#!/bin/bash

# Copyright (c) 2018 Mastercard

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PKCS11LIB=/usr/local/opt/softhsm/lib/softhsm/libsofthsm2.so
PKCS11SLOT=0
PKCS11PASSWORD=changeit
# SO PKCS11PASSWORD=ch@nge1t

SOFTHSM_CONF=softhsm.conf PKCS11LIB=$PKCS11LIB PKCS11SLOT=$PKCS11SLOT PKCS11PASSWORD=$PKCS11PASSWORD "$@"

