#!/bin/sh
# Copyright (c) 2020 Mastercard

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# wrapper script for Belgian eID (libbeidpkcs11) tokens
# see with_pkcs11_common for usage and alternate invocations
#
# Note: Belgian eID does not use a PIN (card PIN is entered via a card reader).

PKCS11SLOT=0
# no PKCS11PASSWORD set

_p11_vendor=beid

# vendor-specific settings
case $(uname -s) in
    Darwin) PKCS11_LIBNAME=libbeidpkcs11.dylib ;;
    *)      PKCS11_LIBNAME=libbeidpkcs11.so    ;;
esac
PKCS11_LIBPATHS=""
LIB_ENVVARS=""

# load common logic
. "$(dirname "$0")/with_pkcs11_common" "$@"
