#!/bin/bash

# Copyright (c) 2018 Mastercard

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PKCS11LIB=/home/eric/work/pkcs11/pkcs11-tools/pkcs11-logger-x64.so
PKCS11NSSDIR=sql:/home/eric/work/pkcs11/pkcs11-tools
PKCS11SLOT=1
PKCS11PASSWORD=changeit

PKCS11_LOGGER_LOG_FILE_PATH=/home/eric/work/pkcs11/pkcs11-tools/pkcs11-logger.log.$$

# 0x01 hex or 1 dec disables logging into the log file
# 0x02 hex or 2 dec disables logging of process id
# 0x04 hex or 4 dec disables logging of thread id
# 0x08 hex or 8 dec enables logging of PINs
# 0x10 hex or 16 dec enables logging to the stdout
# 0x20 hex or 32 dec enables logging to the stderr
PKCS11_LOGGER_FLAGS=0
PKCS11_LOGGER_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so

# execute command with all env vars set
PKCS11LIB=$PKCS11LIB \
PKCS11NSSDIR=$PKCS11NSSDIR \
PKCS11SLOT=$PKCS11SLOT \
PKCS11PASSWORD=$PKCS11PASSWORD \
PKCS11_LOGGER_LOG_FILE_PATH=$PKCS11_LOGGER_LOG_FILE_PATH \
PKCS11_LOGGER_LIBRARY_PATH=$PKCS11_LOGGER_LIBRARY_PATH \
PKCS11_LOGGER_FLAGS=$PKCS11_LOGGER_FLAGS \
"$@"

