#!/bin/sh
# Copyright (c) 2020 Mastercard

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# wrapper script for Entrust nFast/nShield tokens
# see with_pkcs11_common for usage and alternate invocations
#
# nFast-specific notes:
#   - slot 1 is used (OCS is the second slot, after the accelerator slot)
#   - CKNFAST_LOADSHARING and CKNFAST_FAKE_ACCELERATOR_LOGIN are set for typical use
#   - uncomment CKNFAST_DEBUG / CKNFAST_DEBUGDIR for troubleshooting

PKCS11SLOT=1			# OCS is the second slot, after accelerator slot
PKCS11PASSWORD=${PKCS11PASSWORD:-changeit}

_p11_vendor=nfast

# vendor-specific settings
case $(uname -s) in
    Darwin) PKCS11_LIBNAME=libcknfast.dylib ;;
    *)      PKCS11_LIBNAME=libcknfast.so    ;;
esac
PKCS11_LIBPATHS="/opt/nfast/toolkits/pkcs11"
LIB_ENVVARS="CKNFAST_LOADSHARING CKNFAST_FAKE_ACCELERATOR_LOGIN CKNFAST_DEBUG CKNFAST_DEBUGDIR CKNFAST_OVERRIDE_SECURITY_ASSURANCES"

CKNFAST_LOADSHARING=1
CKNFAST_FAKE_ACCELERATOR_LOGIN=1
# CKNFAST_DEBUG=9
# CKNFAST_DEBUGDIR=/var/tmp
# CKNFAST_OVERRIDE_SECURITY_ASSURANCES=all

# load common logic
. "$(dirname "$0")/with_pkcs11_common" "$@"
