#!/bin/sh
# Copyright (c) 2020-2023 Mastercard

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# wrapper script for AWS CloudHSM tokens
# see with_pkcs11_common for usage and alternate invocations
#
# AWS CloudHSM password format: "user:password"

PKCS11PASSWORD=${PKCS11PASSWORD:-user:changeit}

_p11_vendor=aws

# vendor-specific settings
case $(uname -s) in
    Darwin) PKCS11_LIBNAME=libcloudhsm_pkcs11.dylib ;;
    *)      PKCS11_LIBNAME=libcloudhsm_pkcs11.so    ;;
esac
PKCS11_LIBPATHS="/opt/cloudhsm/lib"
LIB_ENVVARS=""

# load common logic
. "$(dirname "$0")/with_pkcs11_common" "$@"
