#!/bin/bash

# Copyright (c) 2018 Mastercard

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PKCS11LIB=/usr/local/opt/nss/lib/libsoftokn3.dylib
PKCS11NSSDIR=sql:.
PKCS11SLOT=1
PKCS11PASSWORD=ch@nge1t

PKCS11LIB=$PKCS11LIB PKCS11NSSDIR=$PKCS11NSSDIR PKCS11SLOT=$PKCS11SLOT PKCS11PASSWORD=$PKCS11PASSWORD "$@"

