#!/bin/sh
# Copyright (c) 2025 Mastercard
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Integration test: additional key types generated by p11keygen.
#   The happy-path test already covers RSA and EC; this one exercises the
#   remaining generator branches that SoftHSM2 supports:
#     - EdDSA Ed25519            (pkcs11_provider_eddsa.c)
#     - EdDSA Ed448
#     - Generic secret / HMAC    (generic-secret keygen branch)
#     - Triple-DES (DES3, 192)   (DES keygen branch)
#   Each key is generated and then confirmed in the p11ls listing with its
#   expected key-type rendering.
#
#   DH and DSA key-pair generation are intentionally omitted: SoftHSM2 rejects
#   them (p11keygen returns code 17), as confirmed by earlier probing.

set -eu

# shellcheck source=/dev/null
. "${PKCS11_TESTS_COMMON:?PKCS11_TESTS_COMMON must be set by the test harness}"

KEYGEN=$(p11bin p11keygen)
P11LS=$(p11bin p11ls)
have_ed448=0

# --- Ed25519 ----------------------------------------------------------------
"$KEYGEN" -l "$PKCS11LIB" -k ed -q ED25519 -i kt-ed25519 \
    sign=true verify=true >/dev/null 2>&1 \
    || die "p11keygen (Ed25519) failed"

# --- Ed448 ------------------------------------------------------------------
if supports_ed448_keygen; then
    have_ed448=1
    "$KEYGEN" -l "$PKCS11LIB" -k ed -q ED448 -i kt-ed448 \
        sign=true verify=true >/dev/null 2>&1 \
        || die "p11keygen (Ed448) failed"
fi

# --- Generic secret / HMAC --------------------------------------------------
"$KEYGEN" -l "$PKCS11LIB" -k generic -b 256 -i kt-hmac \
    sign=true verify=true >/dev/null 2>&1 \
    || die "p11keygen (generic/HMAC) failed"

# --- Triple-DES -------------------------------------------------------------
"$KEYGEN" -l "$PKCS11LIB" -k des -b 192 -i kt-des3 \
    encrypt=true decrypt=true >/dev/null 2>&1 \
    || die "p11keygen (DES3) failed"

# --- confirm each key type in the listing -----------------------------------
ls_out=$("$P11LS" -l "$PKCS11LIB" 2>/dev/null) || die "p11ls returned non-zero"

echo "$ls_out" | grep -q 'prvk/kt-ed25519.*ed(ED25519)' \
    || die "p11ls: Ed25519 private key not rendered as ed(ED25519)"
if [ "$have_ed448" -eq 1 ]; then
    echo "$ls_out" | grep -q 'prvk/kt-ed448.*ed(ED448)' \
        || die "p11ls: Ed448 private key not rendered as ed(ED448)"
fi
echo "$ls_out" | grep -q 'seck/kt-hmac.*generic' \
    || die "p11ls: generic/HMAC secret key not rendered as generic"
echo "$ls_out" | grep -q 'seck/kt-des3.*des(192)' \
    || die "p11ls: DES3 secret key not rendered as des(192)"

echo "key types (Ed25519/Ed448/generic/DES3): OK"
