#line 2 "attribctx_lexer.c"

#line 4 "attribctx_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cl_create_buffer
#define yy_delete_buffer cl_delete_buffer
#define yy_flex_debug cl_flex_debug
#define yy_init_buffer cl_init_buffer
#define yy_flush_buffer cl_flush_buffer
#define yy_load_buffer_state cl_load_buffer_state
#define yy_switch_to_buffer cl_switch_to_buffer
#define yyin clin
#define yyleng clleng
#define yylex cllex
#define yylineno cllineno
#define yyout clout
#define yyrestart clrestart
#define yytext cltext
#define yywrap clwrap
#define yyalloc clalloc
#define yyrealloc clrealloc
#define yyfree clfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

#if defined(__FreeBSD__)
#ifndef __STDC_LIMIT_MACROS
#define	__STDC_LIMIT_MACROS
#endif
#include <sys/cdefs.h>
#include <stdint.h>
#else
#define	__dead2
#endif

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__FreeBSD__) || \
    (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L)

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE clrestart(clin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t clleng;

extern FILE *clin, *clout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cllex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-cllineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < clleng; ++yyl )\
                    if ( cltext[yyl] == '\n' )\
                        --cllineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via clrestart()), so that the user can continue scanning by
	 * just pointing clin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
#define yy_current_buffer YY_CURRENT_BUFFER

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cltext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t clleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow clwrap()'s to do buffer switches
 * instead of setting up a fresh clin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void clrestart (FILE *input_file  );
void cl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cl_create_buffer (FILE *file,int size  );
void cl_delete_buffer (YY_BUFFER_STATE b  );
void cl_flush_buffer (YY_BUFFER_STATE b  );
void clpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void clpop_buffer_state (void );

static void clensure_buffer_stack (void );
static void cl_load_buffer_state (void );
static void cl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cl_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *clalloc (yy_size_t  );
void *clrealloc (void *,yy_size_t  );
void clfree (void *  );

#define yy_new_buffer cl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define clwrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *clin = (FILE *) 0, *clout = (FILE *) 0;

typedef int yy_state_type;

extern int cllineno;

int cllineno = 1;

extern char *cltext;
#define yytext_ptr cltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  ) __dead2;

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	clleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[831] =
    {   0,
        0,    0,    0,    0,   71,   69,   65,   65,    5,    2,
       64,   63,   69,   66,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   67,   68,    1,    3,    4,
       65,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       48,    0,    0,   50,   51,    0,    0,    0,    0,    0,
        6,    0,    0,    0,    0,    0,    5,    0,   63,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    1,    3,    0,   61,   38,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       35,    0,   49,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    5,   64,    0,    0,
        0,    0,    0,   47,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   63,    0,   53,    0,    0,
        0,    0,    0,    0,    0,   52,    0,    0,   36,   37,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   55,   54,    0,
        0,   56,    0,    0,    0,    0,    0,    0,    0,   16,
        0,    0,    0,   63,    0,    0,    0,   14,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       64,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    6,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   48,    0,   50,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   20,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   15,   18,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       38,   35,   49,    0,    0,    0,    0,   47,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   63,
        0,   13,    0,    0,    0,    0,   51,   12,    0,    0,
       34,    0,    0,    0,    0,    0,   60,   21,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       11,   33,    0,    0,    0,    0,   62,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,   14,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   52,    0,
        0,    0,    0,    0,    0,    0,   64,   25,    0,    0,
        0,    0,   27,    0,    0,    0,   10,   39,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    8,    0,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    0,

        0,    0,    0,    0,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   28,
        0,    0,    0,   59,    0,    0,    0,    0,    0,   22,
       40,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   20,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   15,   18,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   51,    0,    0,   57,   24,    0,   54,    0,   56,

        0,    0,    0,    0,   40,    0,   26,    0,    0,    0,
        0,   53,    0,   13,    0,    0,   12,    0,    0,    0,
        0,   21,    0,    0,    0,   11,   33,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   60,    0,    0,    0,    0,    0,
       23,    0,   55,    0,   46,   43,   44,   45,    0,    0,
        0,    0,    0,   25,    0,    0,   27,    0,   10,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   39,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   17,    0,

        0,    0,    0,    0,   28,    0,    0,   22,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   59,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   29,    0,    0,    0,
       24,    0,   26,    0,    0,    0,    0,   51,    0,    0,
        0,    0,    0,    0,    0,   40,    0,    0,   57,    0,
       54,   56,    0,    0,   34,   41,    0,   19,    0,    0,
       23,    0,    0,    0,    0,    0,    0,    0,    0,   46,
       43,   44,   45,   53,    0,   55,   31,    0,   30,    0,
        0,   17,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   29,    0,    0,    0,    0,
        0,   58,   32,    0,    0,   19,    0,   34,   41,   42,
        0,   31,   30,    0,    0,    0,    0,   32,   58,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   14,    1,    1,    1,
       16,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
        1,   33,   34,   35,   36,   37,   38,   39,   40,    1,
        1,    1,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,    1,   58,   59,   60,   61,   62,   63,   64,
       65,    1,   66,    1,   67,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    1,
        1,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[836] =
    {   0,
        0, 1627, 1627, 1626, 1630, 1634,   66,   68, 1634, 1634,
       33,   66,   75, 1634,   70,   71,   79,   75,   76,   80,
       66,   86,   86,   91,   91,   78,  118,  108,  117,  125,
      112,  122,  133,  122,  135, 1634, 1634,    0,    0, 1634,
      155,  180,    0,  125,  139,  179,  165,  151,  163,  180,
     1634,  171,  184, 1588,  164,  184,  170,  181,  181, 1587,
     1634,  172,  197, 1615,  197,  197,  183,  197, 1634,  190,
      208,  214,  214,  231,  230,  233,  228,  235,  235,  227,
      219,  218,  226,  244,  228,    0,    0,  281,    0, 1634,
      237, 1585, 1584, 1583,  276,  248,  243,  282,  267,  276,

      153,  285, 1634,  282,  287,  272, 1582,  273,  275,  289,
      290, 1581,  292, 1580,  291,  291, 1634, 1634, 1579,  280,
      291,  292,  300, 1634,  320,  298,  340,  303,  318,  328,
      334,  339,  326,  336,  330, 1634,  356,  349,  381,  428,
      469,  365,  356,  361,  379, 1634,  357,  366, 1634, 1634,
      379,  385,  394,  379,  399,  426,  430,  429,  419,  432,
      419,  427,  432,  441,  437,  433,  448, 1634, 1634,  441,
      438, 1634,  448,  470, 1578,  254, 1603, 1609, 1608, 1574,
      461,  476,  469, 1634,  467,  487,  483, 1573,  524,  493,
      488,  496,  524,  525,  525,  530,  517,  516,  530,  519,

      523,  535,  524,  537,  563,  541,  540,  544,  567,  545,
      572,  579,  557,  577,  564,  567,  581,  576,  569, 1634,
      588,  575,  587,  581,  575,  581,  595,  584,  602,  615,
     1634,  612,  625,  603, 1634,  616,  616,  622,  627,  614,
      631,  631,  617,  618,  630, 1602, 1599, 1600, 1601, 1568,
      622, 1567,  637, 1634,  636,  626,  620,  626,  683,  638,
      667,  655,  680, 1566,  681,  667, 1634,  663,  686,  685,
      681,  677,  685,  693,  693,  687,  679,  678,  684,  701,
      685,  686, 1634,  704, 1565,  692, 1593,  691,  717,  720,
      716,  715,  722, 1563,  733,  721,  729,  737,  737,  723,

      737,  732,  726, 1562, 1561,  746,  747,  731,  731,  732,
      733,  750,  735,  739,  755,  748,  767,  747,  778, 1560,
     1592, 1558,  775,  772, 1557, 1556, 1555, 1554,  778,  782,
      784,  770,  786, 1548, 1541,  786,  783,  806,  791,  777,
      782,  790,  809,  805,  805, 1538,  806, 1520,  819,  816,
      805,  809,  814,  812,  820,  828,  816,  818,  827,  821,
     1634,  255, 1634,  833,  834, 1519,  835, 1634,  382,  822,
      841,  843,  839,  848, 1517,  836,  856,  854,  867, 1634,
      868, 1634,  855,  859,  859,  864, 1634, 1634,  873,  878,
     1516,  860,  878,  881,  867,  884, 1634, 1515,  876, 1546,

      877,  868,  889,  883,  884,  886,  887,  893,  904,  917,
     1634, 1634,  902,  905,  910,  905, 1634,  924,  908,  926,
      904,  908,  929,  909,  930,  934,  917,  925,  932,  938,
      931, 1513,  922,  937,  930,  926,  955,  951, 1512,  964,
      954,  964,  960,  381, 1537, 1543, 1542,  965, 1634,  966,
      971,  976,  967,  978,  971,  978, 1634, 1634,  979,  984,
      982,  969, 1634,  986,  971,  973, 1634, 1634,  978,  980,
      983,  990, 1534, 1001, 1002, 1015, 1008, 1009, 1010, 1011,
     1024, 1011, 1008, 1023, 1024, 1014, 1025, 1015, 1634, 1033,
     1020, 1032, 1021, 1023, 1039, 1038, 1018, 1634, 1035, 1026,

     1037, 1040,  628, 1065, 1634, 1066, 1056, 1049, 1055, 1053,
     1067, 1065, 1075,  655,  652,  556,  553,  518, 1074, 1069,
     1083, 1071, 1081, 1068, 1085, 1070, 1077, 1074, 1074, 1634,
     1082, 1090, 1101, 1634, 1102, 1113, 1097,  471, 1098, 1634,
     1634, 1122, 1123, 1124, 1125, 1124, 1107, 1124, 1117, 1130,
     1122,  470, 1130, 1124, 1118,  468, 1137, 1120, 1121, 1122,
     1126, 1143, 1140, 1147, 1152, 1164, 1152, 1168,  467,  466,
     1168, 1165, 1174, 1173, 1176,  460,  422,  391,  383,  347,
     1170, 1170,  342, 1161, 1174, 1160, 1180,  336,  334, 1170,
     1186, 1634, 1183, 1186, 1634, 1634, 1166, 1634, 1183, 1634,

     1189, 1191, 1192, 1203, 1634, 1202, 1634, 1202, 1206, 1221,
     1204, 1634, 1219, 1634, 1206, 1213, 1634, 1222, 1227, 1224,
     1228, 1634, 1212, 1231, 1234, 1634, 1634, 1217, 1220, 1225,
     1220, 1223,  315, 1238,  497, 1234, 1236, 1237, 1248, 1244,
     1265, 1255, 1252, 1255, 1634,  281, 1263, 1264, 1264, 1264,
     1634, 1261, 1634, 1266, 1634, 1634, 1634, 1634, 1263, 1271,
     1263, 1266, 1269, 1634, 1282, 1270, 1634, 1287, 1634, 1278,
     1286, 1277, 1275, 1290, 1301, 1291, 1310, 1317, 1304, 1634,
      254,  261, 1310, 1311, 1312, 1313, 1326, 1327, 1328, 1313,
     1320, 1323, 1330, 1331, 1336, 1333, 1334, 1339, 1634, 1340,

     1337, 1339, 1325, 1343, 1634, 1345, 1363, 1634, 1350, 1367,
     1360, 1371, 1363,  226, 1358, 1372,  123,   74, 1377, 1378,
     1379, 1382, 1381, 1366, 1369, 1382, 1634, 1383, 1365, 1366,
     1372, 1373, 1375, 1392, 1387, 1390, 1634, 1400, 1405, 1417,
     1634, 1418, 1634, 1408, 1410, 1425, 1408, 1634, 1425, 1421,
     1422, 1430, 1431, 1432, 1433, 1634, 1432, 1437, 1634, 1415,
     1634, 1634, 1435, 1436, 1634, 1634, 1437, 1634, 1425, 1433,
     1634, 1439, 1445, 1447, 1452, 1455, 1456, 1461, 1462, 1634,
     1634, 1634, 1634, 1634, 1463, 1634, 1634, 1460, 1634, 1473,
     1478, 1634, 1479, 1478, 1479, 1465, 1481, 1486, 1487, 1484,

     1472, 1487, 1473, 1475, 1478, 1634, 1488, 1488, 1515, 1518,
     1503, 1634, 1634, 1518, 1519, 1634, 1506, 1634, 1634, 1634,
     1521, 1634, 1634, 1522, 1511, 1525, 1512, 1634, 1634, 1634,
     1571, 1574, 1580, 1586, 1589
    } ;

static yyconst flex_int16_t yy_def[836] =
    {   0,
      830,    1,  831,  831,  830,  830,  830,  830,  830,  830,
      832,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  833,  834,  830,
      830,  830,  835,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  833,  834,  830,  835,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,    0,
      830,  830,  830,  830,  830
    } ;

static yyconst flex_int16_t yy_nxt[1702] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   14,   15,    6,   16,   17,
       18,   19,   20,   21,   22,    6,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,    6,   35,
        6,   15,    6,   16,   17,   18,   19,   20,   21,   22,
        6,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,    6,   35,   36,   37,   41,   41,   41,
       41,   43,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       44,   45,   58,   54,   55,   49,   43,   46,   47,   50,

       59,   48,   51,   60,   56,   61,   62,   63,   67,   52,
       64,   65,   53,   57,  751,   44,   45,   58,   54,   55,
       49,   66,   46,   47,   50,   59,   48,   51,   60,   56,
       61,   62,   63,   67,   52,   64,   65,   53,   57,   68,
       71,   73,   80,   72,   81,   75,   66,   69,   76,   77,
       74,   82,   70,   83,   84,   85,   41,   41,   90,   78,
       79,  149,  150,  750,   68,   71,   73,   80,   72,   81,
       75,   91,   69,   76,   77,   74,   82,   70,   83,   84,
       85,   96,   97,   90,   78,   79,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   92,   91,   98,   99,  102,

      103,  105,  106,  107,  108,   93,   96,   97,  109,   94,
      110,  112,  100,  101,  113,  115,  116,  117,  118,   95,
       92,  119,   98,   99,  102,  103,  105,  106,  107,  108,
       93,  122,  120,  109,   94,  110,  112,  100,  101,  113,
      115,  116,  117,  118,  121,  123,  119,  124,  125,  127,
      128,  129,  130,  131,  132,  133,  122,  120,  134,  126,
      135,  136,  246,  149,  150,  247,  747,  718,  717,  121,
      123,  138,  124,  125,  127,  128,  129,  130,  131,  132,
      133,  144,  145,  134,  126,  135,  136,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  138,  142,  146,  147,

      148,  151,  152,  154,  155,  157,  144,  145,  158,  159,
      143,  160,  162,  153,  164,  165,  167,  168,  169,  170,
      171,  692,  142,  146,  147,  148,  151,  152,  154,  155,
      157,  174,  180,  158,  159,  143,  160,  162,  153,  164,
      165,  167,  168,  169,  170,  171,  172,  175,  176,  177,
      181,  178,  173,  182,  183,  679,  174,  180,  186,  184,
      187,  188,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  172,  185,  190,  648,  181,  647,  173,  182,  183,
      179,  218,  642,  186,  184,  187,  188,  639,  219,  514,
      444,  445,  515,  446,  220,  221,  222,  185,  190,  191,

      192,  193,  223,  224,  225,  194,  218,  195,  196,  197,
      226,  227,  198,  219,  199,  200,  201,  202,  203,  220,
      221,  222,  447,  638,  191,  192,  193,  223,  224,  225,
      194,  637,  195,  196,  197,  226,  227,  198,  228,  199,
      200,  201,  202,  203,  204,  229,  230,  205,  206,  231,
      207,  232,  233,  234,  235,  236,  208,  237,  238,  239,
      209,  210,  636,  228,  240,  241,  242,  635,  243,  204,
      229,  230,  205,  206,  231,  207,  232,  233,  234,  235,
      236,  208,  237,  238,  239,  209,  210,  211,  212,  240,
      241,  242,  213,  243,  244,  252,  253,  214,  254,  215,

      216,  255,  217,  256,  257,  681,  629,  628,  615,  682,
      611,  599,  211,  212,  260,  261,  263,  213,  262,  244,
      252,  253,  214,  254,  215,  216,  255,  217,  256,  257,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  260,
      261,  263,  264,  262,  267,  268,  269,  270,  271,  276,
      272,  277,  278,  265,  273,  279,  280,  281,  581,  285,
      286,  580,  266,  287,  274,  275,  579,  264,  290,  267,
      268,  269,  270,  271,  276,  272,  277,  278,  265,  273,
      279,  280,  281,  282,  285,  286,  283,  266,  287,  274,
      275,  288,  291,  290,  294,  292,  284,  295,  296,  297,

      289,  299,  298,  300,  301,  302,  303,  304,  282,  293,
      305,  283,  306,  307,  308,  309,  288,  291,  310,  294,
      292,  284,  295,  296,  297,  289,  299,  298,  300,  301,
      302,  303,  304,  311,  293,  305,  312,  306,  307,  308,
      309,  313,  314,  310,  315,  316,  317,  318,  319,  320,
      321,  322,  323,  324,  330,  332,  333,  334,  311,  335,
      336,  312,  339,  337,  578,  577,  313,  314,  566,  315,
      316,  317,  318,  319,  320,  321,  322,  323,  324,  330,
      332,  333,  334,  340,  335,  336,  341,  339,  337,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  342,  345,

      346,  347,  348,  349,  350,  351,  352,  353,  340,  354,
      355,  341,  343,  356,  357,  358,  359,  360,  361,  362,
      363,  365,  367,  342,  345,  346,  347,  348,  349,  350,
      351,  352,  353,  368,  354,  355,  369,  343,  356,  357,
      358,  359,  360,  361,  362,  363,  365,  367,  370,  371,
      372,  374,  375,  376,  377,  378,  379,  380,  368,  381,
      382,  369,  385,  386,  387,  388,  389,  390,  391,  392,
      393,  394,  395,  370,  371,  372,  374,  375,  376,  377,
      378,  379,  380,  396,  381,  382,  397,  385,  386,  387,
      388,  389,  390,  391,  392,  393,  394,  395,  398,  402,

      403,  408,  409,  410,  411,  412,  415,  416,  396,  418,
      419,  397,  417,  417,  417,  417,  417,  417,  417,  417,
      417,  420,  421,  398,  402,  403,  408,  409,  410,  411,
      412,  415,  416,  422,  418,  419,  423,  424,  426,  428,
      429,  430,  431,  432,  433,  434,  420,  421,  435,  436,
      437,  438,  439,  440,  441,  443,  448,  449,  422,  450,
      451,  423,  424,  426,  428,  429,  430,  431,  432,  433,
      434,  452,  454,  435,  436,  437,  438,  439,  440,  441,
      443,  448,  449,  455,  450,  451,  456,  457,  458,  459,
      460,  461,  462,  463,  464,  466,  452,  454,  467,  468,

      469,  470,  472,  474,  475,  476,  477,  478,  455,  479,
      480,  456,  457,  458,  459,  460,  461,  462,  463,  464,
      466,  481,  482,  467,  468,  469,  470,  472,  474,  475,
      476,  477,  478,  483,  479,  480,  484,  485,  486,  487,
      488,  489,  490,  491,  492,  493,  481,  482,  494,  495,
      496,  497,  498,  499,  500,  501,  503,  504,  483,  505,
      506,  484,  485,  486,  487,  488,  489,  490,  491,  492,
      493,  507,  508,  494,  495,  496,  497,  498,  499,  500,
      501,  503,  504,  510,  505,  506,  511,  512,  513,  519,
      520,  521,  522,  523,  524,  525,  507,  508,  526,  527,

      528,  529,  530,  531,  532,  533,  534,  535,  510,  536,
      537,  511,  512,  513,  519,  520,  521,  522,  523,  524,
      525,  539,  540,  526,  527,  528,  529,  530,  531,  532,
      533,  534,  535,  541,  536,  537,  542,  543,  544,  545,
      546,  547,  548,  549,  550,  551,  539,  540,  552,  553,
      554,  555,  556,  557,  558,  559,  560,  561,  541,  562,
      563,  542,  543,  544,  545,  546,  547,  548,  549,  550,
      551,  564,  565,  552,  553,  554,  555,  556,  557,  558,
      559,  560,  561,  567,  562,  563,  568,  569,  570,  571,
      573,  574,  572,  575,  576,  582,  564,  565,  583,  584,

      585,  586,  587,  588,  589,  590,  591,  592,  567,  593,
      594,  568,  569,  570,  571,  573,  574,  572,  575,  576,
      582,  595,  596,  583,  584,  585,  586,  587,  588,  589,
      590,  591,  592,  597,  593,  594,  598,  600,  601,  602,
      603,  604,  605,  606,  607,  608,  595,  596,  609,  610,
      612,  613,  614,  616,  617,  618,  619,  620,  597,  621,
      622,  598,  600,  601,  602,  603,  604,  605,  606,  607,
      608,  623,  624,  609,  610,  612,  613,  614,  616,  617,
      618,  619,  620,  625,  621,  622,  626,  627,  630,  631,
      632,  633,  634,  640,  641,  643,  623,  624,  644,  645,

      646,  649,  650,  651,  652,  653,  654,  655,  625,  656,
      657,  626,  627,  630,  631,  632,  633,  634,  640,  641,
      643,  658,  659,  644,  645,  646,  649,  650,  651,  652,
      653,  654,  655,  660,  656,  657,  661,  662,  663,  664,
      665,  666,  667,  668,  669,  670,  658,  659,  671,  672,
      673,  674,  675,  676,  677,  678,  680,  683,  660,  684,
      685,  661,  662,  663,  664,  665,  666,  667,  668,  669,
      670,  686,  687,  671,  672,  673,  674,  675,  676,  677,
      678,  680,  683,  688,  684,  685,  689,  690,  691,  693,
      694,  695,  696,  697,  698,  699,  686,  687,  700,  701,

      702,  703,  704,  705,  706,  707,  708,  709,  688,  710,
      711,  689,  690,  691,  693,  694,  695,  696,  697,  698,
      699,  712,  713,  700,  701,  702,  703,  704,  705,  706,
      707,  708,  709,  714,  710,  711,  715,  716,  719,  720,
      721,  722,  723,  724,  725,  726,  712,  713,  727,  728,
      729,  730,  731,  732,  733,  734,  735,  736,  714,  737,
      738,  715,  716,  719,  720,  721,  722,  723,  724,  725,
      726,  739,  740,  727,  728,  729,  730,  731,  732,  733,
      734,  735,  736,  741,  737,  738,  742,  743,  744,  745,
      746,  748,  749,  752,  753,  754,  739,  740,  755,  756,

      757,  758,  759,  760,  761,  762,  763,  764,  741,  765,
      766,  742,  743,  744,  745,  746,  748,  749,  752,  753,
      754,  767,  768,  755,  756,  757,  758,  759,  760,  761,
      762,  763,  764,  769,  765,  766,  770,  771,  772,  773,
      774,  775,  776,  777,  778,  779,  767,  768,  780,  781,
      782,  783,  784,  785,  786,  787,  788,  789,  769,  790,
      791,  770,  771,  772,  773,  774,  775,  776,  777,  778,
      779,  792,  793,  780,  781,  782,  783,  784,  785,  786,
      787,  788,  789,  794,  790,  791,  795,  796,  797,  798,
      799,  800,  801,  802,  803,  804,  792,  793,  805,  806,

      807,  808,  809,  810,  811,  812,  813,  814,  794,  815,
      816,  795,  796,  797,  798,  799,  800,  801,  802,  803,
      804,  817,  818,  805,  806,  807,  808,  809,  810,  811,
      812,  813,  814,  819,  815,  816,  820,  821,  822,  823,
      824,  825,  826,  827,  828,  829,  817,  818,  538,  518,
      517,  516,  509,  502,  473,  471,  465,  453,  819,  442,
      427,  820,  821,  822,  823,  824,  825,  826,  827,  828,
      829,   39,   39,   39,   39,   39,   39,   42,  425,   42,
       86,  414,   86,   86,   86,   86,   87,   87,  413,   87,
       87,   87,   89,   89,  407,  406,  405,  404,  401,  400,

      399,  384,  383,  373,  366,  364,  344,  331,  329,  328,
      327,  326,  325,  258,  251,  250,  249,  248,  245,  166,
      163,  161,  156,  141,  140,  139,  114,  111,  104,  830,
       40,   40,   38,    5,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830
    } ;

static yyconst flex_int16_t yy_chk[1702] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    7,    8,
        8,   11,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       15,   16,   19,   18,   18,   17,   11,   16,   16,   17,

       20,   16,   17,   21,   18,   22,   23,   24,   26,   17,
       25,   25,   17,   18,  718,   15,   16,   19,   18,   18,
       17,   25,   16,   16,   17,   20,   16,   17,   21,   18,
       22,   23,   24,   26,   17,   25,   25,   17,   18,   27,
       28,   29,   31,   28,   31,   30,   25,   27,   30,   30,
       29,   32,   27,   33,   34,   35,   41,   41,   44,   30,
       30,  101,  101,  717,   27,   28,   29,   31,   28,   31,
       30,   45,   27,   30,   30,   29,   32,   27,   33,   34,
       35,   47,   48,   44,   30,   30,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   46,   45,   49,   50,   52,

       53,   55,   56,   56,   57,   46,   47,   48,   58,   46,
       59,   62,   50,   50,   63,   65,   66,   67,   68,   46,
       46,   70,   49,   50,   52,   53,   55,   56,   56,   57,
       46,   72,   71,   58,   46,   59,   62,   50,   50,   63,
       65,   66,   67,   68,   71,   73,   70,   74,   75,   76,
       77,   78,   79,   80,   81,   82,   72,   71,   83,   75,
       84,   85,  176,  362,  362,  176,  714,  682,  681,   71,
       73,   91,   74,   75,   76,   77,   78,   79,   80,   81,
       82,   96,   97,   83,   75,   84,   85,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   91,   95,   98,   99,

      100,  102,  104,  105,  106,  108,   96,   97,  109,  110,
       95,  111,  113,  104,  115,  116,  120,  121,  122,  122,
      123,  646,   95,   98,   99,  100,  102,  104,  105,  106,
      108,  126,  128,  109,  110,   95,  111,  113,  104,  115,
      116,  120,  121,  122,  122,  123,  125,  127,  127,  127,
      129,  127,  125,  130,  131,  633,  126,  128,  133,  132,
      134,  135,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  125,  132,  138,  589,  129,  588,  125,  130,  131,
      127,  142,  583,  133,  132,  134,  135,  580,  143,  444,
      369,  369,  444,  369,  144,  145,  147,  132,  138,  139,

      139,  139,  148,  151,  152,  139,  142,  139,  139,  139,
      153,  154,  139,  143,  139,  139,  139,  139,  139,  144,
      145,  147,  369,  579,  139,  139,  139,  148,  151,  152,
      139,  578,  139,  139,  139,  153,  154,  139,  155,  139,
      139,  139,  139,  139,  140,  156,  157,  140,  140,  158,
      140,  159,  160,  161,  162,  163,  140,  164,  165,  166,
      140,  140,  577,  155,  167,  170,  171,  576,  173,  140,
      156,  157,  140,  140,  158,  140,  159,  160,  161,  162,
      163,  140,  164,  165,  166,  140,  140,  141,  141,  167,
      170,  171,  141,  173,  174,  181,  182,  141,  183,  141,

      141,  185,  141,  186,  187,  635,  570,  569,  556,  635,
      552,  538,  141,  141,  190,  191,  192,  141,  191,  174,
      181,  182,  141,  183,  141,  141,  185,  141,  186,  187,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  190,
      191,  192,  193,  191,  194,  195,  196,  197,  198,  200,
      199,  200,  201,  193,  199,  202,  203,  204,  518,  206,
      207,  517,  193,  208,  199,  199,  516,  193,  210,  194,
      195,  196,  197,  198,  200,  199,  200,  201,  193,  199,
      202,  203,  204,  205,  206,  207,  205,  193,  208,  199,
      199,  209,  211,  210,  213,  212,  205,  214,  215,  216,

      209,  217,  216,  218,  219,  221,  222,  223,  205,  212,
      224,  205,  225,  226,  227,  228,  209,  211,  229,  213,
      212,  205,  214,  215,  216,  209,  217,  216,  218,  219,
      221,  222,  223,  230,  212,  224,  232,  225,  226,  227,
      228,  233,  234,  229,  236,  237,  238,  239,  240,  241,
      242,  243,  244,  245,  251,  253,  255,  256,  230,  257,
      258,  232,  260,  258,  515,  514,  233,  234,  503,  236,
      237,  238,  239,  240,  241,  242,  243,  244,  245,  251,
      253,  255,  256,  261,  257,  258,  262,  260,  258,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  263,  265,

      265,  266,  268,  269,  270,  271,  272,  273,  261,  274,
      275,  262,  263,  276,  277,  278,  279,  280,  281,  282,
      284,  286,  288,  263,  265,  265,  266,  268,  269,  270,
      271,  272,  273,  289,  274,  275,  290,  263,  276,  277,
      278,  279,  280,  281,  282,  284,  286,  288,  291,  292,
      293,  295,  296,  297,  298,  299,  300,  301,  289,  302,
      303,  290,  306,  307,  308,  309,  310,  311,  312,  313,
      314,  315,  316,  291,  292,  293,  295,  296,  297,  298,
      299,  300,  301,  317,  302,  303,  318,  306,  307,  308,
      309,  310,  311,  312,  313,  314,  315,  316,  319,  323,

      324,  329,  330,  331,  332,  333,  336,  337,  317,  339,
      340,  318,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  341,  342,  319,  323,  324,  329,  330,  331,  332,
      333,  336,  337,  343,  339,  340,  344,  345,  347,  349,
      350,  351,  352,  353,  354,  355,  341,  342,  356,  357,
      358,  359,  360,  364,  365,  367,  370,  371,  343,  372,
      373,  344,  345,  347,  349,  350,  351,  352,  353,  354,
      355,  374,  376,  356,  357,  358,  359,  360,  364,  365,
      367,  370,  371,  377,  372,  373,  378,  379,  381,  383,
      384,  385,  386,  389,  390,  392,  374,  376,  393,  394,

      395,  396,  399,  401,  402,  403,  404,  405,  377,  406,
      407,  378,  379,  381,  383,  384,  385,  386,  389,  390,
      392,  408,  409,  393,  394,  395,  396,  399,  401,  402,
      403,  404,  405,  410,  406,  407,  413,  414,  415,  416,
      418,  419,  420,  421,  422,  423,  408,  409,  424,  425,
      426,  427,  428,  429,  430,  431,  433,  434,  410,  435,
      436,  413,  414,  415,  416,  418,  419,  420,  421,  422,
      423,  437,  438,  424,  425,  426,  427,  428,  429,  430,
      431,  433,  434,  440,  435,  436,  441,  442,  443,  448,
      450,  451,  452,  453,  454,  455,  437,  438,  456,  459,

      460,  461,  462,  464,  465,  466,  469,  470,  440,  471,
      472,  441,  442,  443,  448,  450,  451,  452,  453,  454,
      455,  474,  475,  456,  459,  460,  461,  462,  464,  465,
      466,  469,  470,  476,  471,  472,  477,  478,  479,  480,
      481,  482,  483,  484,  485,  486,  474,  475,  487,  488,
      490,  491,  492,  493,  494,  495,  496,  497,  476,  499,
      500,  477,  478,  479,  480,  481,  482,  483,  484,  485,
      486,  501,  502,  487,  488,  490,  491,  492,  493,  494,
      495,  496,  497,  504,  499,  500,  506,  507,  508,  509,
      510,  511,  509,  512,  513,  519,  501,  502,  520,  521,

      522,  523,  524,  525,  526,  527,  528,  529,  504,  531,
      532,  506,  507,  508,  509,  510,  511,  509,  512,  513,
      519,  533,  535,  520,  521,  522,  523,  524,  525,  526,
      527,  528,  529,  536,  531,  532,  537,  539,  542,  543,
      544,  545,  546,  547,  548,  549,  533,  535,  550,  551,
      553,  554,  555,  557,  558,  559,  560,  561,  536,  562,
      563,  537,  539,  542,  543,  544,  545,  546,  547,  548,
      549,  564,  565,  550,  551,  553,  554,  555,  557,  558,
      559,  560,  561,  566,  562,  563,  567,  568,  571,  572,
      573,  574,  575,  581,  582,  584,  564,  565,  585,  586,

      587,  590,  591,  593,  594,  597,  599,  601,  566,  602,
      603,  567,  568,  571,  572,  573,  574,  575,  581,  582,
      584,  604,  606,  585,  586,  587,  590,  591,  593,  594,
      597,  599,  601,  608,  602,  603,  609,  610,  611,  613,
      615,  616,  618,  619,  620,  621,  604,  606,  623,  624,
      625,  628,  629,  630,  631,  632,  634,  636,  608,  637,
      638,  609,  610,  611,  613,  615,  616,  618,  619,  620,
      621,  639,  640,  623,  624,  625,  628,  629,  630,  631,
      632,  634,  636,  641,  637,  638,  642,  643,  644,  647,
      648,  649,  650,  652,  654,  659,  639,  640,  660,  661,

      662,  663,  665,  666,  668,  670,  671,  672,  641,  673,
      674,  642,  643,  644,  647,  648,  649,  650,  652,  654,
      659,  675,  676,  660,  661,  662,  663,  665,  666,  668,
      670,  671,  672,  677,  673,  674,  678,  679,  683,  684,
      685,  686,  687,  688,  689,  690,  675,  676,  691,  692,
      693,  694,  695,  696,  697,  698,  700,  701,  677,  702,
      703,  678,  679,  683,  684,  685,  686,  687,  688,  689,
      690,  704,  706,  691,  692,  693,  694,  695,  696,  697,
      698,  700,  701,  707,  702,  703,  709,  710,  711,  712,
      713,  715,  716,  719,  720,  721,  704,  706,  722,  723,

      724,  725,  726,  728,  729,  730,  731,  732,  707,  733,
      734,  709,  710,  711,  712,  713,  715,  716,  719,  720,
      721,  735,  736,  722,  723,  724,  725,  726,  728,  729,
      730,  731,  732,  738,  733,  734,  739,  740,  742,  744,
      745,  746,  747,  749,  750,  751,  735,  736,  752,  753,
      754,  755,  757,  758,  760,  763,  764,  767,  738,  769,
      770,  739,  740,  742,  744,  745,  746,  747,  749,  750,
      751,  772,  773,  752,  753,  754,  755,  757,  758,  760,
      763,  764,  767,  774,  769,  770,  775,  776,  777,  778,
      779,  785,  788,  790,  791,  793,  772,  773,  794,  795,

      796,  797,  798,  799,  800,  801,  802,  803,  774,  804,
      805,  775,  776,  777,  778,  779,  785,  788,  790,  791,
      793,  807,  808,  794,  795,  796,  797,  798,  799,  800,
      801,  802,  803,  809,  804,  805,  810,  811,  814,  815,
      817,  821,  824,  825,  826,  827,  807,  808,  473,  447,
      446,  445,  439,  432,  400,  398,  391,  375,  809,  366,
      348,  810,  811,  814,  815,  817,  821,  824,  825,  826,
      827,  831,  831,  831,  831,  831,  831,  832,  346,  832,
      833,  335,  833,  833,  833,  833,  834,  834,  334,  834,
      834,  834,  835,  835,  328,  327,  326,  325,  322,  321,

      320,  305,  304,  294,  287,  285,  264,  252,  250,  249,
      248,  247,  246,  188,  180,  179,  178,  177,  175,  119,
      114,  112,  107,   94,   93,   92,   64,   60,   54,    5,
        4,    3,    2,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,
      830,  830,  830,  830,  830,  830,  830,  830,  830,  830,

      830
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[71] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cl_flex_debug;
int cl_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cltext;
#line 1 "attribctx_lexer.l"
/* attributes lexical analyser */
/*
 * Copyright (c) 2018 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* %option debug */
#line 27 "attribctx_lexer.l"
#include "config.h"
#include <stdarg.h>
#include "attribctx_parser.h"


#line 1181 "attribctx_lexer.c"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cllex_destroy (void );

int clget_debug (void );

void clset_debug (int debug_flag  );

YY_EXTRA_TYPE clget_extra (void );

void clset_extra (YY_EXTRA_TYPE user_defined  );

FILE *clget_in (void );

void clset_in  (FILE * in_str  );

FILE *clget_out (void );

void clset_out  (FILE * out_str  );

yy_size_t clget_leng (void );

char *clget_text (void );

int clget_lineno (void );

void clset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int clwrap (void );
#else
extern int clwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    static void yyunput (int c,char *buf_ptr  );
#endif
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cltext, clleng, 1, clout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( clin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( clin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, clin))==0 && ferror(clin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(clin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cllex (void);

#define YY_DECL int cllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cltext and clleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( clleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(cltext[clleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
#line 34 "attribctx_lexer.l"


#line 1372 "attribctx_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! clin )
			clin = stdin;

		if ( ! clout )
			clout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			clensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cl_create_buffer(clin,YY_BUF_SIZE );
		}

		cl_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 831 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 830 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < clleng; ++yyl )
				if ( cltext[yyl] == '\n' )
					   
    cllineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "attribctx_lexer.l"
{ /* skipping comment */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "attribctx_lexer.l"
{ cllval.val_str.len=0; BEGIN(STR); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 39 "attribctx_lexer.l"
{ cllval.val_str.val = strdup(cltext); cllval.val_str.len = strlen(cltext); }
	YY_BREAK
case YY_STATE_EOF(STR):
#line 40 "attribctx_lexer.l"
{ clerror(NULL, "Unterminated quoted string"); yyterminate(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "attribctx_lexer.l"
{   /* special case: if we have an empty string, regular rule is never executed */
		/* in which case, we perform the empty string assignment from here */
    if (cllval.val_str.len==0) { cllval.val_str.val=strdup(""); } BEGIN(INITIAL); return STRING;
	    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "attribctx_lexer.l"
{ return NO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "attribctx_lexer.l"
{ cllval.ckattr = CKA_ID; return CKATTR_STR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "attribctx_lexer.l"
{ cllval.ckattr = CKA_LABEL; return CKATTR_STR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "attribctx_lexer.l"
{ cllval.ckattr = CKA_CLASS; return CKATTR_CLASS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "attribctx_lexer.l"
{ cllval.ckattr = CKA_TOKEN; return CKATTR_BOOL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "attribctx_lexer.l"
{ cllval.ckattr = CKA_KEY_TYPE; return CKATTR_KEY; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "attribctx_lexer.l"
{ cllval.ckattr = CKA_SUBJECT; return CKATTR_STR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "attribctx_lexer.l"
{ cllval.ckattr = CKA_ENCRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "attribctx_lexer.l"
{ cllval.ckattr = CKA_DECRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "attribctx_lexer.l"
{ cllval.ckattr = CKA_WRAP; return CKATTR_BOOL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "attribctx_lexer.l"
{ cllval.ckattr = CKA_UNWRAP; return CKATTR_BOOL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "attribctx_lexer.l"
{ cllval.ckattr = CKA_SIGN; return CKATTR_BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "attribctx_lexer.l"
{ cllval.ckattr = CKA_SIGN_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "attribctx_lexer.l"
{ cllval.ckattr = CKA_VERIFY; return CKATTR_BOOL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "attribctx_lexer.l"
{ cllval.ckattr = CKA_VERIFY_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "attribctx_lexer.l"
{ cllval.ckattr = CKA_DERIVE; return CKATTR_BOOL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "attribctx_lexer.l"
{ cllval.ckattr = CKA_PRIVATE; return CKATTR_BOOL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "attribctx_lexer.l"
{ cllval.ckattr = CKA_SENSITIVE; return CKATTR_BOOL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "attribctx_lexer.l"
{ cllval.ckattr = CKA_EXTRACTABLE; return CKATTR_BOOL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "attribctx_lexer.l"
{ cllval.ckattr = CKA_MODIFIABLE; return CKATTR_BOOL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "attribctx_lexer.l"
{ cllval.ckattr = CKA_COPYABLE; return CKATTR_BOOL; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "attribctx_lexer.l"
{ cllval.ckattr = CKA_START_DATE; return CKATTR_DATE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "attribctx_lexer.l"
{ cllval.ckattr = CKA_END_DATE; return CKATTR_DATE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "attribctx_lexer.l"
{ cllval.ckattr = CKA_EC_PARAMS; return CKATTR_STR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "attribctx_lexer.l"
{ cllval.ckattr = CKA_WRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "attribctx_lexer.l"
{ cllval.ckattr = CKA_UNWRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "attribctx_lexer.l"
{ cllval.ckattr = CKA_DERIVE_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "attribctx_lexer.l"
{ cllval.ckattr = CKA_WRAP_WITH_TRUSTED; return CKATTR_BOOL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "attribctx_lexer.l"
{ cllval.ckattr = CKA_TRUSTED; return CKATTR_BOOL; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "attribctx_lexer.l"
{ cllval.val_key = CKK_GENERIC_SECRET; return KEYTYPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "attribctx_lexer.l"
{ cllval.val_key = CKK_DES           ; return KEYTYPE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "attribctx_lexer.l"
{ cllval.val_key = CKK_DES2          ; return KEYTYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "attribctx_lexer.l"
{ cllval.val_key = CKK_DES3          ; return KEYTYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "attribctx_lexer.l"
{ cllval.val_key = CKK_AES           ; return KEYTYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "attribctx_lexer.l"
{ cllval.val_key = CKK_MD5_HMAC      ; return KEYTYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "attribctx_lexer.l"
{ cllval.val_key = CKK_SHA_1_HMAC    ; return KEYTYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "attribctx_lexer.l"
{ cllval.val_key = CKK_RIPEMD128_HMAC; return KEYTYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "attribctx_lexer.l"
{ cllval.val_key = CKK_RIPEMD160_HMAC; return KEYTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "attribctx_lexer.l"
{ cllval.val_key = CKK_SHA256_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "attribctx_lexer.l"
{ cllval.val_key = CKK_SHA384_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "attribctx_lexer.l"
{ cllval.val_key = CKK_SHA512_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "attribctx_lexer.l"
{ cllval.val_key = CKK_SHA224_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "attribctx_lexer.l"
{ cllval.val_key = CKK_RSA           ; return KEYTYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "attribctx_lexer.l"
{ cllval.val_key = CKK_DH            ; return KEYTYPE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "attribctx_lexer.l"
{ cllval.val_key = CKK_DSA           ; return KEYTYPE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "attribctx_lexer.l"
{ cllval.val_key = CKK_EC            ; return KEYTYPE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "attribctx_lexer.l"
{ cllval.val_key = CKK_EC_EDWARDS    ; return KEYTYPE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 96 "attribctx_lexer.l"
{ cllval.val_cls = CKO_DATA ; return OCLASS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 97 "attribctx_lexer.l"
{ cllval.val_cls = CKO_CERTIFICATE ; return OCLASS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 98 "attribctx_lexer.l"
{ cllval.val_cls = CKO_PUBLIC_KEY ; return OCLASS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 99 "attribctx_lexer.l"
{ cllval.val_cls = CKO_PRIVATE_KEY ; return OCLASS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 100 "attribctx_lexer.l"
{ cllval.val_cls = CKO_SECRET_KEY ; return OCLASS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 101 "attribctx_lexer.l"
{ cllval.val_cls = CKO_HW_FEATURE ; return OCLASS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 102 "attribctx_lexer.l"
{ cllval.val_cls = CKO_DOMAIN_PARAMETERS ; return OCLASS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 103 "attribctx_lexer.l"
{ cllval.val_cls = CKO_MECHANISM ; return OCLASS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 104 "attribctx_lexer.l"
{ cllval.val_cls = CKO_OTP_KEY ; return OCLASS; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 106 "attribctx_lexer.l"
{   if(strlen(cltext)%2==1) {
			clerror(NULL, "Invalid hexadecimal string <%s>: odd length", cltext);
			yyterminate();
		    } else {
			cllval.val_str.len = (strlen(cltext)>>1) - 1; /* we skip the '0x' prefix */
			/* convert to hex */
			size_t i;
			char *target = malloc(cllval.val_str.len);
			if(target==NULL) {
			    cllval.val_str.len = 0 ;
			    clerror(NULL,"Memory allocation error during lexical analysis of <%s>", cltext);
			    yyterminate();
			}

			/* we start at cltext[2] */
			for(i=0;i<cllval.val_str.len; i++) {
			    /* the following trick is needed to have CLANG shut up */
			    /* strictly speaking, %x expects indeed a pointer to an integer */

			    volatile int tmp;
			    sscanf( &cltext[ (i<<1) + 2 ], "%2x", &tmp);
			    target[i] = (unsigned char) tmp;
			}
			cllval.val_str.val = target; /* then reassign */
			return STRING;
		    }
		}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 134 "attribctx_lexer.l"
{ memcpy(cllval.val_date.as_buffer, cltext, 8); return TOK_DATE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 136 "attribctx_lexer.l"
{ cllval.val_bool = 1; return TOK_BOOLEAN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 137 "attribctx_lexer.l"
{ cllval.val_bool = 0; return TOK_BOOLEAN; }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 139 "attribctx_lexer.l"
{ /* ignore whitespace and comma */ }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "attribctx_lexer.l"
{ return ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "attribctx_lexer.l"
{ return CURLY_OPEN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "attribctx_lexer.l"
{ return CURLY_CLOSE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 143 "attribctx_lexer.l"
{ return cltext[0]; } /* catch-all http://stackoverflow.com/questions/18837828/how-should-i-handle-lexical-errors-in-my-flex-lexer */
	YY_BREAK
/* gives it back to bison, so error comes from parser */
case 70:
YY_RULE_SETUP
#line 146 "attribctx_lexer.l"
ECHO;
	YY_BREAK
#line 1848 "attribctx_lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed clin at a new source and called
			 * cllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = clin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( clwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					clrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			clrestart(clin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) clrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 831 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 831 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 830);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --cllineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif	/* ifndef YY_NO_UNPUT */

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					clrestart(clin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( clwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    cllineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void clrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        clensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cl_create_buffer(clin,YY_BUF_SIZE );
	}

	cl_init_buffer(YY_CURRENT_BUFFER,input_file );
	cl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		clpop_buffer_state();
	 *		clpush_buffer_state(new_buffer);
     */
	clensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (clwrap()) processing, but the only time this flag
	 * is looked at is after clwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cl_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	clin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cl_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) clalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cl_create_buffer()
 * 
 */
    void cl_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		clfree((void *) b->yy_ch_buf  );

	clfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a clrestart() or at EOF.
 */
    static void cl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cl_init_buffer was _probably_
     * called from clrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cl_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cl_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void clpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	clensure_buffer_stack();

	/* This block is copied from cl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cl_switch_to_buffer. */
	cl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void clpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void clensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)clalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)clrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cl_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cl_scan_bytes() instead.
 */
YY_BUFFER_STATE cl_scan_string (yyconst char * yystr )
{
    
	return cl_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cl_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) clalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cltext[clleng] = (yy_hold_char); \
		(yy_c_buf_p) = cltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		clleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int clget_lineno  (void)
{
        
    return cllineno;
}

/** Get the input stream.
 * 
 */
FILE *clget_in  (void)
{
        return clin;
}

/** Get the output stream.
 * 
 */
FILE *clget_out  (void)
{
        return clout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t clget_leng  (void)
{
        return clleng;
}

/** Get the current token.
 * 
 */

char *clget_text  (void)
{
        return cltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void clset_lineno (int  line_number )
{
    
    cllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cl_switch_to_buffer
 */
void clset_in (FILE *  in_str )
{
        clin = in_str ;
}

void clset_out (FILE *  out_str )
{
        clout = out_str ;
}

int clget_debug  (void)
{
        return cl_flex_debug;
}

void clset_debug (int  bdebug )
{
        cl_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cllex_destroy(), so don't allocate here.
     */

    /* We do not touch cllineno unless the option is enabled. */
    cllineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    clin = stdin;
    clout = stdout;
#else
    clin = (FILE *) 0;
    clout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cllex_init()
     */
    return 0;
}

/* cllex_destroy is for both reentrant and non-reentrant scanners. */
int cllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		clpop_buffer_state();
	}

	/* Destroy the stack itself. */
	clfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *clalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *clrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void clfree (void * ptr )
{
	free( (char *) ptr );	/* see clrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 146 "attribctx_lexer.l"




void clerror(attribCtx *ctx, const char *s, ...)
{
    va_list ap;
    va_start(ap, s);

    fprintf(stderr, "Error during parsing at line %d: ", cllineno);
    vfprintf(stderr, s, ap);
    fprintf(stderr, "\n");

    va_end(ap);
}

