#line 2 "cmdline_lexer.c"

#line 4 "cmdline_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cl_create_buffer
#define yy_delete_buffer cl_delete_buffer
#define yy_flex_debug cl_flex_debug
#define yy_init_buffer cl_init_buffer
#define yy_flush_buffer cl_flush_buffer
#define yy_load_buffer_state cl_load_buffer_state
#define yy_switch_to_buffer cl_switch_to_buffer
#define yyin clin
#define yyleng clleng
#define yylex cllex
#define yylineno cllineno
#define yyout clout
#define yyrestart clrestart
#define yytext cltext
#define yywrap clwrap
#define yyalloc clalloc
#define yyrealloc clrealloc
#define yyfree clfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

#if defined(__FreeBSD__)
#ifndef __STDC_LIMIT_MACROS
#define	__STDC_LIMIT_MACROS
#endif
#include <sys/cdefs.h>
#include <stdint.h>
#else
#define	__dead2
#endif

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__FreeBSD__) || \
    (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L)

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE clrestart(clin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t clleng;

extern FILE *clin, *clout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cllex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-cllineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < clleng; ++yyl )\
                    if ( cltext[yyl] == '\n' )\
                        --cllineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via clrestart()), so that the user can continue scanning by
	 * just pointing clin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
#define yy_current_buffer YY_CURRENT_BUFFER

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cltext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t clleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow clwrap()'s to do buffer switches
 * instead of setting up a fresh clin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void clrestart (FILE *input_file  );
void cl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cl_create_buffer (FILE *file,int size  );
void cl_delete_buffer (YY_BUFFER_STATE b  );
void cl_flush_buffer (YY_BUFFER_STATE b  );
void clpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void clpop_buffer_state (void );

static void clensure_buffer_stack (void );
static void cl_load_buffer_state (void );
static void cl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cl_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *clalloc (yy_size_t  );
void *clrealloc (void *,yy_size_t  );
void clfree (void *  );

#define yy_new_buffer cl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define clwrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *clin = (FILE *) 0, *clout = (FILE *) 0;

typedef int yy_state_type;

extern int cllineno;

int cllineno = 1;

extern char *cltext;
#define yytext_ptr cltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  ) __dead2;

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	clleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[576] =
    {   0,
        0,    0,    0,    0,   65,   63,   62,   62,    2,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   60,   61,    1,
        3,    4,   62,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    5,    0,    0,    0,   57,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    1,    3,
        0,   58,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   56,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   15,    0,    0,
        0,   56,    0,    0,   13,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    7,    0,    0,    0,    0,
        0,    0,   57,    0,    6,    0,    0,    0,    0,    0,
        0,    8,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    5,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   43,    0,   45,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   19,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   14,   17,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   33,   30,   44,    0,    0,    0,    0,   42,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       56,   12,    0,   11,    0,    0,    0,    0,   20,    0,
        0,    0,   10,    0,    0,    0,   59,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,
        0,    0,    0,    0,    0,   13,   31,   32,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   47,    0,    0,
        0,    0,    0,    0,    0,   57,    0,   25,    0,    9,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    0,
        0,    0,    0,    0,    0,    6,    0,    0,    0,    0,
        0,    0,    8,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   26,    0,    0,   21,    0,    0,    0,
        0,    0,    0,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   14,   17,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   23,    0,   24,    0,
        0,    0,   12,    0,   11,    0,    0,    0,    0,   20,
        0,    0,    0,   10,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       55,    0,    0,    0,   22,    0,    0,    0,    0,    0,
       25,    0,    9,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   34,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   16,    0,    0,
        0,   26,    0,    0,   21,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   54,    0,    0,    0,    0,    0,   27,    0,
       23,    0,   24,    0,    0,    0,   46,    0,    0,    0,
        0,    0,    0,    0,   35,    0,    0,   52,    0,   49,
       51,    0,   18,   22,    0,    0,    0,    0,    0,    0,
        0,   41,   38,   39,   40,   48,    0,   50,   28,   16,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   27,
        0,    0,    0,    0,    0,   18,   29,   36,   37,    0,
       28,    0,    0,   53,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   13,    1,    1,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
        1,   31,   32,   33,   34,   35,   36,   37,   38,    1,
        1,    1,    1,    1,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,   56,   57,   58,   59,   60,   61,   62,
       63,    1,   64,    1,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[66] =
    {   0,
        1,    1,    2,    3,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,    1,    1,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[581] =
    {   0,
        0, 1158, 1158, 1157, 1160, 1164,   64,   66, 1164,   33,
       65,   55,   63,   66,   69,   67,   67,   72,   59,   60,
       59,   97,   67,   64,   74,   66,   80, 1164, 1164,    0,
        0, 1164,   98,  126,    0,  128,   87,  127, 1120,  108,
       71,  120, 1164,  109,  132,  131, 1164,  129,  126,  138,
      145,  145,  137,  129,  128,  134,  151,  138,    0,    0,
      190,    0, 1119, 1118, 1112,  160,  149,  161,  171,  177,
      177, 1105,  178,  178, 1102,  192,  189,  178,  182,  187,
      185,  196,  202,  203,  192,  201,  195, 1164,  245,  243,
      290,  331,  227,  232,  232,  227,  236,  257,  236,  263,

      267,  291,  279,  287,  294,  300,  293, 1093,  285,  300,
      292, 1164,  310,  306, 1092,  358,  301,  310,  359,  313,
      313,  340,  330,  344,  358,  350,  354,  370,  359,  374,
      376,  377,  378,  381,  402,  381,  386,  398,  374,  392,
      393,  398,  412,  411,  405, 1164,  410,  422,  411,  413,
      429,  428, 1164,  408, 1164,  424,  415,  416,  422, 1090,
      438, 1164,  428,  422,  428,  481,  460,  465, 1088,  459,
      446, 1164,  443,  468,  479,  475,  471,  482,  490,  492,
      485,  475,  481,  498,  482,  483, 1164,  501, 1086,  489,
     1111,  488,  504,  505,  494,  493,  500, 1082,  512,  501,

      509,  518,  529,  515,  529,  516, 1164,  538,  522,  525,
      527,  531,  547,  544,  541,  546,  548,  534, 1081, 1080,
      549,  588,  547,  550,  559,  554,  572, 1079,  574, 1078,
      589,  587,  576,  580,  585,  583,  591,  597,  586,  595,
      589, 1164,  167, 1164,  601,  602, 1077,  603, 1164,  615,
      592,  612,  616,  612,  612, 1076,  613,  623,  620,  634,
     1164, 1164,  628, 1164,  639,  645,  642,  646, 1164,  628,
      647,  650, 1164,  633,  636,  641, 1164,  637,  632,  636,
      657,  637,  659,  664,  648,  656,  664,  683,  676, 1075,
      668,  684,  677,  693,  690, 1074, 1164, 1164,  693,  681,

      691,  687,  218, 1098, 1104, 1103,  692, 1164,  693,  698,
      703,  694,  705,  698,  703, 1164,  693, 1164,  711, 1164,
      703,  712,  703,  701,  729,  730,  721, 1164,  723,  736,
      727,  730,  746,  745,  725, 1164,  741,  732,  733,  736,
      590,  751, 1164,  739,  732,  738,  736,  752,  750,  761,
      567,  564,  565,  562,  530,  761,  754,  769,  770,  780,
      768,  786,  772, 1164,  782,  791, 1164,  776,  793,  786,
      797,  789,  783, 1164,  802,  785,  786,  787,  791,  807,
      806,  804,  810,  813,  799,  424,  370,  815,  833,  832,
      836,  355,  289,  285,  284,  253,  831,  832,  245,  825,

      837,  823,  843,  244,  241,  844, 1164,  845, 1164,  835,
      837,  852, 1164,  841, 1164,  850,  855,  852,  856, 1164,
      840,  860,  864, 1164,  848,  851,  857,  867,  205,  882,
      219,  879,  881,  883,  886,  883,  894,  882,  879,  882,
     1164,  204,  890,  891, 1164,  886,  892,  884,  887,  889,
     1164,  906, 1164,  899,  908,  900,  898,  913,  915,  918,
      931,  919, 1164,  216,  222,  926,  928,  931,  933,  946,
      947,  948,  933,  938,  941,  948,  949, 1164,  954,  951,
      952, 1164,  946,  956, 1164,  942,  960,  954,  965,  958,
      966,  980,  103,   52,  986,  988,  990,  993,  993,  978,

      981,  994, 1164,  995,  977,  978,  984,  987, 1164, 1000,
     1164, 1001, 1164,  991,  993, 1010, 1164, 1010, 1007, 1009,
     1015, 1017, 1031, 1032, 1164, 1032, 1038, 1164, 1017, 1164,
     1164, 1039, 1164, 1164, 1029, 1035, 1027, 1030, 1033, 1038,
     1039, 1164, 1164, 1164, 1164, 1164, 1040, 1164, 1164, 1164,
     1053, 1050, 1051, 1052, 1057, 1060, 1058, 1046, 1050, 1164,
     1049, 1067, 1081, 1066, 1082, 1164, 1164, 1164, 1164, 1084,
     1164, 1074, 1076, 1164, 1164, 1133, 1136, 1142, 1148, 1151
    } ;

static yyconst flex_int16_t yy_def[581] =
    {   0,
      575,    1,  576,  576,  575,  575,  575,  575,  575,  577,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  578,
      579,  575,  575,  575,  580,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  578,  579,
      575,  580,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,    0,  575,  575,  575,  575,  575
    } ;

static yyconst flex_int16_t yy_nxt[1230] =
    {   0,
        6,    7,    8,    9,    6,   10,   11,   11,   11,   11,
       11,   11,   11,   11,    6,    6,   12,   13,   14,   15,
        6,    6,   16,    6,   17,   18,   19,   20,    6,   21,
        6,   22,   23,   24,   25,   26,    6,   27,    6,    6,
        6,   12,   13,   14,   15,    6,    6,   16,    6,   17,
       18,   19,   20,    6,   21,    6,   22,   23,   24,   25,
       26,    6,   27,   28,   29,   33,   33,   33,   33,   35,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   36,
       37,   38,   39,   42,   43,   44,   45,   46,   47,   48,
      520,   55,   56,   40,   35,   53,   57,   54,   58,   33,

       33,   67,   41,   73,   36,   37,   38,   39,   42,   43,
       44,   45,   46,   47,   48,   49,   55,   56,   40,   50,
       53,   57,   54,   58,   71,   72,   67,   41,   73,   51,
       52,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       49,  519,   63,   68,   50,   74,   75,   76,   77,   71,
       72,   78,   64,   79,   51,   52,   65,   69,   80,   81,
       82,   83,   84,   85,   86,   87,   66,   63,   68,   88,
       74,   75,   76,   77,  297,  298,   78,   64,   79,   93,
       95,   65,   69,   80,   81,   82,   83,   84,   85,   86,
       87,   96,   94,   97,   88,   89,   89,   89,   89,   89,

       89,   89,   89,   89,   93,   95,   98,   99,  101,  102,
      104,  105,  106,  107,  108,  109,   96,   94,   97,  110,
      111,  112,  113,  114,  115,  351,  464,  494,  352,  493,
      465,   98,   99,  101,  102,  104,  105,  106,  107,  108,
      109,  144,  475,  462,  110,  111,  112,  113,  114,  115,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  117,
      118,  119,  145,  146,  147,  120,  144,  121,  122,  123,
      148,  149,  124,  150,  125,  126,  127,  128,  129,  444,
      151,  152,  443,  438,  117,  118,  119,  145,  146,  147,
      120,  435,  121,  122,  123,  148,  149,  124,  150,  125,

      126,  127,  128,  129,  130,  151,  152,  131,  132,  153,
      133,  154,  155,  156,  157,  158,  134,  160,  161,  162,
      135,  136,  434,  433,  163,  164,  167,  432,  168,  130,
      172,  173,  131,  132,  153,  133,  154,  155,  156,  157,
      158,  134,  160,  161,  162,  135,  136,  137,  138,  163,
      164,  167,  139,  168,  174,  172,  173,  140,  175,  141,
      142,  431,  143,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  137,  138,  176,  169,  177,  139,  181,  174,
      178,  182,  140,  175,  141,  142,  170,  143,  183,  184,
      179,  180,  185,  189,  186,  171,  190,  187,  191,  176,

      169,  177,  194,  181,  195,  178,  182,  188,  426,  198,
      199,  170,  196,  183,  184,  179,  180,  185,  189,  186,
      171,  190,  187,  191,  192,  200,  197,  194,  201,  195,
      203,  202,  188,  193,  198,  199,  204,  196,  205,  206,
      207,  208,  209,  210,  211,  212,  213,  214,  215,  192,
      200,  197,  216,  201,  218,  203,  202,  219,  193,  220,
      221,  204,  425,  205,  206,  207,  208,  209,  210,  211,
      212,  213,  214,  215,  223,  227,  228,  216,  229,  218,
      230,  224,  219,  231,  220,  221,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  225,  232,  233,  234,  223,

      227,  228,  235,  229,  236,  230,  224,  237,  231,  238,
      239,  240,  241,  242,  243,  244,  246,  248,  249,  250,
      225,  232,  233,  234,  251,  252,  253,  235,  255,  236,
      256,  257,  237,  258,  238,  239,  240,  241,  242,  243,
      244,  246,  248,  249,  250,  259,  260,  261,  262,  251,
      252,  253,  263,  255,  264,  256,  257,  265,  258,  266,
      267,  268,  269,  270,  271,  272,  273,  276,  397,  396,
      259,  260,  261,  262,  395,  394,  393,  263,  278,  264,
      279,  280,  265,  281,  266,  267,  268,  269,  270,  271,
      272,  273,  276,  277,  277,  277,  277,  277,  277,  277,

      277,  277,  282,  278,  284,  279,  280,  286,  281,  287,
      288,  289,  290,  291,  292,  293,  294,  295,  296,  299,
      300,  302,  303,  304,  307,  305,  308,  282,  384,  284,
      309,  310,  286,  311,  287,  288,  289,  290,  291,  292,
      293,  294,  295,  296,  299,  300,  302,  313,  314,  307,
      315,  308,  316,  306,  317,  309,  310,  318,  311,  319,
      320,  321,  322,  323,  324,  325,  326,  327,  328,  329,
      330,  331,  313,  314,  332,  315,  333,  316,  334,  317,
      335,  336,  318,  337,  319,  320,  321,  322,  323,  324,
      325,  326,  327,  328,  329,  330,  331,  338,  339,  332,

      341,  333,  342,  334,  343,  335,  336,  344,  337,  345,
      347,  348,  349,  350,  356,  357,  358,  359,  360,  361,
      362,  363,  338,  339,  364,  341,  365,  342,  366,  343,
      367,  368,  344,  369,  345,  347,  348,  349,  350,  356,
      357,  358,  359,  360,  361,  362,  363,  370,  371,  364,
      372,  365,  373,  366,  374,  367,  368,  375,  369,  376,
      377,  378,  379,  380,  381,  382,  383,  385,  386,  387,
      388,  389,  370,  371,  390,  372,  391,  373,  392,  374,
      398,  399,  375,  400,  376,  377,  378,  379,  380,  381,
      382,  383,  385,  386,  387,  388,  389,  401,  402,  390,

      403,  391,  404,  392,  405,  398,  399,  406,  400,  407,
      408,  409,  410,  411,  412,  413,  414,  415,  416,  417,
      418,  419,  401,  402,  420,  403,  421,  404,  422,  405,
      423,  424,  406,  427,  407,  408,  409,  410,  411,  412,
      413,  414,  415,  416,  417,  418,  419,  428,  429,  420,
      430,  421,  436,  422,  437,  423,  424,  439,  427,  440,
      441,  442,  445,  446,  447,  448,  449,  450,  451,  452,
      453,  454,  428,  429,  455,  430,  456,  436,  457,  437,
      458,  459,  439,  460,  440,  441,  442,  445,  446,  447,
      448,  449,  450,  451,  452,  453,  454,  461,  463,  455,

      466,  456,  467,  457,  468,  458,  459,  469,  460,  470,
      471,  472,  473,  474,  476,  477,  478,  479,  480,  481,
      482,  483,  461,  463,  484,  466,  485,  467,  486,  468,
      487,  488,  469,  489,  470,  471,  472,  473,  474,  476,
      477,  478,  479,  480,  481,  482,  483,  490,  491,  484,
      492,  485,  495,  486,  496,  487,  488,  497,  489,  498,
      499,  500,  501,  502,  503,  504,  505,  506,  507,  508,
      509,  510,  490,  491,  511,  492,  512,  495,  513,  496,
      514,  515,  497,  516,  498,  499,  500,  501,  502,  503,
      504,  505,  506,  507,  508,  509,  510,  517,  518,  511,

      521,  512,  522,  513,  523,  514,  515,  524,  516,  525,
      526,  527,  528,  529,  530,  531,  532,  533,  534,  535,
      536,  537,  517,  518,  538,  521,  539,  522,  540,  523,
      541,  542,  524,  543,  525,  526,  527,  528,  529,  530,
      531,  532,  533,  534,  535,  536,  537,  544,  545,  538,
      546,  539,  547,  540,  548,  541,  542,  549,  543,  550,
      551,  552,  553,  554,  555,  556,  557,  558,  559,  560,
      561,  562,  544,  545,  563,  546,  564,  547,  565,  548,
      566,  567,  549,  568,  550,  551,  552,  553,  554,  555,
      556,  557,  558,  559,  560,  561,  562,  569,  570,  563,

      571,  564,  572,  565,  573,  566,  567,  574,  568,  355,
      354,  353,  346,  340,  312,  301,  285,  283,  275,  274,
      254,  247,  569,  570,  245,  571,  226,  572,  217,  573,
      165,  159,  574,   31,   31,   31,   31,   31,   31,   34,
      103,   34,   59,  100,   59,   59,   59,   59,   60,   60,
       92,   60,   60,   60,   62,   62,   91,   90,   70,  575,
       32,   32,   30,    5,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575
    } ;

static yyconst flex_int16_t yy_chk[1230] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    7,    7,    8,    8,   10,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   12,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
      494,   24,   25,   14,   10,   23,   26,   23,   27,   33,

       33,   37,   14,   41,   12,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   24,   25,   14,   22,
       23,   26,   23,   27,   40,   40,   37,   14,   41,   22,
       22,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       22,  493,   36,   38,   22,   42,   44,   45,   46,   40,
       40,   48,   36,   49,   22,   22,   36,   38,   50,   51,
       52,   53,   54,   55,   56,   57,   36,   36,   38,   58,
       42,   44,   45,   46,  243,  243,   48,   36,   49,   66,
       67,   36,   38,   50,   51,   52,   53,   54,   55,   56,
       57,   68,   66,   69,   58,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   66,   67,   70,   71,   73,   74,
       76,   77,   78,   79,   80,   81,   68,   66,   69,   82,
       83,   84,   85,   86,   87,  303,  431,  465,  303,  464,
      431,   70,   71,   73,   74,   76,   77,   78,   79,   80,
       81,   93,  442,  429,   82,   83,   84,   85,   86,   87,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   90,
       90,   90,   94,   95,   96,   90,   93,   90,   90,   90,
       97,   98,   90,   99,   90,   90,   90,   90,   90,  405,
      100,  101,  404,  399,   90,   90,   90,   94,   95,   96,
       90,  396,   90,   90,   90,   97,   98,   90,   99,   90,

       90,   90,   90,   90,   91,  100,  101,   91,   91,  102,
       91,  103,  104,  105,  106,  107,   91,  109,  110,  111,
       91,   91,  395,  394,  113,  114,  117,  393,  118,   91,
      120,  121,   91,   91,  102,   91,  103,  104,  105,  106,
      107,   91,  109,  110,  111,   91,   91,   92,   92,  113,
      114,  117,   92,  118,  122,  120,  121,   92,  123,   92,
       92,  392,   92,  116,  116,  116,  116,  116,  116,  116,
      116,  116,   92,   92,  124,  119,  125,   92,  126,  122,
      125,  127,   92,  123,   92,   92,  119,   92,  128,  129,
      125,  125,  130,  132,  131,  119,  133,  131,  134,  124,

      119,  125,  136,  126,  137,  125,  127,  131,  387,  139,
      140,  119,  138,  128,  129,  125,  125,  130,  132,  131,
      119,  133,  131,  134,  135,  141,  138,  136,  142,  137,
      143,  142,  131,  135,  139,  140,  144,  138,  145,  147,
      148,  149,  150,  151,  152,  154,  156,  157,  158,  135,
      141,  138,  159,  142,  161,  143,  142,  163,  135,  164,
      165,  144,  386,  145,  147,  148,  149,  150,  151,  152,
      154,  156,  157,  158,  167,  170,  170,  159,  171,  161,
      173,  168,  163,  174,  164,  165,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  168,  175,  176,  177,  167,

      170,  170,  178,  171,  179,  173,  168,  180,  174,  181,
      182,  183,  184,  185,  186,  188,  190,  192,  193,  194,
      168,  175,  176,  177,  195,  196,  197,  178,  199,  179,
      200,  201,  180,  202,  181,  182,  183,  184,  185,  186,
      188,  190,  192,  193,  194,  203,  204,  205,  206,  195,
      196,  197,  208,  199,  209,  200,  201,  210,  202,  211,
      212,  213,  214,  215,  216,  217,  218,  221,  355,  354,
      203,  204,  205,  206,  353,  352,  351,  208,  223,  209,
      224,  225,  210,  226,  211,  212,  213,  214,  215,  216,
      217,  218,  221,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  227,  223,  229,  224,  225,  231,  226,  232,
      233,  234,  235,  236,  237,  238,  239,  240,  241,  245,
      246,  248,  250,  250,  251,  250,  252,  227,  341,  229,
      253,  254,  231,  255,  232,  233,  234,  235,  236,  237,
      238,  239,  240,  241,  245,  246,  248,  257,  258,  251,
      259,  252,  260,  250,  263,  253,  254,  265,  255,  266,
      267,  268,  270,  271,  272,  274,  275,  276,  278,  279,
      280,  281,  257,  258,  282,  259,  283,  260,  284,  263,
      285,  286,  265,  287,  266,  267,  268,  270,  271,  272,
      274,  275,  276,  278,  279,  280,  281,  288,  289,  282,

      291,  283,  292,  284,  293,  285,  286,  294,  287,  295,
      299,  300,  301,  302,  307,  309,  310,  311,  312,  313,
      314,  315,  288,  289,  317,  291,  319,  292,  321,  293,
      322,  323,  294,  324,  295,  299,  300,  301,  302,  307,
      309,  310,  311,  312,  313,  314,  315,  325,  326,  317,
      327,  319,  329,  321,  330,  322,  323,  331,  324,  332,
      333,  334,  335,  337,  338,  339,  340,  342,  344,  345,
      346,  347,  325,  326,  348,  327,  349,  329,  350,  330,
      356,  357,  331,  358,  332,  333,  334,  335,  337,  338,
      339,  340,  342,  344,  345,  346,  347,  359,  360,  348,

      361,  349,  362,  350,  363,  356,  357,  365,  358,  366,
      368,  369,  370,  371,  372,  373,  375,  376,  377,  378,
      379,  380,  359,  360,  381,  361,  382,  362,  383,  363,
      384,  385,  365,  388,  366,  368,  369,  370,  371,  372,
      373,  375,  376,  377,  378,  379,  380,  389,  390,  381,
      391,  382,  397,  383,  398,  384,  385,  400,  388,  401,
      402,  403,  406,  408,  410,  411,  412,  414,  416,  417,
      418,  419,  389,  390,  421,  391,  422,  397,  423,  398,
      425,  426,  400,  427,  401,  402,  403,  406,  408,  410,
      411,  412,  414,  416,  417,  418,  419,  428,  430,  421,

      432,  422,  433,  423,  434,  425,  426,  435,  427,  436,
      437,  438,  439,  440,  443,  444,  446,  447,  448,  449,
      450,  452,  428,  430,  454,  432,  455,  433,  456,  434,
      457,  458,  435,  459,  436,  437,  438,  439,  440,  443,
      444,  446,  447,  448,  449,  450,  452,  460,  461,  454,
      462,  455,  466,  456,  467,  457,  458,  468,  459,  469,
      470,  471,  472,  473,  474,  475,  476,  477,  479,  480,
      481,  483,  460,  461,  484,  462,  486,  466,  487,  467,
      488,  489,  468,  490,  469,  470,  471,  472,  473,  474,
      475,  476,  477,  479,  480,  481,  483,  491,  492,  484,

      495,  486,  496,  487,  497,  488,  489,  498,  490,  499,
      500,  501,  502,  504,  505,  506,  507,  508,  510,  512,
      514,  515,  491,  492,  516,  495,  518,  496,  519,  497,
      520,  521,  498,  522,  499,  500,  501,  502,  504,  505,
      506,  507,  508,  510,  512,  514,  515,  523,  524,  516,
      526,  518,  527,  519,  529,  520,  521,  532,  522,  535,
      536,  537,  538,  539,  540,  541,  547,  551,  552,  553,
      554,  555,  523,  524,  556,  526,  557,  527,  558,  529,
      559,  561,  532,  562,  535,  536,  537,  538,  539,  540,
      541,  547,  551,  552,  553,  554,  555,  563,  564,  556,

      565,  557,  570,  558,  572,  559,  561,  573,  562,  306,
      305,  304,  296,  290,  256,  247,  230,  228,  220,  219,
      198,  191,  563,  564,  189,  565,  169,  570,  160,  572,
      115,  108,  573,  576,  576,  576,  576,  576,  576,  577,
       75,  577,  578,   72,  578,  578,  578,  578,  579,  579,
       65,  579,  579,  579,  580,  580,   64,   63,   39,    5,
        4,    3,    2,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,

      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575,  575,
      575,  575,  575,  575,  575,  575,  575,  575,  575
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[65] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cl_flex_debug;
int cl_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cltext;
#line 1 "cmdline_lexer.l"
/* cmdline lexical analyser */
/*
 * Copyright (c) 2018 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* %option debug */
#line 27 "cmdline_lexer.l"
#include "config.h"
#include <stdarg.h>
#include "cmdline_parser.h"


#line 989 "cmdline_lexer.c"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cllex_destroy (void );

int clget_debug (void );

void clset_debug (int debug_flag  );

YY_EXTRA_TYPE clget_extra (void );

void clset_extra (YY_EXTRA_TYPE user_defined  );

FILE *clget_in (void );

void clset_in  (FILE * in_str  );

FILE *clget_out (void );

void clset_out  (FILE * out_str  );

yy_size_t clget_leng (void );

char *clget_text (void );

int clget_lineno (void );

void clset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int clwrap (void );
#else
extern int clwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    static void yyunput (int c,char *buf_ptr  );
#endif
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cltext, clleng, 1, clout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( clin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( clin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, clin))==0 && ferror(clin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(clin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cllex (void);

#define YY_DECL int cllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cltext and clleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( clleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(cltext[clleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
#line 34 "cmdline_lexer.l"


#line 1180 "cmdline_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! clin )
			clin = stdin;

		if ( ! clout )
			clout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			clensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cl_create_buffer(clin,YY_BUF_SIZE );
		}

		cl_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 576 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 575 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < clleng; ++yyl )
				if ( cltext[yyl] == '\n' )
					   
    cllineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "cmdline_lexer.l"
{ /* skipping comment */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "cmdline_lexer.l"
{ cllval.val_str.len=0; BEGIN(STR); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 39 "cmdline_lexer.l"
{ cllval.val_str.val = strdup(cltext); cllval.val_str.len = strlen(cltext); }
	YY_BREAK
case YY_STATE_EOF(STR):
#line 40 "cmdline_lexer.l"
{ clerror(NULL, "Unterminated quoted string"); yyterminate(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "cmdline_lexer.l"
{   /* special case: if we have an empty string, regular rule is never executed */
		/* in which case, we perform the empty string assignment from here */
    if (cllval.val_str.len==0) { cllval.val_str.val=strdup(""); } BEGIN(INITIAL); return STRING;
	    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "cmdline_lexer.l"
{ cllval.ckattr = CKA_ID; return CKATTR_STR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "cmdline_lexer.l"
{ cllval.ckattr = CKA_LABEL; return CKATTR_STR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "cmdline_lexer.l"
{ cllval.ckattr = CKA_CLASS; return CKATTR_CLASS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "cmdline_lexer.l"
{ cllval.ckattr = CKA_TOKEN; return CKATTR_BOOL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "cmdline_lexer.l"
{ cllval.ckattr = CKA_KEY_TYPE; return CKATTR_KEY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SUBJECT; return CKATTR_STR; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "cmdline_lexer.l"
{ cllval.ckattr = CKA_ENCRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "cmdline_lexer.l"
{ cllval.ckattr = CKA_DECRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "cmdline_lexer.l"
{ cllval.ckattr = CKA_WRAP; return CKATTR_BOOL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "cmdline_lexer.l"
{ cllval.ckattr = CKA_UNWRAP; return CKATTR_BOOL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SIGN; return CKATTR_BOOL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SIGN_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "cmdline_lexer.l"
{ cllval.ckattr = CKA_VERIFY; return CKATTR_BOOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "cmdline_lexer.l"
{ cllval.ckattr = CKA_VERIFY_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "cmdline_lexer.l"
{ cllval.ckattr = CKA_DERIVE; return CKATTR_BOOL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "cmdline_lexer.l"
{ cllval.ckattr = CKA_PRIVATE; return CKATTR_BOOL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SENSITIVE; return CKATTR_BOOL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "cmdline_lexer.l"
{ cllval.ckattr = CKA_EXTRACTABLE; return CKATTR_BOOL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "cmdline_lexer.l"
{ cllval.ckattr = CKA_MODIFIABLE; return CKATTR_BOOL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "cmdline_lexer.l"
{ cllval.ckattr = CKA_START_DATE; return CKATTR_DATE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "cmdline_lexer.l"
{ cllval.ckattr = CKA_END_DATE; return CKATTR_DATE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "cmdline_lexer.l"
{ cllval.ckattr = CKA_EC_PARAMS; return CKATTR_STR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "cmdline_lexer.l"
{ cllval.ckattr = CKA_WRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "cmdline_lexer.l"
{ cllval.ckattr = CKA_UNWRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 71 "cmdline_lexer.l"
{ cllval.val_key = CKK_GENERIC_SECRET; return KEYTYPE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "cmdline_lexer.l"
{ cllval.val_key = CKK_DES           ; return KEYTYPE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "cmdline_lexer.l"
{ cllval.val_key = CKK_DES2          ; return KEYTYPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "cmdline_lexer.l"
{ cllval.val_key = CKK_DES3          ; return KEYTYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "cmdline_lexer.l"
{ cllval.val_key = CKK_AES           ; return KEYTYPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "cmdline_lexer.l"
{ cllval.val_key = CKK_MD5_HMAC      ; return KEYTYPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA_1_HMAC    ; return KEYTYPE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "cmdline_lexer.l"
{ cllval.val_key = CKK_RIPEMD128_HMAC; return KEYTYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "cmdline_lexer.l"
{ cllval.val_key = CKK_RIPEMD160_HMAC; return KEYTYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA256_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA384_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA512_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA224_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "cmdline_lexer.l"
{ cllval.val_key = CKK_RSA           ; return KEYTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "cmdline_lexer.l"
{ cllval.val_key = CKK_DH            ; return KEYTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "cmdline_lexer.l"
{ cllval.val_key = CKK_DSA           ; return KEYTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "cmdline_lexer.l"
{ cllval.val_key = CKK_EC            ; return KEYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "cmdline_lexer.l"
{ cllval.val_key = CKK_EC_EDWARDS    ; return KEYTYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "cmdline_lexer.l"
{ cllval.val_cls = CKO_DATA ; return OCLASS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "cmdline_lexer.l"
{ cllval.val_cls = CKO_CERTIFICATE ; return OCLASS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "cmdline_lexer.l"
{ cllval.val_cls = CKO_PUBLIC_KEY ; return OCLASS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "cmdline_lexer.l"
{ cllval.val_cls = CKO_PRIVATE_KEY ; return OCLASS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "cmdline_lexer.l"
{ cllval.val_cls = CKO_SECRET_KEY ; return OCLASS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "cmdline_lexer.l"
{ cllval.val_cls = CKO_HW_FEATURE ; return OCLASS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "cmdline_lexer.l"
{ cllval.val_cls = CKO_DOMAIN_PARAMETERS ; return OCLASS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "cmdline_lexer.l"
{ cllval.val_cls = CKO_MECHANISM ; return OCLASS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "cmdline_lexer.l"
{ cllval.val_cls = CKO_OTP_KEY ; return OCLASS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 100 "cmdline_lexer.l"
{ cllval.val_bool = 1; return TOK_BOOLEAN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 101 "cmdline_lexer.l"
{ cllval.val_bool = 0; return TOK_BOOLEAN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 104 "cmdline_lexer.l"
{   if(strlen(cltext)%2==1) {
			clerror(NULL, "Invalid hexadecimal string <%s>: odd length", cltext);
			yyterminate();
		    } else {
			cllval.val_str.len = (strlen(cltext)>>1) - 1; /* we skip the '0x' prefix */
			/* convert to hex */
			size_t i;
			char *target = malloc(cllval.val_str.len);
			if(target==NULL) {
			    cllval.val_str.len = 0 ;
			    clerror(NULL,"Memory allocation error during lexical analysis of <%s>", cltext);
			    yyterminate();
			}

			/* we start at cltext[2] */
			for(i=0;i<cllval.val_str.len; i++) {
			    /* the following trick is needed to have CLANG shut up */
			    /* strictly speaking, %x expects indeed a pointer to an integer */

			    volatile int tmp;
			    sscanf( &cltext[ (i<<1) + 2 ], "%2x", &tmp);
			    target[i] = (unsigned char) tmp;
			}
			cllval.val_str.val = target; /* then reassign */
			return STRING;
		    }
		}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 132 "cmdline_lexer.l"
{ memcpy(cllval.val_date.as_buffer, cltext, 8); return TOK_DATE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "cmdline_lexer.l"
{		/*check with context if we are not nesting templates */
                   if(ctx->level==1) {
		       clerror(NULL, "nesting templates not allowed", cltext);
		       yyterminate();
                   }
                   ctx->level++; /*remind we are in a curly brace */
                   ctx->current_idx++; /*increment current idx*/
                   if(ctx->current_idx>=3) {
		       clerror(NULL, "too many templates specified", cltext);
		       yyterminate();
                   }
                   return CURLY_OPEN;
               }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 148 "cmdline_lexer.l"
{
                   if(ctx->level==0) {
		       clerror(NULL, "no matching opening curly brace", cltext);
		       yyterminate();
                   }
                   ctx->level--;
                   ctx->saved_idx = ctx->current_idx;
                   ctx->current_idx = ctx->mainlist_idx; /* should be always 0 */
                   
                   return CURLY_CLOSE;
               }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 160 "cmdline_lexer.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 162 "cmdline_lexer.l"
{ return cltext[0]; } /* catch-all http://stackoverflow.com/questions/18837828/how-should-i-handle-lexical-errors-in-my-flex-lexer */
	YY_BREAK
/* gives it back to bison, so error comes from parser */
case 64:
YY_RULE_SETUP
#line 165 "cmdline_lexer.l"
ECHO;
	YY_BREAK
#line 1648 "cmdline_lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed clin at a new source and called
			 * cllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = clin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( clwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					clrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			clrestart(clin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) clrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 576 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 576 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 575);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --cllineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif	/* ifndef YY_NO_UNPUT */

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					clrestart(clin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( clwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    cllineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void clrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        clensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cl_create_buffer(clin,YY_BUF_SIZE );
	}

	cl_init_buffer(YY_CURRENT_BUFFER,input_file );
	cl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		clpop_buffer_state();
	 *		clpush_buffer_state(new_buffer);
     */
	clensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (clwrap()) processing, but the only time this flag
	 * is looked at is after clwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cl_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	clin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cl_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) clalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cl_create_buffer()
 * 
 */
    void cl_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		clfree((void *) b->yy_ch_buf  );

	clfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a clrestart() or at EOF.
 */
    static void cl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cl_init_buffer was _probably_
     * called from clrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cl_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cl_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void clpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	clensure_buffer_stack();

	/* This block is copied from cl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cl_switch_to_buffer. */
	cl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void clpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void clensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)clalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)clrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cl_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cl_scan_bytes() instead.
 */
YY_BUFFER_STATE cl_scan_string (yyconst char * yystr )
{
    
	return cl_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cl_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) clalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cltext[clleng] = (yy_hold_char); \
		(yy_c_buf_p) = cltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		clleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int clget_lineno  (void)
{
        
    return cllineno;
}

/** Get the input stream.
 * 
 */
FILE *clget_in  (void)
{
        return clin;
}

/** Get the output stream.
 * 
 */
FILE *clget_out  (void)
{
        return clout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t clget_leng  (void)
{
        return clleng;
}

/** Get the current token.
 * 
 */

char *clget_text  (void)
{
        return cltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void clset_lineno (int  line_number )
{
    
    cllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cl_switch_to_buffer
 */
void clset_in (FILE *  in_str )
{
        clin = in_str ;
}

void clset_out (FILE *  out_str )
{
        clout = out_str ;
}

int clget_debug  (void)
{
        return cl_flex_debug;
}

void clset_debug (int  bdebug )
{
        cl_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cllex_destroy(), so don't allocate here.
     */

    /* We do not touch cllineno unless the option is enabled. */
    cllineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    clin = stdin;
    clout = stdout;
#else
    clin = (FILE *) 0;
    clout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cllex_init()
     */
    return 0;
}

/* cllex_destroy is for both reentrant and non-reentrant scanners. */
int cllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		clpop_buffer_state();
	}

	/* Destroy the stack itself. */
	clfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *clalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *clrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void clfree (void * ptr )
{
	free( (char *) ptr );	/* see clrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 165 "cmdline_lexer.l"




void clerror(CmdLineCtx *ctx, const char *s, ...)
{
    va_list ap;
    va_start(ap, s);

    fprintf(stderr, "Error during parsing at line %d: ", cllineno);
    vfprintf(stderr, s, ap);
    fprintf(stderr, "\n");

    va_end(ap);
}

