#line 2 "cmdline_lexer.c"

#line 4 "cmdline_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cl_create_buffer
#define yy_delete_buffer cl_delete_buffer
#define yy_flex_debug cl_flex_debug
#define yy_init_buffer cl_init_buffer
#define yy_flush_buffer cl_flush_buffer
#define yy_load_buffer_state cl_load_buffer_state
#define yy_switch_to_buffer cl_switch_to_buffer
#define yyin clin
#define yyleng clleng
#define yylex cllex
#define yylineno cllineno
#define yyout clout
#define yyrestart clrestart
#define yytext cltext
#define yywrap clwrap
#define yyalloc clalloc
#define yyrealloc clrealloc
#define yyfree clfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

#if defined(__FreeBSD__)
#ifndef __STDC_LIMIT_MACROS
#define	__STDC_LIMIT_MACROS
#endif
#include <sys/cdefs.h>
#include <stdint.h>
#else
#define	__dead2
#endif

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__FreeBSD__) || \
    (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L)

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE clrestart(clin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t clleng;

extern FILE *clin, *clout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cllex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-cllineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < clleng; ++yyl )\
                    if ( cltext[yyl] == '\n' )\
                        --cllineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via clrestart()), so that the user can continue scanning by
	 * just pointing clin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
#define yy_current_buffer YY_CURRENT_BUFFER

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cltext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t clleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow clwrap()'s to do buffer switches
 * instead of setting up a fresh clin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void clrestart (FILE *input_file  );
void cl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cl_create_buffer (FILE *file,int size  );
void cl_delete_buffer (YY_BUFFER_STATE b  );
void cl_flush_buffer (YY_BUFFER_STATE b  );
void clpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void clpop_buffer_state (void );

static void clensure_buffer_stack (void );
static void cl_load_buffer_state (void );
static void cl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cl_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *clalloc (yy_size_t  );
void *clrealloc (void *,yy_size_t  );
void clfree (void *  );

#define yy_new_buffer cl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define clwrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *clin = (FILE *) 0, *clout = (FILE *) 0;

typedef int yy_state_type;

extern int cllineno;

int cllineno = 1;

extern char *cltext;
#define yytext_ptr cltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  ) __dead2;

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	clleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[578] =
    {   0,
        0,    0,    0,    0,   66,   64,   63,   63,    5,    2,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   61,   62,
        1,    3,    4,   63,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    6,    0,    0,    0,    5,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
        3,    0,   59,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   16,
        0,    0,    0,   57,    0,    0,   14,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    0,    0,
        0,    0,    0,    0,   58,    0,    7,    0,    0,    0,
        0,    0,    0,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    6,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   44,    0,
       46,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   20,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       15,   18,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   34,   31,   45,    0,    0,    0,    0,
       43,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   57,   13,    0,   12,    0,    0,    0,    0,
       21,    0,    0,    0,   11,    0,    0,    0,   60,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   16,    0,    0,    0,    0,    0,   14,   32,   33,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   48,
        0,    0,    0,    0,    0,    0,    0,   58,    0,   26,
        0,   10,    0,    0,    0,    0,    0,    0,    0,    8,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   27,    0,    0,   22,    0,
        0,    0,    0,    0,    0,   20,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   15,   18,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   24,    0,
       25,    0,    0,    0,   13,    0,   12,    0,    0,    0,
        0,   21,    0,    0,    0,   11,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   56,    0,    0,    0,   23,    0,    0,    0,
        0,    0,   26,    0,   10,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   35,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   17,
        0,    0,    0,   27,    0,    0,   22,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   55,    0,    0,    0,    0,    0,
       28,    0,   24,    0,   25,    0,    0,    0,   47,    0,
        0,    0,    0,    0,    0,    0,   36,    0,    0,   53,
        0,   50,   52,    0,   19,   23,    0,    0,    0,    0,
        0,    0,    0,   42,   39,   40,   41,   49,    0,   51,
       29,   17,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   28,    0,    0,    0,    0,    0,   19,   30,   37,
       38,    0,   29,    0,    0,   54,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   14,    1,    1,    1,
        1,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
        1,   32,   33,   34,   35,   36,   37,   38,   39,    1,
        1,    1,    1,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,    1,   57,   58,   59,   60,   61,   62,   63,
       64,    1,   65,    1,   66,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    1,    1,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[583] =
    {   0,
        0, 1160, 1160, 1159, 1163, 1167,   65,   67, 1167, 1167,
       33,   65,   55,   63,   66,   69,   67,   67,   72,   59,
       60,   59,   97,   67,   64,   74,   66,   80, 1167, 1167,
        0,    0, 1167,   99,  126,    0,  128,   87,  127, 1117,
      108,   71,  120, 1167,  109,  132,  131,  119,  131,  131,
      139,  146,  146,  138,  130,  129,  135,  155,  143,    0,
        0,  195,    0, 1110, 1107, 1098,  177,  160,  162,  171,
      166,  167, 1097,  168,  179, 1095,  193,  190, 1167,  179,
      183,  188,  189,  201,  207,  208,  197,  206,  200, 1167,
      250,  248,  295,  336,  228,  213,  215,  232,  241,  262,

      241,  268,  272,  274,  261,  289,  297,  305,  298, 1093,
      290,  305,  297, 1167,  315,  311, 1091,  363,  306,  315,
      364,  318,  318,  345,  335,  349,  363,  355,  359,  375,
      364,  379,  381,  382,  383,  386,  407,  386,  391,  403,
      379,  397,  398,  403,  417,  416,  410, 1167,  415,  427,
      416,  418,  434,  433, 1167,  413, 1167,  429,  420,  421,
      427, 1088,  443, 1167,  433,  427,  433,  486,  465,  470,
     1087,  464,  451, 1167,  448,  473,  484,  480,  476,  487,
      495,  497,  490,  480,  486,  503,  487,  488, 1167,  506,
     1086,  494, 1113,  493,  509,  510,  499,  498,  505, 1084,

      517,  506,  514,  523,  534,  520,  534,  521, 1167,  543,
      527,  530,  532,  536,  552,  549,  546,  551,  553,  539,
     1083, 1082,  554,  593,  552,  555,  564,  559,  577, 1081,
      579, 1080,  594,  592,  581,  585,  590,  588,  596,  602,
      591,  600,  594, 1167,  172, 1167,  606,  607, 1079,  608,
     1167,  620,  597,  617,  621,  617,  617, 1078,  618,  628,
      625,  639, 1167, 1167,  633, 1167,  644,  650,  647,  651,
     1167,  633,  652,  655, 1167,  638,  641,  646, 1167,  642,
      637,  641,  662,  642,  664,  669,  653,  661,  669,  688,
      681, 1077,  673,  689,  682,  698,  695, 1076, 1167, 1167,

      698,  686,  696,  692,  223,  620,  575,  574,  697, 1167,
      698,  703,  708,  699,  710,  703,  708, 1167,  698, 1167,
      716, 1167,  708,  717,  708,  706,  734,  735,  726, 1167,
      728,  741,  732,  735,  751,  750,  730, 1167,  746,  737,
      738,  741,  541,  756, 1167,  744,  737,  743,  741,  757,
      755,  766,  565,  562,  458,  406,  328,  766,  759,  774,
      775,  785,  773,  791,  777, 1167,  787,  796, 1167,  781,
      798,  791,  802,  794,  788, 1167,  807,  790,  791,  792,
      796,  812,  811,  809,  815,  818,  804,  305,  304,  820,
      838,  837,  841,  326,  290,  289,  258,  250,  836,  837,

      249,  830,  842,  828,  848,  246,  210,  849, 1167,  850,
     1167,  840,  842,  857, 1167,  846, 1167,  855,  860,  857,
      861, 1167,  845,  865,  869, 1167,  853,  856,  862,  872,
      209,  887,  234,  884,  886,  888,  891,  888,  899,  887,
      884,  887, 1167,  194,  895,  896, 1167,  891,  897,  889,
      892,  894, 1167,  911, 1167,  904,  913,  905,  903,  918,
      920,  923,  936,  924, 1167,  218,  170,  931,  933,  936,
      938,  951,  952,  953,  938,  943,  946,  953,  954, 1167,
      959,  956,  957, 1167,  951,  961, 1167,  947,  965,  959,
      970,  963,  971,  985,  103,   52,  991,  993,  995,  998,

      998,  983,  986,  999, 1167, 1000,  982,  983,  989,  992,
     1167, 1005, 1167, 1006, 1167,  996,  998, 1015, 1167, 1015,
     1012, 1014, 1020, 1022, 1036, 1037, 1167, 1037, 1043, 1167,
     1022, 1167, 1167, 1044, 1167, 1167, 1034, 1040, 1032, 1035,
     1038, 1043, 1044, 1167, 1167, 1167, 1167, 1167, 1045, 1167,
     1167, 1167, 1058, 1055, 1056, 1057, 1062, 1065, 1063, 1051,
     1055, 1167, 1054, 1072, 1086, 1071, 1087, 1167, 1167, 1167,
     1167, 1089, 1167, 1079, 1081, 1167, 1167, 1139, 1142, 1148,
     1154, 1157
    } ;

static yyconst flex_int16_t yy_def[583] =
    {   0,
      577,    1,  578,  578,  577,  577,  577,  577,  577,  577,
      579,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      580,  581,  577,  577,  577,  582,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  580,
      581,  577,  582,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,

      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,

      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,

      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,

      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,

      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,    0,  577,  577,  577,
      577,  577
    } ;

static yyconst flex_int16_t yy_nxt[1234] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   12,   12,
       12,   12,   12,   12,   12,    6,    6,   13,   14,   15,
       16,    6,    6,   17,    6,   18,   19,   20,   21,    6,
       22,    6,   23,   24,   25,   26,   27,    6,   28,    6,
        6,    6,   13,   14,   15,   16,    6,    6,   17,    6,
       18,   19,   20,   21,    6,   22,    6,   23,   24,   25,
       26,   27,    6,   28,   29,   30,   34,   34,   34,   34,
       36,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       37,   38,   39,   40,   43,   44,   45,   46,   47,   48,
       49,  522,   56,   57,   41,   36,   54,   58,   55,   59,

       34,   34,   68,   42,   74,   37,   38,   39,   40,   43,
       44,   45,   46,   47,   48,   49,   50,   56,   57,   41,
       51,   54,   58,   55,   59,   72,   73,   68,   42,   74,
       52,   53,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   50,  521,   64,   69,   51,   75,   76,   77,   78,
       72,   73,   79,   65,   80,   52,   53,   66,   70,   81,
       82,   83,   84,   85,   86,   87,   88,   67,   64,   69,
       89,   75,   76,   77,   78,   90,  496,   79,   65,   80,
      299,  300,   66,   70,   81,   82,   83,   84,   85,   86,
       87,   88,   97,   98,   99,   89,  100,   95,  101,  103,

       90,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       96,  104,  106,  107,  108,  109,  110,   97,   98,   99,
      111,  100,   95,  101,  103,  112,  113,  114,  115,  116,
      117,  353,  495,  477,  354,   96,  104,  106,  107,  108,
      109,  110,  466,  146,  147,  111,  467,  148,  464,  446,
      112,  113,  114,  115,  116,  117,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  119,  120,  121,  146,  147,
      149,  122,  148,  123,  124,  125,  150,  151,  126,  152,
      127,  128,  129,  130,  131,  445,  153,  154,  440,  437,
      119,  120,  121,  155,  156,  149,  122,  436,  123,  124,

      125,  150,  151,  126,  152,  127,  128,  129,  130,  131,
      132,  153,  154,  133,  134,  157,  135,  158,  155,  156,
      159,  160,  136,  162,  163,  164,  137,  138,  435,  434,
      165,  166,  169,  433,  170,  132,  174,  175,  133,  134,
      157,  135,  158,  428,  427,  159,  160,  136,  162,  163,
      164,  137,  138,  139,  140,  165,  166,  169,  141,  170,
      176,  174,  175,  142,  177,  143,  144,  399,  145,  168,
      168,  168,  168,  168,  168,  168,  168,  168,  139,  140,
      178,  171,  179,  141,  183,  176,  180,  184,  142,  177,
      143,  144,  172,  145,  185,  186,  181,  182,  187,  191,

      188,  173,  192,  189,  193,  178,  171,  179,  196,  183,
      197,  180,  184,  190,  398,  200,  201,  172,  198,  185,
      186,  181,  182,  187,  191,  188,  173,  192,  189,  193,
      194,  202,  199,  196,  203,  197,  205,  204,  190,  195,
      200,  201,  206,  198,  207,  208,  209,  210,  211,  212,
      213,  214,  215,  216,  217,  194,  202,  199,  218,  203,
      220,  205,  204,  221,  195,  222,  223,  206,  397,  207,
      208,  209,  210,  211,  212,  213,  214,  215,  216,  217,
      225,  229,  230,  218,  231,  220,  232,  226,  221,  233,
      222,  223,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  227,  234,  235,  236,  225,  229,  230,  237,  231,
      238,  232,  226,  239,  233,  240,  241,  242,  243,  244,
      245,  246,  248,  250,  251,  252,  227,  234,  235,  236,
      253,  254,  255,  237,  257,  238,  258,  259,  239,  260,
      240,  241,  242,  243,  244,  245,  246,  248,  250,  251,
      252,  261,  262,  263,  264,  253,  254,  255,  265,  257,
      266,  258,  259,  267,  260,  268,  269,  270,  271,  272,
      273,  274,  275,  278,  396,  395,  261,  262,  263,  264,
      386,  357,  356,  265,  280,  266,  281,  282,  267,  283,
      268,  269,  270,  271,  272,  273,  274,  275,  278,  279,

      279,  279,  279,  279,  279,  279,  279,  279,  284,  280,
      286,  281,  282,  288,  283,  289,  290,  291,  292,  293,
      294,  295,  296,  297,  298,  301,  302,  304,  305,  306,
      309,  307,  310,  284,  355,  286,  311,  312,  288,  313,
      289,  290,  291,  292,  293,  294,  295,  296,  297,  298,
      301,  302,  304,  315,  316,  309,  317,  310,  318,  308,
      319,  311,  312,  320,  313,  321,  322,  323,  324,  325,
      326,  327,  328,  329,  330,  331,  332,  333,  315,  316,
      334,  317,  335,  318,  336,  319,  337,  338,  320,  339,
      321,  322,  323,  324,  325,  326,  327,  328,  329,  330,

      331,  332,  333,  340,  341,  334,  343,  335,  344,  336,
      345,  337,  338,  346,  339,  347,  349,  350,  351,  352,
      358,  359,  360,  361,  362,  363,  364,  365,  340,  341,
      366,  343,  367,  344,  368,  345,  369,  370,  346,  371,
      347,  349,  350,  351,  352,  358,  359,  360,  361,  362,
      363,  364,  365,  372,  373,  366,  374,  367,  375,  368,
      376,  369,  370,  377,  371,  378,  379,  380,  381,  382,
      383,  384,  385,  387,  388,  389,  390,  391,  372,  373,
      392,  374,  393,  375,  394,  376,  400,  401,  377,  402,
      378,  379,  380,  381,  382,  383,  384,  385,  387,  388,

      389,  390,  391,  403,  404,  392,  405,  393,  406,  394,
      407,  400,  401,  408,  402,  409,  410,  411,  412,  413,
      414,  415,  416,  417,  418,  419,  420,  421,  403,  404,
      422,  405,  423,  406,  424,  407,  425,  426,  408,  429,
      409,  410,  411,  412,  413,  414,  415,  416,  417,  418,
      419,  420,  421,  430,  431,  422,  432,  423,  438,  424,
      439,  425,  426,  441,  429,  442,  443,  444,  447,  448,
      449,  450,  451,  452,  453,  454,  455,  456,  430,  431,
      457,  432,  458,  438,  459,  439,  460,  461,  441,  462,
      442,  443,  444,  447,  448,  449,  450,  451,  452,  453,

      454,  455,  456,  463,  465,  457,  468,  458,  469,  459,
      470,  460,  461,  471,  462,  472,  473,  474,  475,  476,
      478,  479,  480,  481,  482,  483,  484,  485,  463,  465,
      486,  468,  487,  469,  488,  470,  489,  490,  471,  491,
      472,  473,  474,  475,  476,  478,  479,  480,  481,  482,
      483,  484,  485,  492,  493,  486,  494,  487,  497,  488,
      498,  489,  490,  499,  491,  500,  501,  502,  503,  504,
      505,  506,  507,  508,  509,  510,  511,  512,  492,  493,
      513,  494,  514,  497,  515,  498,  516,  517,  499,  518,
      500,  501,  502,  503,  504,  505,  506,  507,  508,  509,

      510,  511,  512,  519,  520,  513,  523,  514,  524,  515,
      525,  516,  517,  526,  518,  527,  528,  529,  530,  531,
      532,  533,  534,  535,  536,  537,  538,  539,  519,  520,
      540,  523,  541,  524,  542,  525,  543,  544,  526,  545,
      527,  528,  529,  530,  531,  532,  533,  534,  535,  536,
      537,  538,  539,  546,  547,  540,  548,  541,  549,  542,
      550,  543,  544,  551,  545,  552,  553,  554,  555,  556,
      557,  558,  559,  560,  561,  562,  563,  564,  546,  547,
      565,  548,  566,  549,  567,  550,  568,  569,  551,  570,
      552,  553,  554,  555,  556,  557,  558,  559,  560,  561,

      562,  563,  564,  571,  572,  565,  573,  566,  574,  567,
      575,  568,  569,  576,  570,  348,  342,  314,  303,  287,
      285,  277,  276,  256,  249,  247,  228,  219,  571,  572,
      167,  573,  161,  574,  105,  575,  102,   94,  576,   32,
       32,   32,   32,   32,   32,   35,   93,   35,   60,   92,
       60,   60,   60,   60,   61,   61,   71,   61,   61,   61,
       63,   63,  577,   33,   33,   31,    5,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,

      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577
    } ;

static yyconst flex_int16_t yy_chk[1234] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    7,    8,    8,
       11,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       13,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,  496,   25,   26,   15,   11,   24,   27,   24,   28,

       34,   34,   38,   15,   42,   13,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   25,   26,   15,
       23,   24,   27,   24,   28,   41,   41,   38,   15,   42,
       23,   23,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   23,  495,   37,   39,   23,   43,   45,   46,   47,
       41,   41,   48,   37,   49,   23,   23,   37,   39,   50,
       51,   52,   53,   54,   55,   56,   57,   37,   37,   39,
       58,   43,   45,   46,   47,   59,  467,   48,   37,   49,
      245,  245,   37,   39,   50,   51,   52,   53,   54,   55,
       56,   57,   68,   69,   70,   58,   71,   67,   72,   74,

       59,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       67,   75,   77,   78,   80,   81,   82,   68,   69,   70,
       83,   71,   67,   72,   74,   84,   85,   86,   87,   88,
       89,  305,  466,  444,  305,   67,   75,   77,   78,   80,
       81,   82,  433,   95,   96,   83,  433,   97,  431,  407,
       84,   85,   86,   87,   88,   89,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   92,   92,   92,   95,   96,
       98,   92,   97,   92,   92,   92,   99,  100,   92,  101,
       92,   92,   92,   92,   92,  406,  102,  103,  401,  398,
       92,   92,   92,  104,  105,   98,   92,  397,   92,   92,

       92,   99,  100,   92,  101,   92,   92,   92,   92,   92,
       93,  102,  103,   93,   93,  106,   93,  107,  104,  105,
      108,  109,   93,  111,  112,  113,   93,   93,  396,  395,
      115,  116,  119,  394,  120,   93,  122,  123,   93,   93,
      106,   93,  107,  389,  388,  108,  109,   93,  111,  112,
      113,   93,   93,   94,   94,  115,  116,  119,   94,  120,
      124,  122,  123,   94,  125,   94,   94,  357,   94,  118,
      118,  118,  118,  118,  118,  118,  118,  118,   94,   94,
      126,  121,  127,   94,  128,  124,  127,  129,   94,  125,
       94,   94,  121,   94,  130,  131,  127,  127,  132,  134,

      133,  121,  135,  133,  136,  126,  121,  127,  138,  128,
      139,  127,  129,  133,  356,  141,  142,  121,  140,  130,
      131,  127,  127,  132,  134,  133,  121,  135,  133,  136,
      137,  143,  140,  138,  144,  139,  145,  144,  133,  137,
      141,  142,  146,  140,  147,  149,  150,  151,  152,  153,
      154,  156,  158,  159,  160,  137,  143,  140,  161,  144,
      163,  145,  144,  165,  137,  166,  167,  146,  355,  147,
      149,  150,  151,  152,  153,  154,  156,  158,  159,  160,
      169,  172,  172,  161,  173,  163,  175,  170,  165,  176,
      166,  167,  168,  168,  168,  168,  168,  168,  168,  168,

      168,  170,  177,  178,  179,  169,  172,  172,  180,  173,
      181,  175,  170,  182,  176,  183,  184,  185,  186,  187,
      188,  190,  192,  194,  195,  196,  170,  177,  178,  179,
      197,  198,  199,  180,  201,  181,  202,  203,  182,  204,
      183,  184,  185,  186,  187,  188,  190,  192,  194,  195,
      196,  205,  206,  207,  208,  197,  198,  199,  210,  201,
      211,  202,  203,  212,  204,  213,  214,  215,  216,  217,
      218,  219,  220,  223,  354,  353,  205,  206,  207,  208,
      343,  308,  307,  210,  225,  211,  226,  227,  212,  228,
      213,  214,  215,  216,  217,  218,  219,  220,  223,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  229,  225,
      231,  226,  227,  233,  228,  234,  235,  236,  237,  238,
      239,  240,  241,  242,  243,  247,  248,  250,  252,  252,
      253,  252,  254,  229,  306,  231,  255,  256,  233,  257,
      234,  235,  236,  237,  238,  239,  240,  241,  242,  243,
      247,  248,  250,  259,  260,  253,  261,  254,  262,  252,
      265,  255,  256,  267,  257,  268,  269,  270,  272,  273,
      274,  276,  277,  278,  280,  281,  282,  283,  259,  260,
      284,  261,  285,  262,  286,  265,  287,  288,  267,  289,
      268,  269,  270,  272,  273,  274,  276,  277,  278,  280,

      281,  282,  283,  290,  291,  284,  293,  285,  294,  286,
      295,  287,  288,  296,  289,  297,  301,  302,  303,  304,
      309,  311,  312,  313,  314,  315,  316,  317,  290,  291,
      319,  293,  321,  294,  323,  295,  324,  325,  296,  326,
      297,  301,  302,  303,  304,  309,  311,  312,  313,  314,
      315,  316,  317,  327,  328,  319,  329,  321,  331,  323,
      332,  324,  325,  333,  326,  334,  335,  336,  337,  339,
      340,  341,  342,  344,  346,  347,  348,  349,  327,  328,
      350,  329,  351,  331,  352,  332,  358,  359,  333,  360,
      334,  335,  336,  337,  339,  340,  341,  342,  344,  346,

      347,  348,  349,  361,  362,  350,  363,  351,  364,  352,
      365,  358,  359,  367,  360,  368,  370,  371,  372,  373,
      374,  375,  377,  378,  379,  380,  381,  382,  361,  362,
      383,  363,  384,  364,  385,  365,  386,  387,  367,  390,
      368,  370,  371,  372,  373,  374,  375,  377,  378,  379,
      380,  381,  382,  391,  392,  383,  393,  384,  399,  385,
      400,  386,  387,  402,  390,  403,  404,  405,  408,  410,
      412,  413,  414,  416,  418,  419,  420,  421,  391,  392,
      423,  393,  424,  399,  425,  400,  427,  428,  402,  429,
      403,  404,  405,  408,  410,  412,  413,  414,  416,  418,

      419,  420,  421,  430,  432,  423,  434,  424,  435,  425,
      436,  427,  428,  437,  429,  438,  439,  440,  441,  442,
      445,  446,  448,  449,  450,  451,  452,  454,  430,  432,
      456,  434,  457,  435,  458,  436,  459,  460,  437,  461,
      438,  439,  440,  441,  442,  445,  446,  448,  449,  450,
      451,  452,  454,  462,  463,  456,  464,  457,  468,  458,
      469,  459,  460,  470,  461,  471,  472,  473,  474,  475,
      476,  477,  478,  479,  481,  482,  483,  485,  462,  463,
      486,  464,  488,  468,  489,  469,  490,  491,  470,  492,
      471,  472,  473,  474,  475,  476,  477,  478,  479,  481,

      482,  483,  485,  493,  494,  486,  497,  488,  498,  489,
      499,  490,  491,  500,  492,  501,  502,  503,  504,  506,
      507,  508,  509,  510,  512,  514,  516,  517,  493,  494,
      518,  497,  520,  498,  521,  499,  522,  523,  500,  524,
      501,  502,  503,  504,  506,  507,  508,  509,  510,  512,
      514,  516,  517,  525,  526,  518,  528,  520,  529,  521,
      531,  522,  523,  534,  524,  537,  538,  539,  540,  541,
      542,  543,  549,  553,  554,  555,  556,  557,  525,  526,
      558,  528,  559,  529,  560,  531,  561,  563,  534,  564,
      537,  538,  539,  540,  541,  542,  543,  549,  553,  554,

      555,  556,  557,  565,  566,  558,  567,  559,  572,  560,
      574,  561,  563,  575,  564,  298,  292,  258,  249,  232,
      230,  222,  221,  200,  193,  191,  171,  162,  565,  566,
      117,  567,  110,  572,   76,  574,   73,   66,  575,  578,
      578,  578,  578,  578,  578,  579,   65,  579,  580,   64,
      580,  580,  580,  580,  581,  581,   40,  581,  581,  581,
      582,  582,    5,    4,    3,    2,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,

      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577,  577,  577,  577,  577,  577,  577,  577,
      577,  577,  577
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[66] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cl_flex_debug;
int cl_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cltext;
#line 1 "cmdline_lexer.l"
/* cmdline lexical analyser */
/*
 * Copyright (c) 2018 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* %option debug */
#line 27 "cmdline_lexer.l"
#include "config.h"
#include <stdarg.h>
#include "cmdline_parser.h"


#line 993 "cmdline_lexer.c"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cllex_destroy (void );

int clget_debug (void );

void clset_debug (int debug_flag  );

YY_EXTRA_TYPE clget_extra (void );

void clset_extra (YY_EXTRA_TYPE user_defined  );

FILE *clget_in (void );

void clset_in  (FILE * in_str  );

FILE *clget_out (void );

void clset_out  (FILE * out_str  );

yy_size_t clget_leng (void );

char *clget_text (void );

int clget_lineno (void );

void clset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int clwrap (void );
#else
extern int clwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    static void yyunput (int c,char *buf_ptr  );
#endif
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cltext, clleng, 1, clout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( clin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( clin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, clin))==0 && ferror(clin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(clin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cllex (void);

#define YY_DECL int cllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cltext and clleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( clleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(cltext[clleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
#line 34 "cmdline_lexer.l"


#line 1184 "cmdline_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! clin )
			clin = stdin;

		if ( ! clout )
			clout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			clensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cl_create_buffer(clin,YY_BUF_SIZE );
		}

		cl_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 578 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 577 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < clleng; ++yyl )
				if ( cltext[yyl] == '\n' )
					   
    cllineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "cmdline_lexer.l"
{ /* skipping comment */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "cmdline_lexer.l"
{ cllval.val_str.len=0; BEGIN(STR); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 39 "cmdline_lexer.l"
{ cllval.val_str.val = strdup(cltext); cllval.val_str.len = strlen(cltext); }
	YY_BREAK
case YY_STATE_EOF(STR):
#line 40 "cmdline_lexer.l"
{ clerror(NULL, "Unterminated quoted string"); yyterminate(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "cmdline_lexer.l"
{   /* special case: if we have an empty string, regular rule is never executed */
		/* in which case, we perform the empty string assignment from here */
    if (cllval.val_str.len==0) { cllval.val_str.val=strdup(""); } BEGIN(INITIAL); return STRING;
	    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "cmdline_lexer.l"
{ return NO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "cmdline_lexer.l"
{ cllval.ckattr = CKA_ID; return CKATTR_STR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 48 "cmdline_lexer.l"
{ cllval.ckattr = CKA_LABEL; return CKATTR_STR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "cmdline_lexer.l"
{ cllval.ckattr = CKA_CLASS; return CKATTR_CLASS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 50 "cmdline_lexer.l"
{ cllval.ckattr = CKA_TOKEN; return CKATTR_BOOL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 51 "cmdline_lexer.l"
{ cllval.ckattr = CKA_KEY_TYPE; return CKATTR_KEY; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SUBJECT; return CKATTR_STR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "cmdline_lexer.l"
{ cllval.ckattr = CKA_ENCRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "cmdline_lexer.l"
{ cllval.ckattr = CKA_DECRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "cmdline_lexer.l"
{ cllval.ckattr = CKA_WRAP; return CKATTR_BOOL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "cmdline_lexer.l"
{ cllval.ckattr = CKA_UNWRAP; return CKATTR_BOOL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SIGN; return CKATTR_BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SIGN_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "cmdline_lexer.l"
{ cllval.ckattr = CKA_VERIFY; return CKATTR_BOOL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "cmdline_lexer.l"
{ cllval.ckattr = CKA_VERIFY_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "cmdline_lexer.l"
{ cllval.ckattr = CKA_DERIVE; return CKATTR_BOOL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "cmdline_lexer.l"
{ cllval.ckattr = CKA_PRIVATE; return CKATTR_BOOL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "cmdline_lexer.l"
{ cllval.ckattr = CKA_SENSITIVE; return CKATTR_BOOL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "cmdline_lexer.l"
{ cllval.ckattr = CKA_EXTRACTABLE; return CKATTR_BOOL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "cmdline_lexer.l"
{ cllval.ckattr = CKA_MODIFIABLE; return CKATTR_BOOL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "cmdline_lexer.l"
{ cllval.ckattr = CKA_START_DATE; return CKATTR_DATE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "cmdline_lexer.l"
{ cllval.ckattr = CKA_END_DATE; return CKATTR_DATE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "cmdline_lexer.l"
{ cllval.ckattr = CKA_EC_PARAMS; return CKATTR_STR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "cmdline_lexer.l"
{ cllval.ckattr = CKA_WRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "cmdline_lexer.l"
{ cllval.ckattr = CKA_UNWRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "cmdline_lexer.l"
{ cllval.val_key = CKK_GENERIC_SECRET; return KEYTYPE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "cmdline_lexer.l"
{ cllval.val_key = CKK_DES           ; return KEYTYPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "cmdline_lexer.l"
{ cllval.val_key = CKK_DES2          ; return KEYTYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "cmdline_lexer.l"
{ cllval.val_key = CKK_DES3          ; return KEYTYPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "cmdline_lexer.l"
{ cllval.val_key = CKK_AES           ; return KEYTYPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "cmdline_lexer.l"
{ cllval.val_key = CKK_MD5_HMAC      ; return KEYTYPE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA_1_HMAC    ; return KEYTYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "cmdline_lexer.l"
{ cllval.val_key = CKK_RIPEMD128_HMAC; return KEYTYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "cmdline_lexer.l"
{ cllval.val_key = CKK_RIPEMD160_HMAC; return KEYTYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA256_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA384_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA512_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "cmdline_lexer.l"
{ cllval.val_key = CKK_SHA224_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "cmdline_lexer.l"
{ cllval.val_key = CKK_RSA           ; return KEYTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "cmdline_lexer.l"
{ cllval.val_key = CKK_DH            ; return KEYTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "cmdline_lexer.l"
{ cllval.val_key = CKK_DSA           ; return KEYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "cmdline_lexer.l"
{ cllval.val_key = CKK_EC            ; return KEYTYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "cmdline_lexer.l"
{ cllval.val_key = CKK_EC_EDWARDS    ; return KEYTYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "cmdline_lexer.l"
{ cllval.val_cls = CKO_DATA ; return OCLASS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "cmdline_lexer.l"
{ cllval.val_cls = CKO_CERTIFICATE ; return OCLASS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "cmdline_lexer.l"
{ cllval.val_cls = CKO_PUBLIC_KEY ; return OCLASS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "cmdline_lexer.l"
{ cllval.val_cls = CKO_PRIVATE_KEY ; return OCLASS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "cmdline_lexer.l"
{ cllval.val_cls = CKO_SECRET_KEY ; return OCLASS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "cmdline_lexer.l"
{ cllval.val_cls = CKO_HW_FEATURE ; return OCLASS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "cmdline_lexer.l"
{ cllval.val_cls = CKO_DOMAIN_PARAMETERS ; return OCLASS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "cmdline_lexer.l"
{ cllval.val_cls = CKO_MECHANISM ; return OCLASS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "cmdline_lexer.l"
{ cllval.val_cls = CKO_OTP_KEY ; return OCLASS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 101 "cmdline_lexer.l"
{ cllval.val_bool = 1; return TOK_BOOLEAN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 102 "cmdline_lexer.l"
{ cllval.val_bool = 0; return TOK_BOOLEAN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 105 "cmdline_lexer.l"
{   if(strlen(cltext)%2==1) {
			clerror(NULL, "Invalid hexadecimal string <%s>: odd length", cltext);
			yyterminate();
		    } else {
			cllval.val_str.len = (strlen(cltext)>>1) - 1; /* we skip the '0x' prefix */
			/* convert to hex */
			size_t i;
			char *target = malloc(cllval.val_str.len);
			if(target==NULL) {
			    cllval.val_str.len = 0 ;
			    clerror(NULL,"Memory allocation error during lexical analysis of <%s>", cltext);
			    yyterminate();
			}

			/* we start at cltext[2] */
			for(i=0;i<cllval.val_str.len; i++) {
			    /* the following trick is needed to have CLANG shut up */
			    /* strictly speaking, %x expects indeed a pointer to an integer */

			    volatile int tmp;
			    sscanf( &cltext[ (i<<1) + 2 ], "%2x", &tmp);
			    target[i] = (unsigned char) tmp;
			}
			cllval.val_str.val = target; /* then reassign */
			return STRING;
		    }
		}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 133 "cmdline_lexer.l"
{ memcpy(cllval.val_date.as_buffer, cltext, 8); return TOK_DATE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "cmdline_lexer.l"
{		/*check with context if we are not nesting templates */
                   if(ctx->level==1) {
		       clerror(NULL, "nesting templates not allowed", cltext);
		       yyterminate();
                   }
                   ctx->level++; /*remind we are in a curly brace */
                   ctx->current_idx++; /*increment current idx*/
                   if(ctx->current_idx>=3) {
		       clerror(NULL, "too many templates specified", cltext);
		       yyterminate();
                   }
                   return CURLY_OPEN;
               }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 149 "cmdline_lexer.l"
{
                   if(ctx->level==0) {
		       clerror(NULL, "no matching opening curly brace", cltext);
		       yyterminate();
                   }
                   ctx->level--;
                   ctx->saved_idx = ctx->current_idx;
                   ctx->current_idx = ctx->mainlist_idx; /* should be always 0 */
                   
                   return CURLY_CLOSE;
               }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 161 "cmdline_lexer.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 163 "cmdline_lexer.l"
{ return cltext[0]; } /* catch-all http://stackoverflow.com/questions/18837828/how-should-i-handle-lexical-errors-in-my-flex-lexer */
	YY_BREAK
/* gives it back to bison, so error comes from parser */
case 65:
YY_RULE_SETUP
#line 166 "cmdline_lexer.l"
ECHO;
	YY_BREAK
#line 1657 "cmdline_lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed clin at a new source and called
			 * cllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = clin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( clwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					clrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			clrestart(clin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) clrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 578 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 578 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 577);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --cllineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif	/* ifndef YY_NO_UNPUT */

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					clrestart(clin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( clwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    cllineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void clrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        clensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cl_create_buffer(clin,YY_BUF_SIZE );
	}

	cl_init_buffer(YY_CURRENT_BUFFER,input_file );
	cl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		clpop_buffer_state();
	 *		clpush_buffer_state(new_buffer);
     */
	clensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (clwrap()) processing, but the only time this flag
	 * is looked at is after clwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cl_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	clin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cl_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) clalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cl_create_buffer()
 * 
 */
    void cl_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		clfree((void *) b->yy_ch_buf  );

	clfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a clrestart() or at EOF.
 */
    static void cl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cl_init_buffer was _probably_
     * called from clrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cl_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cl_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void clpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	clensure_buffer_stack();

	/* This block is copied from cl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cl_switch_to_buffer. */
	cl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void clpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void clensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)clalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)clrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cl_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cl_scan_bytes() instead.
 */
YY_BUFFER_STATE cl_scan_string (yyconst char * yystr )
{
    
	return cl_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cl_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) clalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cltext[clleng] = (yy_hold_char); \
		(yy_c_buf_p) = cltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		clleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int clget_lineno  (void)
{
        
    return cllineno;
}

/** Get the input stream.
 * 
 */
FILE *clget_in  (void)
{
        return clin;
}

/** Get the output stream.
 * 
 */
FILE *clget_out  (void)
{
        return clout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t clget_leng  (void)
{
        return clleng;
}

/** Get the current token.
 * 
 */

char *clget_text  (void)
{
        return cltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void clset_lineno (int  line_number )
{
    
    cllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cl_switch_to_buffer
 */
void clset_in (FILE *  in_str )
{
        clin = in_str ;
}

void clset_out (FILE *  out_str )
{
        clout = out_str ;
}

int clget_debug  (void)
{
        return cl_flex_debug;
}

void clset_debug (int  bdebug )
{
        cl_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cllex_destroy(), so don't allocate here.
     */

    /* We do not touch cllineno unless the option is enabled. */
    cllineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    clin = stdin;
    clout = stdout;
#else
    clin = (FILE *) 0;
    clout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cllex_init()
     */
    return 0;
}

/* cllex_destroy is for both reentrant and non-reentrant scanners. */
int cllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		clpop_buffer_state();
	}

	/* Destroy the stack itself. */
	clfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *clalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *clrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void clfree (void * ptr )
{
	free( (char *) ptr );	/* see clrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 166 "cmdline_lexer.l"




void clerror(CmdLineCtx *ctx, const char *s, ...)
{
    va_list ap;
    va_start(ap, s);

    fprintf(stderr, "Error during parsing at line %d: ", cllineno);
    vfprintf(stderr, s, ap);
    fprintf(stderr, "\n");

    va_end(ap);
}

