
#line 3 "cmdline_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
#define yy_create_buffer cl_create_buffer
#define yy_delete_buffer cl_delete_buffer
#define yy_flex_debug cl_flex_debug
#define yy_init_buffer cl_init_buffer
#define yy_flush_buffer cl_flush_buffer
#define yy_load_buffer_state cl_load_buffer_state
#define yy_switch_to_buffer cl_switch_to_buffer
#define yyin clin
#define yyleng clleng
#define yylex cllex
#define yylineno cllineno
#define yyout clout
#define yyrestart clrestart
#define yytext cltext
#define yywrap clwrap
#define yyalloc clalloc
#define yyrealloc clrealloc
#define yyfree clfree

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

#if defined(__FreeBSD__)
#ifndef __STDC_LIMIT_MACROS
#define	__STDC_LIMIT_MACROS
#endif
#include <sys/cdefs.h>
#include <stdint.h>
#else
#define	__dead2
#endif

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__FreeBSD__) || \
    (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L)

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE clrestart(clin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern yy_size_t clleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *clin, *clout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cllex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-cllineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < clleng; ++yyl )\
                    if ( cltext[yyl] == '\n' )\
                        --cllineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via clrestart()), so that the user can continue scanning by
	 * just pointing clin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
#define yy_current_buffer YY_CURRENT_BUFFER

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when cltext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t clleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow clwrap()'s to do buffer switches
 * instead of setting up a fresh clin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void clrestart (FILE *input_file  );
void cl_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cl_create_buffer (FILE *file,int size  );
void cl_delete_buffer (YY_BUFFER_STATE b  );
void cl_flush_buffer (YY_BUFFER_STATE b  );
void clpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void clpop_buffer_state (void );

static void clensure_buffer_stack (void );
static void cl_load_buffer_state (void );
static void cl_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cl_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cl_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cl_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cl_scan_bytes (yyconst char *bytes,yy_size_t len  );

/* %endif */

void *clalloc (yy_size_t  );
void *clrealloc (void *,yy_size_t  );
void clfree (void *  );

#define yy_new_buffer cl_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        clensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cl_create_buffer(clin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] cltext/clin/clout/yy_state_type/cllineno etc. def's & init go here */
/* Begin user sect3 */

#define clwrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *clin = (FILE *) 0, *clout = (FILE *) 0;

typedef int yy_state_type;

extern int cllineno;

int cllineno = 1;

extern char *cltext;
#define yytext_ptr cltext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  ) __dead2;

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle cltext and clleng for yymore() goes here \ */\
	clleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to cltext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[625] =
    {   0,
        0,    0,    0,    0,   69,   67,   63,   63,    5,    2,
       67,   67,   64,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       65,   66,    1,    3,    4,   63,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    6,    0,    0,    0,    5,
        0,   61,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    1,    3,    0,   59,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    5,   62,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   61,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   16,    0,    0,    0,   61,    0,
        0,   14,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    8,    0,    0,    0,    0,    0,    0,   62,
        0,    7,    0,    0,    0,    0,    0,    0,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    6,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   46,    0,   48,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   20,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   15,   18,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   36,
       33,   47,    0,    0,    0,    0,   45,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   61,   13,
        0,    0,   12,    0,    0,    0,    0,   21,    0,    0,
        0,   11,    0,    0,    0,    0,   60,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   16,

        0,    0,    0,    0,    0,   14,   34,   35,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   50,    0,    0,
        0,    0,    0,    0,    0,   62,    0,    0,   26,    0,
       10,    0,    0,    0,    0,    0,    0,    0,    0,    8,
        0,    0,    0,    0,    0,    0,    0,    7,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   27,    0,    0,   22,
        0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,

       18,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   24,    0,   25,    0,    0,    0,    0,   13,
        0,    0,   12,    0,    0,    0,    0,   21,    0,    0,
        0,   11,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   58,
        0,    0,    0,    0,   23,    0,    0,    0,    0,    0,
        0,    0,   26,    0,   10,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   37,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   17,    0,    0,    0,    0,    0,   27,    0,    0,
       22,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   57,
        0,    0,    0,    0,    0,    0,   28,    0,    0,    0,
       24,    0,   25,    0,    0,    0,    0,   49,    0,    0,
        0,    0,    0,    0,    0,   38,    0,    0,   55,    0,
       52,   54,    0,    0,   19,    0,    0,   23,    0,    0,
        0,    0,    0,    0,    0,    0,   44,   41,   42,   43,
       51,    0,   53,   30,   29,    0,    0,   17,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       28,    0,    0,    0,    0,    0,   31,    0,    0,   19,
        0,   32,   39,   40,    0,   30,   29,    0,    0,    0,
        0,   31,   56,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   14,    1,    1,    1,
       16,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
        1,   33,   34,   35,   36,   37,   38,   39,   40,    1,
        1,    1,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,    1,   58,   59,   60,   61,   62,   63,   64,
       65,    1,   66,    1,   67,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    1,
        1,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[630] =
    {   0,
        0, 1247, 1247, 1246, 1250, 1254,   66,   68, 1254, 1254,
       33,   66, 1254,   55,   63,   66,   69,   67,   67,   72,
       59,   60,   70,   60,   98,   68,   65,   81,   70,   83,
     1254, 1254,    0,    0, 1254,  129,  128,    0,  129,  105,
      130, 1208,  131,  117,  125, 1254,  114,  137,  137,  126,
      140, 1254,  139,  135,  143,  150,  150,  142,  136,  135,
      150,  167,  161,    0,    0,  192,    0, 1207, 1206, 1205,
      188,  162,  178,  187,  181,  181, 1204,  182,  182, 1203,
      196,  193, 1254, 1254,  182,  188,  194,  192,  200,  206,
      207,  196,  205,  199, 1254,  250,  247,  294,  335,  228,

      213,  235,  233,  240,  261,  240,  267,  271,  274,  261,
      288,  296,  302,  297, 1202,  289,  304,  296, 1254,  314,
      310, 1201,  363,  305,  314,  363,  317,  317,  344,  334,
      348,  362,  354,  358,  374,  363,  378,  380,  381,  382,
      385,  406,  385,  390,  402,  378,  396,  397,  402,  416,
      415,  409, 1254,  414,  426,  415,  417,  433,  432, 1254,
      412, 1254,  428,  419,  420,  426, 1200,  442, 1254,  432,
      426,  447,  485,  464,  468, 1199,  483,  448, 1254,  448,
      472,  484,  480,  479,  488,  497,  498,  490,  480,  486,
      503,  487,  488, 1254,  506, 1198,  494, 1226,  493,  514,

      515,  500,  500,  508, 1196,  519,  508,  526,  534,  534,
      520,  534,  524, 1195,  544,  529,  531,  532,  536,  552,
      549,  546,  551,  553,  539, 1194, 1193,  554,  556,  600,
      567,  569,  578,  572,  572, 1192,  583, 1191,  596,  593,
      582,  586,  591,  589,  597,  603,  592,  606,  600, 1254,
      223, 1254,  612,  613, 1185,  614, 1254,  627,  603,  623,
      634,  630,  629, 1178,  617,  627,  628,  641, 1254, 1254,
      629,  637, 1254,  646,  652,  649,  653, 1254,  635,  654,
      657, 1254,  640,  648,  653,  648, 1254,  650,  645,  651,
      673,  653,  681,  685,  668,  676,  683,  694,  687, 1175,

      679,  695,  687,  702,  698, 1164, 1254, 1254,  701,  689,
      699,  695,  277, 1189, 1195, 1194,  700, 1254,  706,  711,
      716,  707,  718,  713,  719, 1254,  722,  717, 1254,  734,
     1254,  725,  733,  724,  726,  741,  743,  734,  743, 1254,
      737,  749,  738,  740,  756,  755,  735, 1254,  756,  747,
      748,  751, 1160,  766, 1254,  756,  750,  766,  755,  777,
      774,  785, 1182, 1177, 1177, 1176, 1143,  789,  782,  797,
      786,  796,  784,  801,  786,  793, 1254,  795,  803, 1254,
      788,  810,  803,  814,  806,  549,  800,  547,  821,  805,
      808,  816,  820,  836,  833,  830,  840,  842,  829,  546,

      544,  845,  842,  852,  851,  854,  575,  541,  428,  426,
      374,  848,  848,  327,  839,  850,  841,  861,  305,  304,
      851,  863, 1254,  864, 1254,  856,  859,  876,  866, 1254,
      867,  874, 1254,  883,  888,  890,  894, 1254,  877,  897,
      900, 1254,  884,  887,  892,  887,  890,  293,  905,   85,
      901,  907,  908,  909,  905,  916,  906,  904,  909, 1254,
      289,  924,  925,  925, 1254,  921,  927,  924,  927,  931,
      945,  933, 1254,  951, 1254,  942,  950,  941,  938,  953,
      954,  949,  958,  963,  950, 1254,  314,  283,  956,  959,
      961,  964,  984,  985,  986,  971,  976,  984,  991,  993,

      999, 1254, 1000,  998,  999,  985,  993, 1254,  995, 1003,
     1254,  988, 1010, 1003, 1014, 1006,  193, 1001, 1017,  104,
       65, 1023, 1026, 1034, 1035, 1034, 1019, 1022, 1040, 1254,
     1041, 1024, 1026, 1032, 1034, 1037, 1254, 1037, 1040, 1052,
     1254, 1053, 1254, 1043, 1050, 1065, 1048, 1254, 1065, 1061,
     1064, 1071, 1074, 1082, 1083, 1254, 1082, 1087, 1254, 1065,
     1254, 1254, 1090, 1091, 1254, 1079, 1088, 1254, 1084, 1091,
     1083, 1086, 1089, 1090, 1095, 1096, 1254, 1254, 1254, 1254,
     1254, 1102, 1254, 1254, 1254, 1111, 1116, 1254, 1117, 1114,
     1117, 1104, 1122, 1134, 1135, 1132, 1134, 1120, 1126, 1129,

     1254, 1130, 1131, 1148, 1150, 1135, 1254, 1150, 1151, 1254,
     1138, 1254, 1254, 1254, 1153, 1254, 1254, 1154, 1148, 1162,
     1149, 1254, 1254, 1254, 1208, 1211, 1217, 1223, 1226
    } ;

static yyconst flex_int16_t yy_def[630] =
    {   0,
      624,    1,  625,  625,  624,  624,  624,  624,  624,  624,
      626,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  627,  628,  624,  624,  624,  629,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  627,  628,  624,  629,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,    0,  624,  624,  624,  624,  624
    } ;

static yyconst flex_int16_t yy_nxt[1322] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   13,    6,    6,   14,   15,
       16,   17,    6,    6,   18,    6,   19,   20,   21,   22,
       23,   24,    6,   25,   26,   27,   28,   29,    6,   30,
        6,    6,    6,   14,   15,   16,   17,    6,    6,   18,
        6,   19,   20,   21,   22,   23,   24,    6,   25,   26,
       27,   28,   29,    6,   30,   31,   32,   36,   36,   36,
       36,   38,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   39,   40,   41,   42,   45,   46,   47,   48,   49,
       50,   51,   53,  487,   60,   43,   38,  488,   58,   52,

       59,   61,   62,   63,   44,  551,   39,   40,   41,   42,
       45,   46,   47,   48,   49,   50,   51,   53,   54,   60,
       43,   72,   55,   58,   52,   59,   61,   62,   63,   44,
       36,   36,   56,   57,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   54,  550,   68,   72,   55,   73,   76,
       77,   78,   79,   80,   81,   69,   82,   56,   57,   70,
       83,   84,   74,   85,   86,   87,   88,   89,   90,   71,
       68,   91,   92,   73,   76,   77,   78,   79,   80,   81,
       69,   82,   93,   94,   70,   83,   84,   74,   85,   86,
       87,   88,   89,   90,   95,  102,   91,   92,   96,   96,

       96,   96,   96,   96,   96,   96,   96,   93,   94,  100,
      103,  104,  105,  106,  108,  109,  111,  112,  113,   95,
      102,  114,  101,  115,  116,  117,  118,  119,  120,  121,
      122,  307,  308,  547,  100,  103,  104,  105,  106,  108,
      109,  111,  112,  113,  151,  152,  114,  101,  115,  116,
      117,  118,  119,  120,  121,  122,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  124,  125,  126,  153,  151,
      152,  127,  154,  128,  129,  130,  155,  156,  131,  157,
      132,  133,  134,  135,  136,  363,  158,  159,  364,  521,
      124,  125,  126,  153,  160,  161,  127,  154,  128,  129,

      130,  155,  156,  131,  157,  132,  133,  134,  135,  136,
      137,  158,  159,  138,  139,  162,  140,  163,  164,  160,
      161,  165,  141,  167,  168,  169,  142,  143,  520,  498,
      170,  171,  174,  485,  175,  137,  179,  180,  138,  139,
      162,  140,  163,  164,  463,  462,  165,  141,  167,  168,
      169,  142,  143,  144,  145,  170,  171,  174,  146,  175,
      181,  179,  180,  147,  182,  148,  149,  457,  150,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  144,  145,
      183,  176,  184,  146,  188,  181,  185,  189,  147,  182,
      148,  149,  177,  150,  190,  191,  186,  187,  192,  196,

      193,  178,  197,  194,  198,  183,  176,  184,  201,  188,
      202,  185,  189,  195,  454,  205,  206,  177,  203,  190,
      191,  186,  187,  192,  196,  193,  178,  197,  194,  198,
      199,  207,  204,  201,  208,  202,  210,  209,  195,  200,
      205,  206,  211,  203,  212,  213,  214,  215,  216,  217,
      218,  219,  220,  221,  222,  199,  207,  204,  223,  208,
      225,  210,  209,  226,  200,  227,  453,  211,  452,  212,
      213,  214,  215,  216,  217,  218,  219,  220,  221,  222,
      231,  228,  237,  223,  229,  225,  232,  238,  226,  239,
      227,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      233,  235,  236,  240,  241,  231,  228,  237,  242,  229,
      243,  232,  238,  244,  239,  245,  246,  247,  248,  249,
      250,  251,  252,  254,  256,  233,  235,  236,  240,  241,
      257,  258,  259,  242,  260,  243,  261,  263,  244,  264,
      245,  246,  247,  248,  249,  250,  251,  252,  254,  256,
      265,  266,  267,  268,  269,  257,  258,  259,  270,  260,
      272,  261,  263,  273,  264,  274,  275,  276,  277,  278,
      279,  280,  281,  282,  285,  265,  266,  267,  268,  269,
      286,  451,  450,  270,  444,  272,  443,  431,  273,  429,
      274,  275,  276,  277,  278,  279,  280,  281,  282,  285,

      288,  289,  290,  291,  292,  286,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  294,  296,  297,  298,  299,
      300,  301,  302,  303,  304,  288,  289,  290,  291,  292,
      305,  306,  309,  310,  312,  313,  314,  317,  315,  318,
      294,  296,  297,  298,  299,  300,  301,  302,  303,  304,
      319,  320,  321,  323,  324,  305,  306,  309,  310,  312,
      325,  326,  317,  327,  318,  328,  329,  316,  330,  331,
      332,  333,  334,  335,  336,  319,  320,  321,  323,  324,
      337,  338,  339,  340,  341,  325,  326,  342,  327,  343,
      328,  329,  344,  330,  331,  332,  333,  334,  335,  336,

      345,  346,  347,  348,  349,  337,  338,  339,  340,  341,
      350,  351,  342,  353,  343,  354,  355,  344,  356,  357,
      359,  360,  361,  362,  368,  345,  346,  347,  348,  349,
      369,  370,  371,  372,  373,  350,  351,  374,  353,  375,
      354,  355,  376,  356,  357,  359,  360,  361,  362,  368,
      377,  378,  379,  380,  381,  369,  370,  371,  372,  373,
      382,  383,  374,  384,  375,  385,  386,  376,  387,  388,
      389,  390,  391,  392,  393,  377,  378,  379,  380,  381,
      394,  395,  396,  397,  399,  382,  383,  400,  384,  401,
      385,  386,  404,  387,  388,  389,  390,  391,  392,  393,

      402,  405,  406,  403,  407,  394,  395,  396,  397,  399,
      413,  414,  400,  415,  401,  416,  417,  404,  418,  419,
      420,  421,  422,  423,  424,  402,  405,  406,  403,  407,
      425,  426,  427,  428,  430,  413,  414,  432,  415,  433,
      416,  417,  434,  418,  419,  420,  421,  422,  423,  424,
      435,  436,  437,  438,  439,  425,  426,  427,  428,  430,
      440,  441,  432,  442,  433,  445,  446,  434,  447,  448,
      449,  455,  456,  458,  459,  435,  436,  437,  438,  439,
      460,  461,  464,  465,  466,  440,  441,  467,  442,  468,
      445,  446,  469,  447,  448,  449,  455,  456,  458,  459,

      470,  471,  472,  473,  474,  460,  461,  464,  465,  466,
      475,  476,  467,  477,  468,  478,  479,  469,  480,  481,
      482,  483,  484,  486,  489,  470,  471,  472,  473,  474,
      490,  491,  492,  493,  494,  475,  476,  495,  477,  496,
      478,  479,  497,  480,  481,  482,  483,  484,  486,  489,
      499,  500,  501,  502,  503,  490,  491,  492,  493,  494,
      504,  505,  495,  506,  496,  507,  508,  497,  509,  510,
      511,  512,  513,  514,  515,  499,  500,  501,  502,  503,
      516,  517,  518,  519,  522,  504,  505,  523,  506,  524,
      507,  508,  525,  509,  510,  511,  512,  513,  514,  515,

      526,  527,  528,  529,  530,  516,  517,  518,  519,  522,
      531,  532,  523,  533,  524,  534,  535,  525,  536,  537,
      538,  539,  540,  541,  542,  526,  527,  528,  529,  530,
      543,  544,  545,  546,  548,  531,  532,  549,  533,  552,
      534,  535,  553,  536,  537,  538,  539,  540,  541,  542,
      554,  555,  556,  557,  558,  543,  544,  545,  546,  548,
      559,  560,  549,  561,  552,  562,  563,  553,  564,  565,
      566,  567,  568,  569,  570,  554,  555,  556,  557,  558,
      571,  572,  573,  574,  575,  559,  560,  576,  561,  577,
      562,  563,  578,  564,  565,  566,  567,  568,  569,  570,

      579,  580,  581,  582,  583,  571,  572,  573,  574,  575,
      584,  585,  576,  586,  577,  587,  588,  578,  589,  590,
      591,  592,  593,  594,  595,  579,  580,  581,  582,  583,
      596,  597,  598,  599,  600,  584,  585,  601,  586,  602,
      587,  588,  603,  589,  590,  591,  592,  593,  594,  595,
      604,  605,  606,  607,  608,  596,  597,  598,  599,  600,
      609,  610,  601,  611,  602,  612,  613,  603,  614,  615,
      616,  617,  618,  619,  620,  604,  605,  606,  607,  608,
      621,  622,  623,  412,  411,  609,  610,  410,  611,  409,
      612,  613,  408,  614,  615,  616,  617,  618,  619,  620,

      398,  367,  366,  365,  358,  621,  622,  623,   34,   34,
       34,   34,   34,   34,   37,  352,   37,   64,  322,   64,
       64,   64,   64,   65,   65,  311,   65,   65,   65,   67,
       67,  295,  293,  284,  283,  271,  262,  255,  253,  234,
      224,  172,  166,  110,  107,   99,   98,   97,   75,  624,
       35,   35,   33,    5,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624
    } ;

static yyconst flex_int16_t yy_chk[1322] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    7,    8,
        8,   11,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   14,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,  450,   27,   16,   11,  450,   26,   23,

       26,   28,   29,   30,   16,  521,   14,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   27,
       16,   40,   25,   26,   23,   26,   28,   29,   30,   16,
       36,   36,   25,   25,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   25,  520,   39,   40,   25,   41,   43,
       43,   44,   45,   47,   48,   39,   49,   25,   25,   39,
       50,   51,   41,   53,   54,   55,   56,   57,   58,   39,
       39,   59,   60,   41,   43,   43,   44,   45,   47,   48,
       39,   49,   61,   62,   39,   50,   51,   41,   53,   54,
       55,   56,   57,   58,   63,   72,   59,   60,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   61,   62,   71,
       73,   74,   75,   76,   78,   79,   81,   82,   85,   63,
       72,   86,   71,   87,   88,   89,   90,   91,   92,   93,
       94,  251,  251,  517,   71,   73,   74,   75,   76,   78,
       79,   81,   82,   85,  100,  101,   86,   71,   87,   88,
       89,   90,   91,   92,   93,   94,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   97,   97,   97,  102,  100,
      101,   97,  103,   97,   97,   97,  104,  105,   97,  106,
       97,   97,   97,   97,   97,  313,  107,  108,  313,  488,
       97,   97,   97,  102,  109,  110,   97,  103,   97,   97,

       97,  104,  105,   97,  106,   97,   97,   97,   97,   97,
       98,  107,  108,   98,   98,  111,   98,  112,  113,  109,
      110,  114,   98,  116,  117,  118,   98,   98,  487,  461,
      120,  121,  124,  448,  125,   98,  127,  128,   98,   98,
      111,   98,  112,  113,  420,  419,  114,   98,  116,  117,
      118,   98,   98,   99,   99,  120,  121,  124,   99,  125,
      129,  127,  128,   99,  130,   99,   99,  414,   99,  123,
      123,  123,  123,  123,  123,  123,  123,  123,   99,   99,
      131,  126,  132,   99,  133,  129,  132,  134,   99,  130,
       99,   99,  126,   99,  135,  136,  132,  132,  137,  139,

      138,  126,  140,  138,  141,  131,  126,  132,  143,  133,
      144,  132,  134,  138,  411,  146,  147,  126,  145,  135,
      136,  132,  132,  137,  139,  138,  126,  140,  138,  141,
      142,  148,  145,  143,  149,  144,  150,  149,  138,  142,
      146,  147,  151,  145,  152,  154,  155,  156,  157,  158,
      159,  161,  163,  164,  165,  142,  148,  145,  166,  149,
      168,  150,  149,  170,  142,  171,  410,  151,  409,  152,
      154,  155,  156,  157,  158,  159,  161,  163,  164,  165,
      174,  172,  178,  166,  172,  168,  175,  180,  170,  181,
      171,  173,  173,  173,  173,  173,  173,  173,  173,  173,

      175,  177,  177,  182,  183,  174,  172,  178,  184,  172,
      185,  175,  180,  186,  181,  187,  188,  189,  190,  191,
      192,  193,  195,  197,  199,  175,  177,  177,  182,  183,
      200,  201,  202,  184,  203,  185,  204,  206,  186,  207,
      187,  188,  189,  190,  191,  192,  193,  195,  197,  199,
      208,  209,  210,  211,  212,  200,  201,  202,  213,  203,
      215,  204,  206,  216,  207,  217,  218,  219,  220,  221,
      222,  223,  224,  225,  228,  208,  209,  210,  211,  212,
      229,  408,  407,  213,  401,  215,  400,  388,  216,  386,
      217,  218,  219,  220,  221,  222,  223,  224,  225,  228,

      231,  232,  233,  234,  235,  229,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  237,  239,  240,  241,  242,
      243,  244,  245,  246,  247,  231,  232,  233,  234,  235,
      248,  249,  253,  254,  256,  258,  258,  259,  258,  260,
      237,  239,  240,  241,  242,  243,  244,  245,  246,  247,
      261,  262,  263,  265,  266,  248,  249,  253,  254,  256,
      267,  268,  259,  271,  260,  272,  274,  258,  275,  276,
      277,  279,  280,  281,  283,  261,  262,  263,  265,  266,
      284,  285,  286,  288,  289,  267,  268,  290,  271,  291,
      272,  274,  292,  275,  276,  277,  279,  280,  281,  283,

      293,  294,  295,  296,  297,  284,  285,  286,  288,  289,
      298,  299,  290,  301,  291,  302,  303,  292,  304,  305,
      309,  310,  311,  312,  317,  293,  294,  295,  296,  297,
      319,  320,  321,  322,  323,  298,  299,  324,  301,  325,
      302,  303,  327,  304,  305,  309,  310,  311,  312,  317,
      328,  330,  332,  333,  334,  319,  320,  321,  322,  323,
      335,  336,  324,  337,  325,  338,  339,  327,  341,  342,
      343,  344,  345,  346,  347,  328,  330,  332,  333,  334,
      349,  350,  351,  352,  354,  335,  336,  356,  337,  357,
      338,  339,  359,  341,  342,  343,  344,  345,  346,  347,

      358,  360,  361,  358,  362,  349,  350,  351,  352,  354,
      368,  369,  356,  370,  357,  371,  372,  359,  373,  374,
      375,  376,  378,  379,  381,  358,  360,  361,  358,  362,
      382,  383,  384,  385,  387,  368,  369,  389,  370,  390,
      371,  372,  391,  373,  374,  375,  376,  378,  379,  381,
      392,  393,  394,  395,  396,  382,  383,  384,  385,  387,
      397,  398,  389,  399,  390,  402,  403,  391,  404,  405,
      406,  412,  413,  415,  416,  392,  393,  394,  395,  396,
      417,  418,  421,  422,  424,  397,  398,  426,  399,  427,
      402,  403,  428,  404,  405,  406,  412,  413,  415,  416,

      429,  431,  432,  434,  435,  417,  418,  421,  422,  424,
      436,  437,  426,  439,  427,  440,  441,  428,  443,  444,
      445,  446,  447,  449,  451,  429,  431,  432,  434,  435,
      452,  453,  454,  455,  456,  436,  437,  457,  439,  458,
      440,  441,  459,  443,  444,  445,  446,  447,  449,  451,
      462,  463,  464,  466,  467,  452,  453,  454,  455,  456,
      468,  469,  457,  470,  458,  471,  472,  459,  474,  476,
      477,  478,  479,  480,  481,  462,  463,  464,  466,  467,
      482,  483,  484,  485,  489,  468,  469,  490,  470,  491,
      471,  472,  492,  474,  476,  477,  478,  479,  480,  481,

      493,  494,  495,  496,  497,  482,  483,  484,  485,  489,
      498,  499,  490,  500,  491,  501,  503,  492,  504,  505,
      506,  507,  509,  510,  512,  493,  494,  495,  496,  497,
      513,  514,  515,  516,  518,  498,  499,  519,  500,  522,
      501,  503,  523,  504,  505,  506,  507,  509,  510,  512,
      524,  525,  526,  527,  528,  513,  514,  515,  516,  518,
      529,  531,  519,  532,  522,  533,  534,  523,  535,  536,
      538,  539,  540,  542,  544,  524,  525,  526,  527,  528,
      545,  546,  547,  549,  550,  529,  531,  551,  532,  552,
      533,  534,  553,  535,  536,  538,  539,  540,  542,  544,

      554,  555,  557,  558,  560,  545,  546,  547,  549,  550,
      563,  564,  551,  566,  552,  567,  569,  553,  570,  571,
      572,  573,  574,  575,  576,  554,  555,  557,  558,  560,
      582,  586,  587,  589,  590,  563,  564,  591,  566,  592,
      567,  569,  593,  570,  571,  572,  573,  574,  575,  576,
      594,  595,  596,  597,  598,  582,  586,  587,  589,  590,
      599,  600,  591,  602,  592,  603,  604,  593,  605,  606,
      608,  609,  611,  615,  618,  594,  595,  596,  597,  598,
      619,  620,  621,  367,  366,  599,  600,  365,  602,  364,
      603,  604,  363,  605,  606,  608,  609,  611,  615,  618,

      353,  316,  315,  314,  306,  619,  620,  621,  625,  625,
      625,  625,  625,  625,  626,  300,  626,  627,  264,  627,
      627,  627,  627,  628,  628,  255,  628,  628,  628,  629,
      629,  238,  236,  227,  226,  214,  205,  198,  196,  176,
      167,  122,  115,   80,   77,   70,   69,   68,   42,    5,
        4,    3,    2,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,

      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624,  624,  624,  624,  624,  624,  624,  624,  624,  624,
      624
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[69] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cl_flex_debug;
int cl_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[68] =
    {   0,
       36,   38,   39,   41,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
       72,   74,   75,   76,   77,   78,   79,   80,   81,   82,
       83,   84,   85,   86,   87,   88,   89,   90,   91,   93,
       94,   95,   96,   97,   98,   99,  100,  101,  103,  131,
      133,  134,  136,  137,  138,  139,  140
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cltext;
/* cmdline lexical analyser */
/*
 * Copyright (c) 2018 Mastercard
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* %option debug */
#include "config.h"
#include <stdarg.h>
#include "cmdline_parser.h"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cllex_destroy (void );

int clget_debug (void );

void clset_debug (int debug_flag  );

YY_EXTRA_TYPE clget_extra (void );

void clset_extra (YY_EXTRA_TYPE user_defined  );

FILE *clget_in (void );

void clset_in  (FILE * in_str  );

FILE *clget_out (void );

void clset_out  (FILE * out_str  );

yy_size_t clget_leng (void );

char *clget_text (void );

int clget_lineno (void );

void clset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int clwrap (void );
#else
extern int clwrap (void );
#endif
#endif

/* %not-for-header */

#ifndef YY_NO_UNPUT
    static void yyunput (int c,char *buf_ptr  );
#endif
    
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cltext, clleng, 1, clout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( clin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( clin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, clin))==0 && ferror(clin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(clin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int cllex (void);

#define YY_DECL int cllex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cltext and clleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	if ( clleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(cltext[clleng - 1] == '\n'); \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
/* %% [7.0] user's declarations go here */

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! clin )
/* %if-c-only */
			clin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! clout )
/* %if-c-only */
			clout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			clensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cl_create_buffer(clin,YY_BUF_SIZE );
		}

		cl_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of cltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 625 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 624 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for cllineno update goes here */

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < clleng; ++yyl )
				if ( cltext[yyl] == '\n' )
					   
    cllineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( cl_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 68 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], cltext );
			else if ( yy_act == 68 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         cltext );
			else if ( yy_act == 69 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{ /* skipping comment */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
{ cllval.val_str.len=0; BEGIN(STR); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
{ cllval.val_str.val = strdup(cltext); cllval.val_str.len = strlen(cltext); }
	YY_BREAK
case YY_STATE_EOF(STR):
{ clerror(NULL, "Unterminated quoted string"); yyterminate(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
{   /* special case: if we have an empty string, regular rule is never executed */
		/* in which case, we perform the empty string assignment from here */
    if (cllval.val_str.len==0) { cllval.val_str.val=strdup(""); } BEGIN(INITIAL); return STRING;
	    }
	YY_BREAK
case 5:
YY_RULE_SETUP
{ return NO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
{ cllval.ckattr = CKA_ID; return CKATTR_STR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
{ cllval.ckattr = CKA_LABEL; return CKATTR_STR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
{ cllval.ckattr = CKA_CLASS; return CKATTR_CLASS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
{ cllval.ckattr = CKA_TOKEN; return CKATTR_BOOL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
{ cllval.ckattr = CKA_KEY_TYPE; return CKATTR_KEY; }
	YY_BREAK
case 11:
YY_RULE_SETUP
{ cllval.ckattr = CKA_SUBJECT; return CKATTR_STR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
{ cllval.ckattr = CKA_ENCRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
{ cllval.ckattr = CKA_DECRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
{ cllval.ckattr = CKA_WRAP; return CKATTR_BOOL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
{ cllval.ckattr = CKA_UNWRAP; return CKATTR_BOOL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
{ cllval.ckattr = CKA_SIGN; return CKATTR_BOOL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
{ cllval.ckattr = CKA_SIGN_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
{ cllval.ckattr = CKA_VERIFY; return CKATTR_BOOL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
{ cllval.ckattr = CKA_VERIFY_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
{ cllval.ckattr = CKA_DERIVE; return CKATTR_BOOL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
{ cllval.ckattr = CKA_PRIVATE; return CKATTR_BOOL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
{ cllval.ckattr = CKA_SENSITIVE; return CKATTR_BOOL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
{ cllval.ckattr = CKA_EXTRACTABLE; return CKATTR_BOOL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
{ cllval.ckattr = CKA_MODIFIABLE; return CKATTR_BOOL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
{ cllval.ckattr = CKA_START_DATE; return CKATTR_DATE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
{ cllval.ckattr = CKA_END_DATE; return CKATTR_DATE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
{ cllval.ckattr = CKA_EC_PARAMS; return CKATTR_STR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
{ cllval.ckattr = CKA_WRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
{ cllval.ckattr = CKA_UNWRAP_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
{ cllval.ckattr = CKA_DERIVE_TEMPLATE; return CKATTR_TEMPLATE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
{ cllval.ckattr = CKA_WRAP_WITH_TRUSTED; return CKATTR_BOOL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
{ cllval.val_key = CKK_GENERIC_SECRET; return KEYTYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
{ cllval.val_key = CKK_DES           ; return KEYTYPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
{ cllval.val_key = CKK_DES2          ; return KEYTYPE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
{ cllval.val_key = CKK_DES3          ; return KEYTYPE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
{ cllval.val_key = CKK_AES           ; return KEYTYPE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
{ cllval.val_key = CKK_MD5_HMAC      ; return KEYTYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
{ cllval.val_key = CKK_SHA_1_HMAC    ; return KEYTYPE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
{ cllval.val_key = CKK_RIPEMD128_HMAC; return KEYTYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
{ cllval.val_key = CKK_RIPEMD160_HMAC; return KEYTYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
{ cllval.val_key = CKK_SHA256_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
{ cllval.val_key = CKK_SHA384_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
{ cllval.val_key = CKK_SHA512_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
{ cllval.val_key = CKK_SHA224_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
{ cllval.val_key = CKK_RSA           ; return KEYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ cllval.val_key = CKK_DH            ; return KEYTYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
{ cllval.val_key = CKK_DSA           ; return KEYTYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ cllval.val_key = CKK_EC            ; return KEYTYPE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ cllval.val_key = CKK_EC_EDWARDS    ; return KEYTYPE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ cllval.val_cls = CKO_DATA ; return OCLASS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ cllval.val_cls = CKO_CERTIFICATE ; return OCLASS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
{ cllval.val_cls = CKO_PUBLIC_KEY ; return OCLASS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ cllval.val_cls = CKO_PRIVATE_KEY ; return OCLASS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ cllval.val_cls = CKO_SECRET_KEY ; return OCLASS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
{ cllval.val_cls = CKO_HW_FEATURE ; return OCLASS; }
	YY_BREAK
case 56:
YY_RULE_SETUP
{ cllval.val_cls = CKO_DOMAIN_PARAMETERS ; return OCLASS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ cllval.val_cls = CKO_MECHANISM ; return OCLASS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
{ cllval.val_cls = CKO_OTP_KEY ; return OCLASS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
{   if(strlen(cltext)%2==1) {
			clerror(NULL, "Invalid hexadecimal string <%s>: odd length", cltext);
			yyterminate();
		    } else {
			cllval.val_str.len = (strlen(cltext)>>1) - 1; /* we skip the '0x' prefix */
			/* convert to hex */
			size_t i;
			char *target = malloc(cllval.val_str.len);
			if(target==NULL) {
			    cllval.val_str.len = 0 ;
			    clerror(NULL,"Memory allocation error during lexical analysis of <%s>", cltext);
			    yyterminate();
			}

			/* we start at cltext[2] */
			for(i=0;i<cllval.val_str.len; i++) {
			    /* the following trick is needed to have CLANG shut up */
			    /* strictly speaking, %x expects indeed a pointer to an integer */

			    volatile int tmp;
			    sscanf( &cltext[ (i<<1) + 2 ], "%2x", &tmp);
			    target[i] = (unsigned char) tmp;
			}
			cllval.val_str.val = target; /* then reassign */
			return STRING;
		    }
		}
	YY_BREAK
case 60:
YY_RULE_SETUP
{ memcpy(cllval.val_date.as_buffer, cltext, 8); return TOK_DATE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
{ cllval.val_bool = 1; return TOK_BOOLEAN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ cllval.val_bool = 0; return TOK_BOOLEAN; }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
{ /* ignore whitespace and comma */ }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ return ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ return CURLY_OPEN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ return CURLY_CLOSE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ return cltext[0]; } /* catch-all http://stackoverflow.com/questions/18837828/how-should-i-handle-lexical-errors-in-my-flex-lexer */
	YY_BREAK
/* gives it back to bison, so error comes from parser */
case 68:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed clin at a new source and called
			 * cllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = clin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( clwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cllex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					clrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			clrestart(clin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) clrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 625 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 625 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 624);

		return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

#ifndef YY_NO_UNPUT
    static void yyunput (int c, char * yy_bp )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update cllineno here */

    if ( c == '\n' ){
        --cllineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif	/* ifndef YY_NO_UNPUT */
/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					clrestart(clin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( clwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cltext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and cllineno */
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    cllineno++;
;

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void clrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        clensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cl_create_buffer(clin,YY_BUF_SIZE );
	}

	cl_init_buffer(YY_CURRENT_BUFFER,input_file );
	cl_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void cl_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		clpop_buffer_state();
	 *		clpush_buffer_state(new_buffer);
     */
	clensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cl_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (clwrap()) processing, but the only time this flag
	 * is looked at is after clwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void cl_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	clin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE cl_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) clalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cl_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cl_create_buffer()
 * 
 */
/* %if-c-only */
    void cl_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		clfree((void *) b->yy_ch_buf  );

	clfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a clrestart() or at EOF.
 */
/* %if-c-only */
    static void cl_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	cl_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cl_init_buffer was _probably_
     * called from clrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void cl_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cl_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void clpush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	clensure_buffer_stack();

	/* This block is copied from cl_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cl_switch_to_buffer. */
	cl_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void clpop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cl_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cl_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void clensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)clalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)clrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in clensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cl_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) clalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cl_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to cllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cl_scan_bytes() instead.
 */
YY_BUFFER_STATE cl_scan_string (yyconst char * yystr )
{
    
	return cl_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to cllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cl_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) clalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cl_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cl_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cl_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cltext[clleng] = (yy_hold_char); \
		(yy_c_buf_p) = cltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		clleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int clget_lineno  (void)
{
        
    return cllineno;
}

/** Get the input stream.
 * 
 */
FILE *clget_in  (void)
{
        return clin;
}

/** Get the output stream.
 * 
 */
FILE *clget_out  (void)
{
        return clout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t clget_leng  (void)
{
        return clleng;
}

/** Get the current token.
 * 
 */

char *clget_text  (void)
{
        return cltext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void clset_lineno (int  line_number )
{
    
    cllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cl_switch_to_buffer
 */
void clset_in (FILE *  in_str )
{
        clin = in_str ;
}

void clset_out (FILE *  out_str )
{
        clout = out_str ;
}

int clget_debug  (void)
{
        return cl_flex_debug;
}

void clset_debug (int  bdebug )
{
        cl_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cllex_destroy(), so don't allocate here.
     */

    /* We do not touch cllineno unless the option is enabled. */
    cllineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    clin = stdin;
    clout = stdout;
#else
    clin = (FILE *) 0;
    clout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cllex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* cllex_destroy is for both reentrant and non-reentrant scanners. */
int cllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cl_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		clpop_buffer_state();
	}

	/* Destroy the stack itself. */
	clfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cllex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *clalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *clrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void clfree (void * ptr )
{
	free( (char *) ptr );	/* see clrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

void clerror(CmdLineCtx *ctx, const char *s, ...)
{
    va_list ap;
    va_start(ap, s);

    fprintf(stderr, "Error during parsing at line %d: ", cllineno);
    vfprintf(stderr, s, ap);
    fprintf(stderr, "\n");

    va_end(ap);
}

