
#line 3 "wrappedkey_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[583] =
    {   0,
        0,    0,    0,    0,    0,    0,   87,   85,   84,   84,
        6,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,    1,   86,    5,
       86,    7,    8,   84,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   78,    0,    0,   80,    0,    0,
        0,    0,    0,    1,    4,    0,    7,    0,   83,    0,
       81,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   65,    0,    0,    0,    0,   79,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   71,    0,   13,    0,   79,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   80,   77,   12,    0,
        0,    0,    0,    0,   14,    0,    0,    0,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   53,    0,   55,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   43,   40,   54,    0,    0,    0,
       52,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   79,    0,    0,    0,    0,   82,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   26,    0,    0,    0,    0,    0,   24,
        0,   41,   42,    0,    0,    0,    0,    0,    0,    0,
       72,    0,    0,    0,    0,    0,   56,    0,    0,    0,
        0,    0,    0,    0,   80,    0,    0,    0,    0,    0,
        0,    0,   18,    0,    0,    0,    0,    0,    0,    0,

       17,    0,    0,    0,    0,    0,    0,   19,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   30,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       25,   28,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   73,   74,   75,   76,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,    0,   22,    0,    0,    0,    0,   31,    0,    0,
        0,   21,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   64,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   36,    0,
       20,    0,    0,    0,    0,    0,    0,    0,   44,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    9,    0,   15,    0,    0,    0,    0,
       38,    0,    0,   32,    0,    0,    0,   66,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   63,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   34,    0,   35,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   45,    0,    0,

       61,    0,   58,   60,    0,    0,    0,    0,   37,   33,
        0,    0,   67,   68,   69,   70,    0,    0,    0,   51,
       48,   49,   50,   57,    0,   59,    0,    0,    0,    0,
       27,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   29,
       39,   46,   47,    0,   11,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   62,    0,    0,    0,
        0,    0,    0,    0,    0,   10,    0,    0,    3,    0,
        2,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    1,    1,
        1,    1,    8,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   19,    1,    1,    1,
        8,    1,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
        8,   37,   38,   39,   40,   41,   42,   43,   44,    8,
        1,    1,    1,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,    8,   62,   63,   64,   65,   66,   67,   68,
       69,    8,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    3,    1,    5,
        3,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    8,    3,    1,    7,    7,    7,    7,    7,
        7,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    8,    3
    } ;

static yyconst flex_uint16_t yy_base[590] =
    {   0,
        0, 1195,   67,   69, 1195, 1194, 1199, 1203,   77,   81,
     1203, 1189,   64,   77,   39,   77,   56,   67,   57,   80,
       76,   69,   84,   75,   72,   73,   86,    0,    0, 1203,
     1188,    0, 1203,  112, 1187,  126,  137,    0,  112,  135,
      163,  126,  129,  124, 1203,  141,  138, 1203,  141,  144,
      128,  149,  134,    0,    0, 1186,    0, 1185,  162,  212,
        0,  178,  175, 1148, 1147, 1146, 1145, 1144,  194,  173,
      175,  186,  191, 1203,  181,  180,  209,  204, 1203, 1179,
     1178,  234,  226,  235,  259,  227,  306,  223,  347,  241,
      227,  243,  244, 1203,  239, 1203, 1173, 1203,  241, 1176,

      256,  374,  256,  286,  300,  286,  306,  288,  296,  313,
      303,  304,  372,  307,  313,  323,  314,  350,  353,  381,
      356,  373,  375,  387,  385,  386,  390,  397,  375,  395,
      382,  390,  403,  397,  393,  401, 1203, 1203, 1203,  418,
      423,  424,  449,  430, 1203,  431,  449,  448, 1139,  454,
      436, 1203,  435,  458,  458,  454,  450,  459,  466,  466,
      458,  448,  454,  471,  467,  456,  459, 1203,  477, 1203,
      465, 1166,  465,  485,  499,  500,  488,  488,  495, 1137,
      506,  494,  503,  511,  511,  497,  511,  498,  504,  505,
      513,  556,  503,  533,  539,  541,  550,  544,  545, 1136,

      546, 1135,  559,  556,  545,  549,  554,  552,  560,  566,
      555,  564,  558, 1160, 1203,  104, 1203,  570, 1121,  571,
     1203,  583,  609,  567,  604,  606,  604,  604, 1120,  592,
      602,  598,  611, 1203, 1147,  610,  614,  610,  655,  612,
      620,  615,  612,  636,  658,  636,  658,  662,  645,  653,
      660,  666,  659, 1108,  650,  665,  657,  671,  667, 1203,
     1088, 1203, 1203,  657,  667,  663,  108, 1110, 1116, 1114,
     1203,  185, 1097, 1103, 1102,  668, 1203,  669,  674,  679,
      670,  682,  677,  702, 1203,  690, 1105, 1108,  696,  722,
      698, 1067, 1203,  707,  719,  708,  710,  726,  725,  705,

     1203,  721,  712,  714,  719, 1066,  734, 1203,  723,  716,
      723,  733,  730,  740, 1094,  631,  632,  633,  601,  629,
      626,  627,  628,  739,  732,  746,  743,  754,  741,  760,
      754,  750,  775,  753,  635,  763,  757,  760, 1203,  779,
      762,  764,  768,  773,  789,  786,  783,  788,  790,  776,
     1203,  584,  788,  794,  806,  588,  554,  506,  504,  503,
      801, 1203, 1203, 1203, 1203,  801,  502,  794,  814,  800,
      820,  499,  498,  810,  815,  823,  812,  808,  530,  830,
     1203,  820, 1203,  831,  836,  834,  838, 1203,  820,  839,
      842, 1203,  827,  844,  336,  843,  151,  839,  849,  851,

      852,  850,  870,  858,  855,  858, 1203,  317,  866,  867,
      874,  873,  857,  882,  869,  871,  877,  872, 1203,  889,
     1203,  880,  888,  879,  876,  891,  190,  879, 1203,  341,
      348,  894,  896,  897,  900,  922,  923,  924,  909,  914,
      917,  924,  925, 1203,  916, 1203,  917,  935,  926,  919,
     1203,  928,  936, 1203,  921,  938,  941, 1203,  249,  330,
      332,  940,  274,  273,  945,  946,  956,  958,  957,  944,
      956,  969, 1203,  970,  952,  953,  961,  963,  964,  978,
      978,  981, 1203,  982, 1203,  974,  298,  288,  289,  262,
      987,  983,  984,  990,  991,  992,  993, 1203,  992, 1006,

     1203,  985, 1203, 1203, 1001, 1008, 1007, 1006, 1203, 1203,
     1008, 1005, 1203, 1203, 1203, 1203, 1010, 1015, 1016, 1203,
     1203, 1203, 1203, 1203, 1017, 1203, 1012, 1029, 1031,  262,
     1203, 1032, 1034, 1039, 1040, 1037, 1035,  269, 1040,  260,
     1028, 1027, 1044, 1054, 1040, 1047, 1052,  267,  261, 1203,
     1203, 1203, 1203, 1068, 1203, 1069, 1064, 1057, 1060, 1054,
     1074, 1065, 1063,  258, 1059, 1071, 1203,  248,  197, 1075,
      192,  191, 1071,  162,  150, 1203,  118,  112, 1203,  111,
     1203, 1203, 1134, 1142, 1146, 1154, 1161, 1169, 1172
    } ;

static yyconst flex_int16_t yy_def[590] =
    {   0,
      582,    1,  583,  583,  584,  584,  582,  582,  582,  582,
      582,  582,  585,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  586,  587,  582,
      587,  588,  582,  582,  582,  582,  582,  589,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  586,  587,  582,  588,  582,  582,  582,
      589,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,

      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,

      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,

      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,

      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,

      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,    0,  582,  582,  582,  582,  582,  582,  582
    } ;

static yyconst flex_uint16_t yy_nxt[1273] =
    {   0,
        8,    9,   10,    9,    9,   11,    8,    8,   12,    8,
        8,   13,   14,   14,   14,   14,   14,   14,   14,   14,
       15,    8,   16,    8,    8,   17,    8,   18,   19,    8,
        8,   20,   21,   22,   23,   24,    8,    8,   25,    8,
        8,   26,    8,   27,    8,   15,    8,   16,    8,    8,
       17,    8,   18,   19,    8,    8,   20,   21,   22,   23,
       24,    8,    8,   25,    8,    8,   26,    8,   27,   30,
       30,   30,   30,   36,   39,   31,   43,   31,   34,   34,
       34,   34,   34,   34,   34,   34,   36,   44,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   45,   40,   39,

       46,   43,   47,   48,   49,   50,   38,   41,   51,   52,
       53,   42,   44,   34,   34,   34,   34,  262,  263,  581,
      580,  315,   45,   40,  316,   46,  579,   47,   48,   49,
       50,   38,   41,   51,   52,   53,   42,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   36,   62,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   63,  578,   70,
       71,   72,   73,   74,  430,   75,   76,   77,  431,   78,
      577,   79,   62,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   63,   64,   70,   71,   72,   73,   74,   65,
       75,   76,   77,   66,   78,   67,   79,   68,  320,  575,

      574,  321,  458,  459,  460,  572,  461,   69,   64,   83,
       84,   92,   93,   94,   65,   95,   96,   97,   66,   90,
       67,   36,   68,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   91,   98,   83,   84,   92,   93,   94,   99,
       95,   96,   97,   36,   90,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  103,  104,  571,   91,   98,  118,
      126,  134,  487,  135,   99,  488,  568,  136,  137,  558,
      138,  557,  549,  547,  540,  516,  140,  142,  144,  103,
      104,  105,  106,  107,  118,  126,  134,  108,  135,  109,
      110,  111,  136,  137,  112,  138,  113,  114,  115,  116,

      117,  140,  142,  144,  515,  514,  105,  106,  107,  145,
      148,  152,  108,  513,  109,  110,  111,  493,  492,  112,
      153,  113,  114,  115,  116,  117,  119,  146,  149,  120,
      121,  147,  122,  154,  145,  148,  152,  155,  123,  150,
      156,  161,  124,  125,  490,  153,  162,  163,  151,  489,
      164,  119,  146,  149,  120,  121,  147,  122,  154,  464,
      463,  441,  155,  123,  150,  156,  161,  124,  125,  127,
      128,  162,  163,  151,  129,  164,  165,  166,  170,  130,
      428,  131,  132,   36,  133,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  127,  128,  157,  171,  172,  129,

      158,  165,  166,  170,  130,  167,  131,  132,  168,  133,
      159,  160,  175,  176,  177,  173,  180,  178,  169,  181,
      182,  157,  171,  172,  174,  158,  183,  185,  186,  184,
      167,  179,  187,  168,  188,  159,  160,  175,  176,  177,
      173,  180,  178,  169,  181,  182,  189,  190,  191,  174,
      193,  183,  185,  186,  184,  194,  179,  187,   36,  188,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  195,
      196,  189,  190,  191,  201,  193,  199,  200,  202,  203,
      194,  204,  205,  206,  197,  207,  208,  209,  210,  211,
      212,  213,  214,  215,  195,  196,  216,  217,  218,  201,

      220,  199,  200,  202,  203,  221,  204,  205,  206,  197,
      207,  208,  209,  210,  211,  212,  213,  214,  215,  222,
      223,  216,  217,  218,  224,  220,  225,  226,  228,  229,
      221,  230,  231,  232,  233,  234,  235,  236,  237,  238,
      416,  240,  410,  409,  222,  223,  404,  401,  400,  224,
      399,  225,  226,  228,  229,  241,  230,  231,  232,  233,
      234,  235,  236,  237,  238,   36,  240,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  242,  243,  244,  245,
      241,  246,  248,  250,  251,  252,  253,  254,  255,  256,
      257,  258,  259,  260,  264,  266,  267,  268,  398,  269,

      397,  242,  243,  244,  245,  276,  246,  248,  250,  251,
      252,  253,  254,  255,  256,  257,  258,  259,  260,  264,
      266,  271,  272,  273,  277,  274,  278,  270,  393,  279,
      276,  280,  282,  283,  284,  285,  287,  288,  289,  378,
      291,  365,  364,  363,  362,  361,  360,  359,  358,  277,
      292,  278,  293,  275,  279,  294,  280,  282,  283,  284,
      285,  287,  288,  289,   36,  291,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  292,  295,  293,  296,  297,
      294,  298,  299,  300,  301,  302,  303,  304,  306,  307,
      308,  309,  310,  312,  313,  314,  324,  325,  326,  327,

      328,  295,  329,  296,  297,  330,  298,  299,  300,  301,
      302,  303,  304,  306,  307,  308,  309,  310,  312,  313,
      314,  324,  325,  326,  327,  328,  331,  329,  332,  335,
      330,   36,  336,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  338,  339,  340,  341,  342,  343,  344,  345,
      346,  331,  347,  332,  335,  348,  350,  336,  351,  352,
      353,  354,  355,  356,  366,  367,  368,  338,  339,  340,
      341,  342,  343,  344,  345,  346,  369,  347,  370,  371,
      348,  350,  372,  351,  352,  353,  354,  355,  356,  366,
      367,  368,  373,  374,  377,  375,  379,  380,  381,  382,

      383,  369,  384,  370,  371,  376,  385,  372,  386,  387,
      388,  389,  390,  391,  392,  394,  395,  373,  374,  377,
      375,  379,  380,  381,  382,  383,  396,  384,  402,  403,
      376,  385,  405,  386,  387,  388,  389,  390,  391,  392,
      394,  395,  406,  407,  408,  411,  412,  413,  414,  415,
      417,  396,  418,  402,  403,  419,  420,  405,  421,  422,
      423,  424,  425,  426,  427,  429,  432,  406,  407,  408,
      411,  412,  413,  414,  415,  417,  433,  418,  434,  435,
      419,  420,  436,  421,  422,  423,  424,  425,  426,  427,
      429,  432,  437,  438,  439,  440,  442,  443,  444,  445,

      446,  433,  447,  434,  435,  448,  449,  436,  450,  451,
      452,  453,  454,  455,  456,  457,  462,  437,  438,  439,
      440,  442,  443,  444,  445,  446,  465,  447,  466,  467,
      448,  449,  468,  450,  451,  452,  453,  454,  455,  456,
      457,  462,  469,  470,  471,  472,  473,  474,  475,  476,
      477,  465,  478,  466,  467,  479,  480,  468,  481,  482,
      483,  484,  485,  486,  491,  494,  495,  469,  470,  471,
      472,  473,  474,  475,  476,  477,  496,  478,  497,  498,
      479,  480,  499,  481,  482,  483,  484,  485,  486,  491,
      494,  495,  500,  501,  502,  503,  504,  505,  506,  507,

      508,  496,  509,  497,  498,  510,  511,  499,  512,  517,
      518,  519,  520,  521,  522,  523,  524,  500,  501,  502,
      503,  504,  505,  506,  507,  508,  525,  509,  526,  527,
      510,  511,  528,  512,  517,  518,  519,  520,  521,  522,
      523,  524,  529,  530,  531,  532,  533,  534,  535,  536,
      537,  525,  538,  526,  527,  539,  541,  528,  542,  543,
      544,  545,  546,  548,  550,  551,  552,  529,  530,  531,
      532,  533,  534,  535,  536,  537,  553,  538,  554,  555,
      539,  541,  556,  542,  543,  544,  545,  546,  548,  550,
      551,  552,  559,  560,  561,  562,  563,  564,  565,  566,

      567,  553,  569,  554,  555,  570,  573,  556,  576,  357,
      349,  337,  334,  333,  271,  323,  322,  559,  560,  561,
      562,  563,  564,  565,  566,  567,  319,  569,  318,  317,
      570,  573,  311,  576,   29,   29,   29,   29,   29,   29,
       29,   29,   32,   32,   32,   32,   32,   32,   32,   32,
       37,   37,  305,   37,   54,  286,   54,   54,   54,   54,
       54,   54,   55,   55,  281,  265,   55,   55,   55,   57,
       57,   57,  261,   57,   57,   57,   57,   61,   61,  249,
      247,  227,  219,  198,  141,  139,  101,  100,   89,   88,
       87,   86,   85,   81,   80,   58,   56,   35,  582,   33,

       33,   28,    7,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582
    } ;

static yyconst flex_int16_t yy_chk[1273] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,   13,   15,    3,   17,    4,    9,    9,
        9,    9,   10,   10,   10,   10,   14,   18,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   19,   16,   15,

       20,   17,   21,   22,   23,   24,   13,   16,   25,   26,
       27,   16,   18,   34,   34,   34,   34,  216,  216,  580,
      578,  267,   19,   16,  267,   20,  577,   21,   22,   23,
       24,   13,   16,   25,   26,   27,   16,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   37,   39,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   40,  575,   42,
       43,   44,   46,   47,  397,   49,   50,   51,  397,   52,
      574,   53,   39,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   40,   41,   42,   43,   44,   46,   47,   41,
       49,   50,   51,   41,   52,   41,   53,   41,  272,  572,

      571,  272,  427,  427,  427,  569,  427,   41,   41,   62,
       63,   70,   71,   72,   41,   73,   75,   76,   41,   69,
       41,   60,   41,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   69,   77,   62,   63,   70,   71,   72,   78,
       73,   75,   76,   82,   69,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   83,   84,  568,   69,   77,   86,
       88,   90,  459,   91,   78,  459,  564,   92,   93,  549,
       95,  548,  540,  538,  530,  490,   99,  101,  103,   83,
       84,   85,   85,   85,   86,   88,   90,   85,   91,   85,
       85,   85,   92,   93,   85,   95,   85,   85,   85,   85,

       85,   99,  101,  103,  489,  488,   85,   85,   85,  104,
      106,  108,   85,  487,   85,   85,   85,  464,  463,   85,
      109,   85,   85,   85,   85,   85,   87,  105,  107,   87,
       87,  105,   87,  110,  104,  106,  108,  111,   87,  107,
      112,  114,   87,   87,  461,  109,  115,  116,  107,  460,
      117,   87,  105,  107,   87,   87,  105,   87,  110,  431,
      430,  408,  111,   87,  107,  112,  114,   87,   87,   89,
       89,  115,  116,  107,   89,  117,  118,  119,  121,   89,
      395,   89,   89,  102,   89,  102,  102,  102,  102,  102,
      102,  102,  102,  102,   89,   89,  113,  122,  123,   89,

      113,  118,  119,  121,   89,  120,   89,   89,  120,   89,
      113,  113,  125,  126,  127,  124,  129,  128,  120,  130,
      131,  113,  122,  123,  124,  113,  132,  133,  134,  132,
      120,  128,  135,  120,  136,  113,  113,  125,  126,  127,
      124,  129,  128,  120,  130,  131,  140,  141,  142,  124,
      144,  132,  133,  134,  132,  146,  128,  135,  143,  136,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  147,
      148,  140,  141,  142,  151,  144,  150,  150,  153,  154,
      146,  155,  156,  157,  148,  158,  159,  160,  161,  162,
      163,  164,  165,  166,  147,  148,  167,  169,  171,  151,

      173,  150,  150,  153,  154,  174,  155,  156,  157,  148,
      158,  159,  160,  161,  162,  163,  164,  165,  166,  175,
      176,  167,  169,  171,  177,  173,  178,  179,  181,  182,
      174,  183,  184,  185,  186,  187,  188,  189,  190,  191,
      379,  193,  373,  372,  175,  176,  367,  360,  359,  177,
      358,  178,  179,  181,  182,  194,  183,  184,  185,  186,
      187,  188,  189,  190,  191,  192,  193,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  195,  196,  197,  198,
      194,  199,  201,  203,  204,  205,  206,  207,  208,  209,
      210,  211,  212,  213,  218,  220,  222,  222,  357,  222,

      356,  195,  196,  197,  198,  224,  199,  201,  203,  204,
      205,  206,  207,  208,  209,  210,  211,  212,  213,  218,
      220,  223,  223,  223,  225,  223,  226,  222,  352,  227,
      224,  228,  230,  231,  232,  233,  236,  237,  238,  335,
      240,  323,  322,  321,  320,  319,  318,  317,  316,  225,
      241,  226,  242,  223,  227,  243,  228,  230,  231,  232,
      233,  236,  237,  238,  239,  240,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  241,  244,  242,  245,  246,
      243,  247,  248,  249,  250,  251,  252,  253,  255,  256,
      257,  258,  259,  264,  265,  266,  276,  278,  279,  280,

      281,  244,  282,  245,  246,  283,  247,  248,  249,  250,
      251,  252,  253,  255,  256,  257,  258,  259,  264,  265,
      266,  276,  278,  279,  280,  281,  284,  282,  286,  289,
      283,  290,  291,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  294,  295,  296,  297,  298,  299,  300,  302,
      303,  284,  304,  286,  289,  305,  307,  291,  309,  310,
      311,  312,  313,  314,  324,  325,  326,  294,  295,  296,
      297,  298,  299,  300,  302,  303,  327,  304,  328,  329,
      305,  307,  330,  309,  310,  311,  312,  313,  314,  324,
      325,  326,  331,  332,  334,  333,  336,  337,  338,  340,

      341,  327,  342,  328,  329,  333,  343,  330,  344,  345,
      346,  347,  348,  349,  350,  353,  354,  331,  332,  334,
      333,  336,  337,  338,  340,  341,  355,  342,  361,  366,
      333,  343,  368,  344,  345,  346,  347,  348,  349,  350,
      353,  354,  369,  370,  371,  374,  375,  376,  377,  378,
      380,  355,  382,  361,  366,  384,  385,  368,  386,  387,
      389,  390,  391,  393,  394,  396,  398,  369,  370,  371,
      374,  375,  376,  377,  378,  380,  399,  382,  400,  401,
      384,  385,  402,  386,  387,  389,  390,  391,  393,  394,
      396,  398,  403,  404,  405,  406,  409,  410,  411,  412,

      413,  399,  414,  400,  401,  415,  416,  402,  417,  418,
      420,  422,  423,  424,  425,  426,  428,  403,  404,  405,
      406,  409,  410,  411,  412,  413,  432,  414,  433,  434,
      415,  416,  435,  417,  418,  420,  422,  423,  424,  425,
      426,  428,  436,  437,  438,  439,  440,  441,  442,  443,
      445,  432,  447,  433,  434,  448,  449,  435,  450,  452,
      453,  455,  456,  457,  462,  465,  466,  436,  437,  438,
      439,  440,  441,  442,  443,  445,  467,  447,  468,  469,
      448,  449,  470,  450,  452,  453,  455,  456,  457,  462,
      465,  466,  471,  472,  474,  475,  476,  477,  478,  479,

      480,  467,  481,  468,  469,  482,  484,  470,  486,  491,
      492,  493,  494,  495,  496,  497,  499,  471,  472,  474,
      475,  476,  477,  478,  479,  480,  500,  481,  502,  505,
      482,  484,  506,  486,  491,  492,  493,  494,  495,  496,
      497,  499,  507,  508,  511,  512,  517,  518,  519,  525,
      527,  500,  528,  502,  505,  529,  532,  506,  533,  534,
      535,  536,  537,  539,  541,  542,  543,  507,  508,  511,
      512,  517,  518,  519,  525,  527,  544,  528,  545,  546,
      529,  532,  547,  533,  534,  535,  536,  537,  539,  541,
      542,  543,  554,  556,  557,  558,  559,  560,  561,  562,

      563,  544,  565,  545,  546,  566,  570,  547,  573,  315,
      306,  292,  288,  287,  275,  274,  273,  554,  556,  557,
      558,  559,  560,  561,  562,  563,  270,  565,  269,  268,
      566,  570,  261,  573,  583,  583,  583,  583,  583,  583,
      583,  583,  584,  584,  584,  584,  584,  584,  584,  584,
      585,  585,  254,  585,  586,  235,  586,  586,  586,  586,
      586,  586,  587,  587,  229,  219,  587,  587,  587,  588,
      588,  588,  214,  588,  588,  588,  588,  589,  589,  202,
      200,  180,  172,  149,  100,   97,   81,   80,   68,   67,
       66,   65,   64,   58,   56,   35,   31,   12,    7,    6,

        5,    2,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582,  582,  582,  582,  582,  582,  582,  582,  582,
      582,  582
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[87] =
    {   0,
0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "wrappedkey_lexer.l"
/* wrappedkey lexical analyser */
/* %option debug */
#line 10 "wrappedkey_lexer.l"
#include "config.h"
#include <stdarg.h>
#include "wrappedkey_parser.h"


#line 962 "wrappedkey_lexer.c"

#define INITIAL 0
#define PEM 1
#define STR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 18 "wrappedkey_lexer.l"


#line 1188 "wrappedkey_lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 583 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1203 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "wrappedkey_lexer.l"
{ /* skipping comment */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "wrappedkey_lexer.l"
{ BEGIN(PEM); }
	YY_BREAK
case YY_STATE_EOF(PEM):
#line 23 "wrappedkey_lexer.l"
{ yyerror(NULL, "Unterminated wrapped key block"); yyterminate(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "wrappedkey_lexer.l"
{ BEGIN(INITIAL);  }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 25 "wrappedkey_lexer.l"
{ yylval.pkcs = (unsigned char *)strdup(yytext); return PKCSBLOCK; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 26 "wrappedkey_lexer.l"
{ /* ignore initial line feed */ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "wrappedkey_lexer.l"
{ yylval.val_str.len=0; BEGIN(STR); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 28 "wrappedkey_lexer.l"
{ yylval.val_str.val = strdup(yytext); yylval.val_str.len = strlen(yytext); }
	YY_BREAK
case YY_STATE_EOF(STR):
#line 29 "wrappedkey_lexer.l"
{ yyerror(NULL, "Unterminated quoted string"); yyterminate(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "wrappedkey_lexer.l"
{   /* special case: if we have an empty string, regular rule is never executed */
                /* in which case, we perform the empty string assignment from here */
    if (yylval.val_str.len==0) { yylval.val_str.val=strdup(""); } BEGIN(INITIAL); return STRING;
            }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "wrappedkey_lexer.l"
{ return CTYPE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "wrappedkey_lexer.l"
{ yylval.val_contenttype = ct_appl_p11; return CTYPE_VAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "wrappedkey_lexer.l"
{ return WRAPPING_ALG; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "wrappedkey_lexer.l"
{ yylval.val_wrappingmethod = w_pkcs1_15; return PKCS1ALGO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "wrappedkey_lexer.l"
{ yylval.val_wrappingmethod = w_pkcs1_oaep; return OAEPALGO;  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "wrappedkey_lexer.l"
{ yylval.val_wrappingmethod = w_cbcpad; return CBCPADALGO;  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "wrappedkey_lexer.l"
{ return WRAPPING_KEY; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 45 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_ID; return CKATTR_STR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 46 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_LABEL; return CKATTR_STR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 47 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_CLASS; return CKATTR_CLASS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 48 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_TOKEN; return CKATTR_BOOL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 49 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_KEY_TYPE; return CKATTR_KEY; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 50 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_SUBJECT; return CKATTR_STR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 51 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_ENCRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 52 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_DECRYPT; return CKATTR_BOOL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 53 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_WRAP; return CKATTR_BOOL; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_UNWRAP; return CKATTR_BOOL; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 55 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_SIGN; return CKATTR_BOOL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 56 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_SIGN_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 57 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_VERIFY; return CKATTR_BOOL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 58 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_VERIFY_RECOVER; return CKATTR_BOOL; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 59 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_DERIVE; return CKATTR_BOOL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 60 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_PRIVATE; return CKATTR_BOOL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 61 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_SENSITIVE; return CKATTR_BOOL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 62 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_EXTRACTABLE; return CKATTR_BOOL; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 63 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_MODIFIABLE; return CKATTR_BOOL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 64 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_START_DATE; return CKATTR_DATE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 65 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_END_DATE; return CKATTR_DATE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 66 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_CHECK_VALUE; return CKATTR_STR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 67 "wrappedkey_lexer.l"
{ yylval.ckattr = CKA_EC_PARAMS; return CKATTR_STR; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 69 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_GENERIC_SECRET; return KEYTYPE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 70 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_DES           ; return KEYTYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 71 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_DES2          ; return KEYTYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 72 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_DES3          ; return KEYTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 73 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_AES           ; return KEYTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 74 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_MD5_HMAC      ; return KEYTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 75 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_SHA_1_HMAC    ; return KEYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 76 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_RIPEMD128_HMAC; return KEYTYPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 77 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_RIPEMD160_HMAC; return KEYTYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 78 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_SHA256_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 79 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_SHA384_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 80 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_SHA512_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 81 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_SHA224_HMAC   ; return KEYTYPE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 82 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_RSA           ; return KEYTYPE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 83 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_DH            ; return KEYTYPE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 84 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_DSA           ; return KEYTYPE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 85 "wrappedkey_lexer.l"
{ yylval.val_key = CKK_EC            ; return KEYTYPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_DATA ; return OCLASS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_CERTIFICATE ; return OCLASS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_PUBLIC_KEY ; return OCLASS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_PRIVATE_KEY ; return OCLASS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_SECRET_KEY ; return OCLASS; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_HW_FEATURE ; return OCLASS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_DOMAIN_PARAMETERS ; return OCLASS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_MECHANISM ; return OCLASS; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "wrappedkey_lexer.l"
{ yylval.val_cls = CKO_OTP_KEY ; return OCLASS; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 97 "wrappedkey_lexer.l"
{ return PARAMMGF; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 98 "wrappedkey_lexer.l"
{ yylval.val_mgf = CKG_MGF1_SHA1; return MGFTYPE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 99 "wrappedkey_lexer.l"
{ yylval.val_mgf = CKG_MGF1_SHA224; return MGFTYPE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 100 "wrappedkey_lexer.l"
{ yylval.val_mgf = CKG_MGF1_SHA256; return MGFTYPE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 101 "wrappedkey_lexer.l"
{ yylval.val_mgf = CKG_MGF1_SHA384; return MGFTYPE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 102 "wrappedkey_lexer.l"
{ yylval.val_mgf = CKG_MGF1_SHA512; return MGFTYPE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 104 "wrappedkey_lexer.l"
{ return PARAMHASH; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 105 "wrappedkey_lexer.l"
{ yylval.val_hashalg = CKM_SHA_1; return HASHALG; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 106 "wrappedkey_lexer.l"
{ yylval.val_hashalg = CKM_SHA224; return HASHALG; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 107 "wrappedkey_lexer.l"
{ yylval.val_hashalg = CKM_SHA256; return HASHALG; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 108 "wrappedkey_lexer.l"
{ yylval.val_hashalg = CKM_SHA384; return HASHALG; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 109 "wrappedkey_lexer.l"
{ yylval.val_hashalg = CKM_SHA512; return HASHALG; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 111 "wrappedkey_lexer.l"
{ return PARAMLABEL; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 112 "wrappedkey_lexer.l"
{ return PARAMIV; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 114 "wrappedkey_lexer.l"
{ yylval.val_bool = 1; return TOK_BOOLEAN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 115 "wrappedkey_lexer.l"
{ yylval.val_bool = 0; return TOK_BOOLEAN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 118 "wrappedkey_lexer.l"
{   if(strlen(yytext)%2==1) {
                        yyerror(NULL, "Invalid hexadecimal string <%s>: odd length", yytext);
                        yyterminate();
		    } else {
			yylval.val_str.len = (strlen(yytext)>>1) - 1; /* we skip the '0x' prefix */
			/* convert to hex */
			size_t i;
			char *target = malloc(yylval.val_str.len); 
			if(target==NULL) {
			    yylval.val_str.len = 0 ;
			    yyerror(NULL,"Memory allocation error during lexical analysis of <%s>", yytext);
                            yyterminate();
			}

                        /* we start at yytext[2] */
		        for(i=0;i<yylval.val_str.len; i++) {
                            /* the following trick is needed to have CLANG shut up */
                            /* strictly speaking, %x expects indeed a pointer to an integer */

                            volatile int tmp;
			    sscanf( &yytext[ (i<<1) + 2 ], "%2x", &tmp);
                            target[i] = (unsigned char) tmp;
			}
		        yylval.val_str.val = target; /* then reassign */
                        return STRING;
		    }
                }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 146 "wrappedkey_lexer.l"
{ memcpy(yylval.val_date.as_buffer, yytext, 8); return TOK_DATE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 148 "wrappedkey_lexer.l"
{ yylval.val_dottednumber = strdup(yytext); return DOTTEDNUMBER; }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 150 "wrappedkey_lexer.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "wrappedkey_lexer.l"
{ return yytext[0]; } /* catch-all http://stackoverflow.com/questions/18837828/how-should-i-handle-lexical-errors-in-my-flex-lexer */
	YY_BREAK
/* gives it back to bison, so error comes from parser */
case 86:
YY_RULE_SETUP
#line 155 "wrappedkey_lexer.l"
ECHO;
	YY_BREAK
#line 1728 "wrappedkey_lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 583 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 583 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 582);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 155 "wrappedkey_lexer.l"




void yyerror(wrappedKeyCtx *ctx, const char *s, ...)
{
    va_list ap;
    va_start(ap, s);
    
    fprintf(stderr, "Error during parsing at line %d: ", yylineno);
    vfprintf(stderr, s, ap);
    fprintf(stderr, "\n");

    va_end(ap);
}

